CREATE TABLE `clinical_master_packages` (
  `clinical_master_package_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `package_key` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `manifest_checksum` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `manifest_schema_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `source_status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `governance_status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'unreviewed',
  `production_ready` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `source_runtime_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `license_disposition` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'not_declared',
  `declared_dataset_count` SMALLINT UNSIGNED NOT NULL,
  `observed_dataset_count` SMALLINT UNSIGNED NOT NULL,
  `declared_record_count` BIGINT UNSIGNED NOT NULL,
  `observed_record_count` BIGINT UNSIGNED NOT NULL,
  `source_reference` VARCHAR(255) COLLATE utf8mb4_bin NULL,
  `first_seen_at` DATETIME(6) NOT NULL,
  `last_seen_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`clinical_master_package_id`),
  UNIQUE KEY `uq_clinical_master_package_key_version` (`package_key`, `package_version`),
  KEY `idx_clinical_master_package_checksum` (`manifest_checksum`),
  KEY `idx_clinical_master_package_governance` (`governance_status`),
  KEY `idx_clinical_master_package_license` (`license_disposition`),
  CONSTRAINT `chk_clinical_master_package_checksum` CHECK (`manifest_checksum` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_master_package_source_status` CHECK (`source_status` IN ('draft','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_master_package_governance` CHECK (`governance_status` IN ('unreviewed','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_master_package_license` CHECK (`license_disposition` IN ('not_declared','review_required','cleared','restricted','rejected')),
  CONSTRAINT `chk_clinical_master_package_booleans` CHECK (`production_ready` IN (0,1) AND `source_runtime_enabled` IN (0,1)),
  CONSTRAINT `chk_clinical_master_package_seen_at` CHECK (`last_seen_at` >= `first_seen_at`),
  CONSTRAINT `chk_clinical_master_package_source_reference` CHECK (`source_reference` IS NULL OR `source_reference` <> '' AND LEFT(`source_reference`,1) <> '/' AND LEFT(`source_reference`,1) <> CONVERT(CHAR(92) USING utf8mb4) AND !(`source_reference` REGEXP '^[A-Za-z]:'))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
