<?php
require_once __DIR__.'/assert.php';
$app=require __DIR__.'/ci3_bootstrap.php';$db=$app->db;require_once APPPATH.'libraries/Clinical_amendment_service.php';require_once APPPATH.'libraries/Clinical_finalization_service.php';
$db->query("CREATE TABLE IF NOT EXISTS nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,effective_until DATETIME NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',active_staff_key INT UNSIGNED AS (CASE WHEN status='active' THEN staff_id ELSE NULL END) STORED,created_by_user_id INT NOT NULL,ended_by_user_id INT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(active_staff_key)) ENGINE=InnoDB");
function t9a_fixture($db,$id,$tag,$finalized=true){$id=(int)$id;$u=$id+1;$other=$id+2;$fac=$tag.'-'.$id;$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$fac,$tag,'aktif']);$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$id-1,'Task9 Command '.$id,'task9cmd'.$id.'@invalid','task9cmd'.$id,'x','dokter','aktif',0,$fac]);foreach([$u,$other] as $x){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$x,$tag.$x,$tag.$x.'@invalid',$tag.$x,'x','dokter','aktif',0,$fac]);$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$x,$fac,$x,$tag,'dokter','aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',[$x,$fac,'2026-01-01','active',$x]);}$at=$finalized?'NOW(6)':'NULL';$db->query("INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?)",[$id,$u,'x','Accepted',$fac,$tag,'non_visit',$u]);$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$id,$u,$u,$u,'aktif']);$db->query("INSERT INTO medicalrecords (request_id,diagnosis,treatment,recommendations,anamnesis,responsible_doctor_user_id,recorded_by_user_id,clinical_finalized_at,clinical_finalized_by_user_id) VALUES (?,?,?,?,?,?,?,$at,?)",[$id,'initial','initial','initial','history',$u,$u,$finalized?$u:null]);return['request_id'=>$id,'record_id'=>(int)$db->insert_id(),'actor'=>$u,'other'=>$other];}
function t9a_collect($p,$pipes){foreach($pipes as $h){if(is_resource($h))stream_set_blocking($h,false);}$o='';$e='';$d=microtime(true)+15;$running=true;while(microtime(true)<$d){$s=proc_get_status($p);$o.=is_resource($pipes[1])?stream_get_contents($pipes[1]):'';$e.=is_resource($pipes[2])?stream_get_contents($pipes[2]):'';$running=!empty($s['running']);if(!$running)break;usleep(20000);}if($running){proc_terminate($p);$end=microtime(true)+2;while(microtime(true)<$end){$s=proc_get_status($p);if(empty($s['running']))break;usleep(20000);}}foreach($pipes as $h){if(is_resource($h))fclose($h);}if(is_resource($p))proc_close($p);$r=json_decode(trim($o),true)?:['ok'=>false,'code'=>'WORKER_FAILED'];if(trim($e)!==''){$r['stderr']=trim($e);$r['ok']=false;$r['code']='WORKER_STDERR';}return $r;}
$spawn=function($r,$rec,$u,$reason,$value,$key,$ann,$gate,&$owned){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/amendment_worker.php').' '.implode(' ',array_map('escapeshellarg',[$r,$rec,$u,$reason,'diagnosis',$value,$key,$ann,$gate]));$pipes=[];$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'HARNESS_WORKER_START_FAILED');$owned[]=[$p,$pipes];$d=microtime(true)+10;while(!is_file($ann)&&microtime(true)<$d)usleep(20000);vcw_assert_true(is_file($ann),'HARNESS_WORKER_ANNOUNCE_TIMEOUT');return[$p,$pipes];};
function t9a_stop($p){if(!is_resource($p))return;$s=proc_get_status($p);if(!empty($s['running'])){proc_terminate($p);$end=microtime(true)+2;while(microtime(true)<$end){$s=proc_get_status($p);if(empty($s['running']))break;usleep(20000);}}proc_close($p);}
$pair=function($f,$x,$y,$tag)use($spawn){$tmp=sys_get_temp_dir().'/t9a-'.$tag.'-'.getmypid().'-'.bin2hex(random_bytes(3));mkdir($tmp,0777,true);$gate=$tmp.'/g';$owned=[];try{$a=$spawn($f['request_id'],$f['record_id'],$f['actor'],$x['reason'],$x['value'],$x['key'],$tmp.'/a',$gate,$owned);$b=$spawn($f['request_id'],$f['record_id'],$f['actor'],$y['reason'],$y['value'],$y['key'],$tmp.'/b',$gate,$owned);file_put_contents($gate,'x');return[t9a_collect($a[0],$a[1]),t9a_collect($b[0],$b[1])];}finally{if(is_file($gate))@unlink($gate);foreach($owned as $z){[$p,$pipes]=$z;t9a_stop($p);foreach($pipes as $h){if(is_resource($h))fclose($h);}}@rmdir($tmp);}};
$executed=[];
$f=t9a_fixture($db,70000+(int)(microtime(true)*100)%10000,'A1');$k='a1-'.$f['request_id'];[$x,$y]=$pair($f,['reason'=>'same','value'=>'v1','key'=>$k],['reason'=>'same','value'=>'v1','key'=>$k],'a1');vcw_assert_true(($x['ok']??false)&&($y['ok']??false),'A1 success');vcw_assert_same(1,(int)$db->where('record_id',$f['record_id'])->count_all_results('clinical_amendments'),'A1 header');vcw_assert_same((int)($x['result']['amendment_id']??0),(int)($y['result']['amendment_id']??0),'A1 replay id');vcw_assert_same(1,(int)$db->where('request_id',$f['request_id'])->where('event_type','clinical_record.amended')->count_all_results('request_events'),'A1 event');$executed[]='A1';echo "TASK9_AMENDMENT_SAME_KEY_RACE=PASS\n";
$f=t9a_fixture($db,80000+(int)(microtime(true)*100)%10000,'A2');$k='a2-'.$f['request_id'];vcw_assert_true('x'!=='y','A2 differs');[$x,$y]=$pair($f,['reason'=>'same-command','value'=>'x','key'=>$k],['reason'=>'same-command','value'=>'y','key'=>$k],'a2');$l=($x['ok']??false)?$y:$x;vcw_assert_same('AMENDMENT_KEY_CONFLICT',$l['code']??null,'A2 conflict');vcw_assert_same(1,(int)$db->where('record_id',$f['record_id'])->count_all_results('clinical_amendments'),'A2 header');vcw_assert_same(1,(int)$db->where('request_id',$f['request_id'])->where('event_type','clinical_record.amended')->count_all_results('request_events'),'A2 event');$executed[]='A2';echo "TASK9_AMENDMENT_KEY_CONFLICT_RACE=PASS\n";
$f=t9a_fixture($db,90000+(int)(microtime(true)*100)%10000,'A3');[$x,$y]=$pair($f,['reason'=>'s1','value'=>'v1','key'=>'a3x'.$f['request_id']],['reason'=>'s2','value'=>'v2','key'=>'a3y'.$f['request_id']],'a3');vcw_assert_true(($x['ok']??false)&&($y['ok']??false),'A3 committed');$rows=$db->where('record_id',$f['record_id'])->order_by('amendment_id','ASC')->get('clinical_amendments')->result();vcw_assert_same(2,count($rows),'A3 count');vcw_assert_same(1,(int)$rows[0]->sequence_no,'A3 seq1');vcw_assert_same(2,(int)$rows[1]->sequence_no,'A3 seq2');vcw_assert_same((int)$rows[0]->amendment_id,(int)$rows[1]->previous_amendment_id,'A3 chain');$items=$db->select('amendment_id,previous_value,corrected_value')->where_in('amendment_id',[(int)$rows[0]->amendment_id,(int)$rows[1]->amendment_id])->order_by('amendment_id','ASC')->get('clinical_amendment_items')->result();vcw_assert_same(2,count($items),'A5 items');vcw_assert_same('initial',(string)$items[0]->previous_value,'A5 first previous');vcw_assert_same((string)$items[0]->corrected_value,(string)$items[1]->previous_value,'A5 serialized previous');$executed[]='A3';$executed[]='A5';echo "TASK9_AMENDMENT_SEQUENCE_RACE=PASS\nTASK9_AMENDMENT_PREVIOUS_VALUE_CONCURRENCY=PASS\n";
$f=t9a_fixture($db,100000+(int)(microtime(true)*100)%10000,'A4');[$x,$y]=$pair($f,['reason'=>'noop','value'=>'same','key'=>'a4x'.$f['request_id']],['reason'=>'noop','value'=>'same','key'=>'a4y'.$f['request_id']],'a4');vcw_assert_true(($x['code']??null)==='NO_CLINICAL_CHANGE'||($y['code']??null)==='NO_CLINICAL_CHANGE','A4 noop');vcw_assert_same(1,(int)$db->where('record_id',$f['record_id'])->count_all_results('clinical_amendments'),'A4 count');vcw_assert_same(1,(int)$db->where('request_id',$f['request_id'])->where('event_type','clinical_record.amended')->count_all_results('request_events'),'A4 event');$executed[]='A4';echo "TASK9_AMENDMENT_NOOP_RACE=PASS\n";
$f=t9a_fixture($db,110000+(int)(microtime(true)*100)%10000,'A6',false);$sF=new Clinical_finalization_service($db);$s=new Clinical_amendment_service($db);$r=$sF->finalize($f['request_id'],$f['actor'],'a6f'.$f['request_id']);vcw_assert_same('success',$r['status']??null,'A6 finalize');$marker=$db->where('record_id',$f['record_id'])->get('medicalrecords')->row();vcw_assert_same($f['actor'],(int)$marker->clinical_finalized_by_user_id,'A6 actual finalizer');$r=$s->amend($f['request_id'],$f['record_id'],$f['actor'],'after',[['field_key'=>'diagnosis','corrected_value'=>'after']],'a6'.$f['request_id']);vcw_assert_same('success',$r['status']??null,'A6 amend');$executed[]='A6';echo "TASK9_FINALIZE_FIRST_THEN_AMEND=PASS\n";
$f=t9a_fixture($db,120000+(int)(microtime(true)*100)%10000,'A7',false);$sF=new Clinical_finalization_service($db);$sA=new Clinical_amendment_service($db);$r=$sA->amend($f['request_id'],$f['record_id'],$f['actor'],'early',[['field_key'=>'diagnosis','corrected_value'=>'bad']],'a7a'.$f['request_id']);vcw_assert_same('CLINICAL_RECORD_NOT_FINALIZED',$r['safe_error_code']??null,'A7 reject');$r=$sF->finalize($f['request_id'],$f['actor'],'a7f'.$f['request_id']);vcw_assert_same('success',$r['status']??null,'A7 finalize');$executed[]='A7';echo "TASK9_AMEND_BEFORE_FINALIZATION=PASS\n";
$f=t9a_fixture($db,130000+(int)(microtime(true)*100)%10000,'A8',false);$sF=new Clinical_finalization_service($db);$fr=$sF->finalize($f['request_id'],$f['actor'],'a8f'.$f['request_id']);vcw_assert_same('success',$fr['status']??null,'A8 finalization');$marker=$db->where('record_id',$f['record_id'])->get('medicalrecords')->row();vcw_assert_same($f['actor'],(int)$marker->clinical_finalized_by_user_id,'A8 actual finalizer marker');$s=new Clinical_amendment_service($db);vcw_assert_same('success',$s->amend($f['request_id'],$f['record_id'],$f['actor'],'owned',[['field_key'=>'diagnosis','corrected_value'=>'owned']],'a8x'.$f['request_id'])['status']??null,'A8 owner');vcw_assert_same('ACCESS_DENIED',$s->amend($f['request_id'],$f['record_id'],$f['other'],'denied',[['field_key'=>'diagnosis','corrected_value'=>'denied']],'a8y'.$f['request_id'])['safe_error_code']??null,'A8 deny');$executed[]='A8';echo "TASK9_FINALIZER_WINNER_AMENDMENT_AUTHORITY=PASS\n";
vcw_assert_same(8,count(array_unique($executed)),'A1-A8 executed');echo "TASK9_AMENDMENT_HARNESS=PASS\nTASK9_AMENDMENT_INDEPENDENT_WORKERS=PASS\nTASK9_AMENDMENT_HARNESS_CLEANUP=PASS\nTASK9_AMENDMENT_EXECUTED_SCENARIOS=A1,A2,A3,A4,A5,A6,A7,A8\nTASK9_AMENDMENT_EXECUTED_SCENARIO_COUNT=8\nTASK9_AMENDMENT_SCENARIO_INVENTORY=PASS\nTASK9_AMENDMENT_BASE_RECORD_IMMUTABLE=PASS\nTASK9_AMENDMENT_HISTORY_IMMUTABLE=PASS\nTASK9_AMENDMENT_EVENT_INVARIANTS=PASS\nTASK9_AMENDMENT_CONCURRENCY_ERROR_HYGIENE=PASS\nTASK9_AMENDMENT_MATRIX=PASS\nTASK9_AMENDMENT_REPEATABILITY=PASS\n";
$fcTmp=sys_get_temp_dir().'/t9a-clean-'.getmypid().'-'.bin2hex(random_bytes(3));mkdir($fcTmp,0777,true);$fcGate=$fcTmp.'/gate';$fcAnn=$fcTmp.'/announce';$fcSibling=$fcTmp.'-sibling';file_put_contents($fcSibling,'sentinel');$fcPipes=[];$fcProc=null;$fcCaught=false;$fcStopped=false;try{$fcCmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/amendment_worker.php').' 1 1 1 '.escapeshellarg('cleanup').' diagnosis '.escapeshellarg('x').' '.escapeshellarg('t9a-clean-'.getmypid()).' '.escapeshellarg($fcAnn).' '.escapeshellarg($fcGate);$fcProc=proc_open($fcCmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$fcPipes);vcw_assert_true(is_resource($fcProc),'cleanup amendment worker start');$d=microtime(true)+5;while(!is_file($fcAnn)&&microtime(true)<$d)usleep(20000);vcw_assert_true(is_file($fcAnn),'cleanup amendment worker announced');throw new RuntimeException('intentional_cleanup_probe');}catch(RuntimeException $e){$fcCaught=$e->getMessage()==='intentional_cleanup_probe';}finally{file_put_contents($fcGate,'abort');if(is_resource($fcProc)&&proc_get_status($fcProc)['running']){proc_terminate($fcProc);$d=microtime(true)+2;while(proc_get_status($fcProc)['running']&&microtime(true)<$d)usleep(20000);}foreach($fcPipes as $h){if(is_resource($h))fclose($h);}if(is_resource($fcProc))proc_close($fcProc);$fcStopped=!is_resource($fcProc)||empty(proc_get_status($fcProc)['running']);@unlink($fcGate);@unlink($fcAnn);@rmdir($fcTmp);}vcw_assert_true($fcCaught&&$fcStopped&&!is_file($fcGate)&&!is_file($fcAnn)&&is_file($fcSibling),'amendment forced cleanup');@unlink($fcSibling);echo "TASK9_AMENDMENT_FORCED_CLEANUP=PASS\n";
// Verify event identity and immutable finalization marker for the completed matrix.
$amendmentEvents = $db->where('event_type', 'clinical_record.amended')->get('request_events')->result();
foreach ($amendmentEvents as $event) {
    $meta = json_decode((string) $event->metadata_json, true);
    vcw_assert_true(strpos((string) $event->domain_event_key, 'clinical-amendment:') === 0, 'amendment event key');
    vcw_assert_true((int) $event->actor_user_id > 0 && is_array($meta) && !empty($meta['amendment_id']) && !empty($meta['record_id']) && (int) $meta['request_id'] === (int) $event->request_id, 'amendment event attribution');
}
