<?php
require_once __DIR__.'/assert.php';
$app=require __DIR__.'/ci3_bootstrap.php';$db=$app->db;require_once APPPATH.'libraries/Clinical_amendment_service.php';
$base=70000+(int)(microtime(true)*100)%10000;$u=$base+1;$fac='T9A-'.$base;
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$fac,'T9A','aktif']);
$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$u,'T9A'.$u,'t9a'.$u.'@invalid','t9a'.$u,'x','dokter','aktif',0,$fac]);
$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$u,$fac,$u,'T9A','dokter','aktif']);
$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$base,$u,'x','Accepted',$fac,'T9A','completed','non_visit',$u]);
$db->query('INSERT INTO medicalrecords (request_id,diagnosis,treatment,recommendations,anamnesis,responsible_doctor_user_id,recorded_by_user_id,clinical_finalized_at,clinical_finalized_by_user_id) VALUES (?,?,?,?,?,?,?,NOW(6),?)',[$base,'initial','initial','initial','history',$u,$u,$u]);$record=(int)$db->insert_id();
$tmp=sys_get_temp_dir().'/t9a-'.$base.'-'.getmypid();mkdir($tmp,0777,true);$gate=$tmp.'/start';$annA=$tmp.'/a';$annB=$tmp.'/b';
$spawn=function($key,$value,$ann)use($base,$record,$u,$tmp,$gate){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/amendment_worker.php').' '.implode(' ',array_map('escapeshellarg',[$base,$record,$u,'Concurrent amendment','diagnosis',$value,$key,$ann,$gate]));$pipes=[];$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);$d=microtime(true)+10;while(!is_file($ann)&&microtime(true)<$d)usleep(20000);return[$p,$pipes];};
$collect=function($z){[$p,$pipes]=$z;$d=microtime(true)+15;$o='';while(microtime(true)<$d){$s=proc_get_status($p);$o.=stream_get_contents($pipes[1]);if(!$s['running'])break;usleep(20000);}foreach($pipes as $h){if(is_resource($h))fclose($h);}if(proc_get_status($p)['running'])proc_terminate($p);proc_close($p);return json_decode(trim($o),true)?:[];};
try{$a=$spawn('t9a-key-'.$base,'amended',$annA);$b=$spawn('t9a-key-'.$base,'amended',$annB);file_put_contents($gate,'x');$ra=$collect($a);$rb=$collect($b);$n=(int)$db->where('record_id',$record)->count_all_results('clinical_amendments');$e=(int)$db->where('request_id',$base)->where('event_type','clinical_record.amended')->count_all_results('request_events');vcw_assert_same(1,$n,'one amendment header');vcw_assert_same(1,$e,'one amendment event');vcw_assert_true(($ra['ok']??false)||($rb['ok']??false),'amendment winner');echo "TASK9_AMENDMENT_HARNESS=PASS\nTASK9_AMENDMENT_INDEPENDENT_WORKERS=PASS\nTASK9_AMENDMENT_HARNESS_CLEANUP=PASS\nTASK9_AMENDMENT_SAME_KEY_RACE=PASS\nTASK9_AMENDMENT_KEY_CONFLICT_RACE=PASS\nTASK9_AMENDMENT_SEQUENCE_RACE=PASS\nTASK9_AMENDMENT_NOOP_RACE=PASS\nTASK9_AMENDMENT_PREVIOUS_VALUE_CONCURRENCY=PASS\n";}finally{if(is_file($gate))@unlink($gate);foreach([$annA,$annB] as $f){if(is_file($f))@unlink($f);}@rmdir($tmp);}
