<?php
require_once __DIR__ . '/assert.php';
$app = require __DIR__ . '/ci3_bootstrap.php'; $db = $app->db;
$app->config->set('care_team_workflow_enabled', true); $app->config->set('realtime_requests_enabled', false); $app->config->set('realtime_client_enabled', false);
require_once APPPATH . 'libraries/Clinical_closure_service.php';
$db->query("CREATE TABLE IF NOT EXISTS nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',active_staff_key INT UNSIGNED AS (CASE WHEN status='active' THEN staff_id ELSE NULL END) STORED,created_by_user_id INT NOT NULL,PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(active_staff_key)) ENGINE=InnoDB");
$base = random_int(300000, 900000); $fac = 'T10C-' . $base; $actor = $base + 1; $cmd = $base - 1;
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)', array($fac, 'Task 10 Concurrency', 'aktif'));
foreach (array($cmd => 'Command', $actor => 'Doctor', $base + 2 => 'Owner') as $uid => $label) { $db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)', array($uid, 'T10 ' . $label, 't10c' . $uid . '@invalid', 't10c' . $uid, 'x', 'dokter', 'aktif', 0, $fac)); }
$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)', array($actor, $fac, $actor, 'T10 Doctor', 'dokter', 'aktif'));
$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)', array($actor, $fac, '2026-01-01', 'active', $actor));
$make = function ($requestId, $owner, $key) use ($db, $actor, $fac) { $db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?)', array($requestId, $owner, 'synthetic', 'Accepted', $fac, 'Task 10 Concurrency', 'non_visit', $actor)); $db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))', array($requestId, $actor, $actor, $actor, 'aktif')); $db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,created_by_user_id,idempotency_key,created_at) VALUES (?,?,?,?,?,?,NOW(6))', array($requestId, 1, 'non_visit', null, $actor, $key)); $db->query('INSERT INTO medicalrecords (request_id,diagnosis,treatment,recommendations,anamnesis,responsible_doctor_user_id,recorded_by_user_id,clinical_finalized_at,clinical_finalized_by_user_id) VALUES (?,?,?,?,?,?,?,NOW(6),?)', array($requestId, 'd', 't', 'r', 'a', $actor, $actor, $actor)); };
$collect = function ($p, $pipes) { foreach ($pipes as $h) { stream_set_blocking($h, false); } $deadline = microtime(true) + 12; $out = ''; $err = ''; while (microtime(true) < $deadline) { $out .= stream_get_contents($pipes[1]); $err .= stream_get_contents($pipes[2]); $st = proc_get_status($p); if (!$st['running']) { $out .= stream_get_contents($pipes[1]); $err .= stream_get_contents($pipes[2]); break; } usleep(20000); } if (is_resource($p) && proc_get_status($p)['running']) proc_terminate($p); foreach ($pipes as $h) if (is_resource($h)) fclose($h); if (is_resource($p)) proc_close($p); $decoded = json_decode(trim($out), true) ?: array(); if ($err !== '') { $decoded['_stderr'] = trim($err); } return $decoded; };
$runRace = function ($requestId, $actorA, $actorB, $keyA, $keyB) use ($collect) { $procs = array(); foreach (array(array($actorA,$keyA),array($actorB,$keyB)) as $x) { $pipes = array(); $cmd = escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg(__DIR__ . '/clinical_closure_worker.php') . ' ' . $requestId . ' ' . $x[0] . ' non_visit ' . escapeshellarg($x[1]); $p = proc_open($cmd, array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')), $pipes); $procs[] = array($p,$pipes); } $r = array(); foreach ($procs as $z) $r[] = $collect($z[0],$z[1]); return $r; };
$runDifferentRequestsRace = function ($requestA, $requestB, $actorA, $actorB, $key) use ($collect) { $procs = array(); foreach (array(array($requestA, $actorA), array($requestB, $actorB)) as $x) { $pipes = array(); $cmd = escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg(__DIR__ . '/clinical_closure_worker.php') . ' ' . $x[0] . ' ' . $x[1] . ' non_visit ' . escapeshellarg($key); $p = proc_open($cmd, array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')), $pipes); $procs[] = array($p, $pipes); } $r = array(); foreach ($procs as $z) $r[] = $collect($z[0], $z[1]); return $r; };
$make($base + 10, $base + 2, 't10c-d1-' . $base); $same = $runRace($base + 10, $actor, $actor, 't10c-same-' . $base, 't10c-same-' . $base); vcw_assert_same('success', $same[0]['status'] ?? null, 'same-key winner'); vcw_assert_same('success', $same[1]['status'] ?? null, 'same-key replay'); vcw_assert_same(1, (int) $db->where('request_id', $base + 10)->count_all_results('clinical_closure_operations'), 'one same-key receipt');
$make($base + 11, $base + 2, 't10c-d2-' . $base); $different = $runRace($base + 11, $actor, $actor, 't10c-k1-' . $base, 't10c-k2-' . $base); $statuses = array($different[0]['status'] ?? '', $different[1]['status'] ?? ''); vcw_assert_same(1, count(array_filter($statuses, function ($s) { return $s === 'success'; })), 'different-key one winner'); vcw_assert_true(in_array('CLINICAL_ALREADY_CLOSED', array($different[0]['safe_error_code'] ?? '', $different[1]['safe_error_code'] ?? ''), true), 'different-key loser');
$make($base + 12, $base + 2, 't10c-d3-' . $base); $globalKey = 't10c-global-' . $base; $make($base + 13, $base + 2, 't10c-d4-' . $base); $global = $runDifferentRequestsRace($base + 12, $base + 13, $actor, $actor, $globalKey); $globalCodes = array($global[0]['safe_error_code'] ?? '', $global[1]['safe_error_code'] ?? ''); vcw_assert_same(1, count(array_filter(array($global[0]['status'] ?? '', $global[1]['status'] ?? ''), function ($s) { return $s === 'success'; })), 'global key one success ' . json_encode($global)); vcw_assert_true(in_array('CLOSURE_KEY_CONFLICT', $globalCodes, true), 'global key conflict loser ' . json_encode($global)); vcw_assert_same(1, (int) $db->where('idempotency_key', $globalKey)->count_all_results('clinical_closure_operations'), 'global key one owner');
echo "TASK10_CLOSURE_SAME_KEY_RACE=PASS\nTASK10_CLOSURE_DIFFERENT_KEY_RACE=PASS\nTASK10_CLOSURE_GLOBAL_KEY_COLLISION=PASS\nTASK10_CLOSURE_CONCURRENCY=PASS\n";
