<?php
require_once __DIR__.'/assert.php';
$app=require __DIR__.'/ci3_bootstrap.php'; $db=$app->db;
require_once APPPATH.'libraries/Clinical_finalization_service.php';
$db->query("CREATE TABLE IF NOT EXISTS nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,effective_until DATETIME NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',active_staff_key INT UNSIGNED AS (CASE WHEN status='active' THEN staff_id ELSE NULL END) STORED,created_by_user_id INT NOT NULL,ended_by_user_id INT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(active_staff_key)) ENGINE=InnoDB");
$base=50000+(int)(microtime(true)*100)%10000; $rd=$base+1; $perf=$base+2; $cmd=$base-1; $fac='T9F-'.$base;
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$fac,'T9F','aktif']);
foreach([[$cmd,'dokter'],[$rd,'dokter'],[$perf,'dokter']] as $x){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$x[0],'T9F'.$x[0],'t9f'.$x[0].'@invalid','t9f'.$x[0],'x',$x[1],'aktif',0,$fac]);}
foreach([$rd,$perf] as $u){$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$u,$fac,$u,'T9F','dokter','aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',[$u,$fac,'2026-01-01','active',$u]);}
// The lower-ID no-staff user is the canonical command center; both actors are canonical personal doctors.
$cmdIdentity=doclinc_dokter_identity_context($cmd,true);$rdIdentity=doclinc_dokter_identity_context($rd,true);$perfIdentity=doclinc_dokter_identity_context($perf,true);vcw_assert_true($cmd<$rd&&$cmd<$perf&&!empty($cmdIdentity['valid'])&&($cmdIdentity['account_type']??null)==='command_center','lower-ID canonical command-center fixture');vcw_assert_true(!empty($rdIdentity['valid'])&&($rdIdentity['account_type']??null)==='personal'&&(int)($rdIdentity['staff_id']??0)===$rd,'canonical responsible-doctor fixture');vcw_assert_true(!empty($perfIdentity['valid'])&&($perfIdentity['account_type']??null)==='personal'&&(int)($perfIdentity['staff_id']??0)===$perf,'canonical performer fixture');
$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id,visit_performer_user_id) VALUES (?,?,?,?,?,?,?,?,?,?)',[$base,$rd,'x','Accepted',$fac,'T9F','completed','visit',$rd,$perf]);
$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$base,$rd,$rd,$rd,'aktif']); $rdAssign=(int)$db->insert_id();
$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,created_by_user_id,idempotency_key,created_at) VALUES (?,?,?,?,?,?,NOW(6))',[$base,1,'visit','routine',$rd,'t9f-d-'.$base]);
$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at,completed_at) VALUES (?,?,?,?,?,NOW(6),NOW(6))',[$base,$perf,$perf,$rd,'selesai']); $a=(int)$db->insert_id();
$db->query('INSERT INTO visit_results (request_id,visit_assignment_id,version_no,performer_user_id,performer_staff_id,status,draft_revision,findings_json,actions_json,created_at,updated_at,submitted_at,submitted_by_user_id,submission_key) VALUES (?,?,?,?,?,"submitted",0,"[]","[]",NOW(6),NOW(6),NOW(6),?,?)',[$base,$a,$perf,$perf,$perf,$perf,'t9f-r-'.$base]); $res=(int)$db->insert_id();
$db->query('INSERT INTO clinical_reviews (request_id,visit_result_id,reviewer_user_id,responsible_assignment_id,reviewer_visit_assignment_id,decision,reviewed_at,idempotency_key) VALUES (?,?,?,?,?,?,NOW(6),?)',[$base,$res,$rd,$rdAssign,null,'approved','t9f-review-'.$base]);
$db->query('INSERT INTO medicalrecords (request_id,diagnosis,treatment,recommendations,anamnesis,responsible_doctor_user_id,recorded_by_user_id) VALUES (?,?,?,?,?,?,?)',[$base,'d','t','r','a',$rd,$perf]); $record=(int)$db->insert_id();
$tmp=sys_get_temp_dir().'/t9f-'.$base.'-'.getmypid(); mkdir($tmp,0777,true); $gate=$tmp.'/start'; $procs=[];
$start=function($args)use($tmp,$gate,&$procs){$ann=(string)$args[3];$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/finalization_worker.php').' '.implode(' ',array_map('escapeshellarg',$args));$pipes=[];$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($p))throw new RuntimeException('worker_start_failed');$procs[]=[$p,$pipes,$ann];$deadline=microtime(true)+10;while(!is_file($ann)&&microtime(true)<$deadline)usleep(20000);if(!is_file($ann))throw new RuntimeException('worker_announce_timeout');return[$p,$pipes,$ann];};
$collect=function($z){[$p,$pipes]=$z;$deadline=microtime(true)+15;$out='';while(microtime(true)<$deadline){$st=proc_get_status($p);$out.=stream_get_contents($pipes[1]);if(!$st['running'])break;usleep(20000);}$err=stream_get_contents($pipes[2]);foreach($pipes as $h){if(is_resource($h))fclose($h);}if(proc_get_status($p)['running'])proc_terminate($p);proc_close($p);return json_decode(trim($out),true)?:['ok'=>false,'error'=>'worker_failed','stderr'=>$err];};
try{$sameKey='t9f-final-'.$base;$x=$start([$base,$rd,$sameKey,$tmp.'/a',$gate]);$y=$start([$base,$rd,$sameKey,$tmp.'/b',$gate]);file_put_contents($gate,'x');$rx=$collect($x);$ry=$collect($y);$count=(int)$db->where('request_id',$base)->where('event_type','clinical_record.finalized')->count_all_results('request_events');vcw_assert_same(1,$count,'one finalization event');vcw_assert_same(1,(int)$db->where('request_id',$base)->where('clinical_finalized_at IS NOT NULL',null,false)->count_all_results('medicalrecords'),'one finalized record');vcw_assert_true(($rx['ok']??false)&&($ry['ok']??false),'same actor/key finalization replay succeeds');vcw_assert_same((int)($rx['result']['record_id']??0),(int)($ry['result']['record_id']??0),'same actor/key returns canonical record');vcw_assert_same(1,(int)!empty($rx['result']['idempotent'])+(int)!empty($ry['result']['idempotent']),'same actor/key has one exact replay');echo "TASK9_FINALIZATION_HARNESS=PASS\nTASK9_FINALIZATION_INDEPENDENT_WORKERS=PASS\nTASK9_FINALIZATION_HARNESS_CLEANUP=PASS\nTASK9_FINALIZATION_SAME_KEY_EXACT_REPLAY=PASS\n";}finally{if(is_file($gate))@unlink($gate);foreach($procs as $z){[$p,$pipes]=$z;if(is_resource($p)){if(proc_get_status($p)['running'])proc_terminate($p);foreach($pipes as $h){if(is_resource($h))fclose($h);}proc_close($p);}}foreach(glob($tmp.'/*')?:[] as $f){@unlink($f);}@rmdir($tmp);}
