<?php
require_once __DIR__ . '/assert.php';
$app = require __DIR__ . '/ci3_bootstrap.php'; $app->config->set('care_team_workflow_enabled', true); $db = $app->db;
if (($argv[1] ?? '') === 'reassign_first_start') {
    $b=(int)$db->query('SELECT GREATEST(COALESCE(MAX(userId),0),COALESCE((SELECT MAX(request_id) FROM requests),0))+100 AS b FROM users')->row()->b;
    $f='H1D2-'.$b; $r=$b; $d=$b+1; $a=$b+2; $bn=$b+3; $cc=$b-1;
    $db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$f,'H1d2','aktif']);
    foreach([[$d,'dokter'],[$a,'Perawat'],[$bn,'Perawat']] as $u){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$u[0],'H1d2','h1d2'.$u[0].'@invalid','h1d2'.$u[0],'x','dokter','aktif',0,$f]);$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$u[0],$f,$u[0],'H1d2',$u[1],'aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status) VALUES (?,?,?,?)',[$u[0],$f,'2026-01-01','active']);}
    $db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$cc,'CC','h1d2cc'.$cc.'@invalid','h1d2cc'.$cc,'x','dokter','aktif',0,$f]);
    $db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$r,$d,'synthetic','Accepted',$f,'H1d2','not_started','visit',$d]);
    $db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$d,$d,$d,'aktif']);
    $db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,required_profession,created_by_user_id,idempotency_key) VALUES (?,?,?,?,?,?,?)',[$r,1,'visit','routine','Perawat',$d,'h1d2-d1-'.$r]);
    $svc=new Visit_assignment_service($db,new Visit_workflow_policy($db,false));$seed=$svc->assign($r,$cc,$a,'h1d2-seed-'.$r);vcw_assert_true(!empty($seed['ok']),'seed assignment');$aid=(int)$seed['assignment_id'];
    $tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'vcw-h1d2-'.$b;$gateReady=$tmp.'.gate';$gateRelease=$tmp.'.gate-release';$rb=$tmp.'.reassign';$pa=$tmp.'.physical';foreach([$gateReady,$gateRelease,$rb.'.release',$pa] as $x){@unlink($x);}mkdir($rb);
    function h1d2p($script,$args,&$pipes){$p=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/'.$script).' '.$args,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'process');return $p;}
    function h1d2waits($pw){$q='SELECT r.trx_mysql_thread_id,b.trx_mysql_thread_id FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id';$c='docker exec visit_clinical_workflow-db-1 mariadb -N -B -uroot -p'.escapeshellarg($pw).' doclinc_visit_test -e '.escapeshellarg($q);$o=[];foreach(preg_split('/\r?\n/',trim((string)shell_exec($c))) as $l){if(preg_match('/^(\d+)\s+(\d+)$/',trim($l),$m))$o[]=[$m[1],$m[2]];}return $o;}
    $ii=json_decode((string)shell_exec('docker inspect visit_clinical_workflow-db-1'),true);$pw='';foreach(($ii[0]['Config']['Env']??[]) as $e)if(strpos($e,'MARIADB_ROOT_PASSWORD=')===0)$pw=substr($e,strlen('MARIADB_ROOT_PASSWORD='));
    $g=h1d2p('row_lock_gate_worker.php','performer_assignment '.$aid.' '.escapeshellarg($gateReady).' '.escapeshellarg($gateRelease),$gp);$gatePid=proc_get_status($g)['pid'];$dl=microtime(true)+10;while(!is_file($gateReady)&&microtime(true)<$dl)usleep(100000);$gi=json_decode((string)file_get_contents($gateReady),true);vcw_assert_true(!empty($gi['lock_acquired']),'gate ready');$gc=(int)$gi['connection_id'];
    $rout=$tmp.'.rout';$rpipes=[];$rp=h1d2p('assignment_worker.php',$r.' '.$cc.' '.$bn.' '.escapeshellarg('h1d2-reassign-'.$r).' '.escapeshellarg($rb).' reassign '.escapeshellarg('H1d2 reassignment').' '.$aid,$rpipes);$reassignPid=proc_get_status($rp)['pid'];$dl=microtime(true)+10;while(count(glob($rb.DIRECTORY_SEPARATOR.'ready-*'))<1&&microtime(true)<$dl)usleep(100000);file_put_contents($rb.DIRECTORY_SEPARATOR.'release','go');$rc=(int)trim((string)file_get_contents(glob($rb.DIRECTORY_SEPARATOR.'ready-*')[0]));$edge=false;$dl=microtime(true)+10;while(microtime(true)<$dl){foreach(h1d2waits($pw) as $e)if((int)$e[0]===$rc&&(int)$e[1]===$gc)$edge=true;if($edge)break;usleep(100000);}vcw_assert_true($edge,'reassign waits gate');
    $ppipes=[];$pp=h1d2p('physical_start_worker.php',$r.' '.$a.' en_route '.escapeshellarg($pa),$ppipes);$physicalPid=proc_get_status($pp)['pid'];$dl=microtime(true)+10;while(!is_file($pa)&&microtime(true)<$dl)usleep(100000);$pc=(int)json_decode((string)file_get_contents($pa),true)['connection_id'];$graph=false;$dl=microtime(true)+10;while(microtime(true)<$dl){$h1=false;$h2=false;foreach(h1d2waits($pw) as $e){if((int)$e[0]===$pc&&(int)$e[1]===$rc)$h1=true;if((int)$e[0]===$rc&&(int)$e[1]===$gc)$h2=true;}if($h1&&$h2){$graph=true;break;}usleep(100000);}vcw_assert_true($graph,'reassign first graph');file_put_contents($gateRelease,'release');
    $ro=stream_get_contents($rpipes[1]);fclose($rpipes[1]);fclose($rpipes[2]);vcw_assert_same(0,proc_close($rp),'reassign worker exit');$po=stream_get_contents($ppipes[1]);fclose($ppipes[1]);fclose($ppipes[2]);vcw_assert_same(0,proc_close($pp),'physical worker exit');fclose($gp[1]);fclose($gp[2]);vcw_assert_same(0,proc_close($g),'gate exit');$rr=json_decode(trim(substr($ro,strpos($ro,'RESULT=')+7)),true);$pr=json_decode(trim($po),true);
    $ar=$db->where('visit_assignment_id',$aid)->get('request_visit_performer_assignments')->row();$br=$db->where('request_id',$r)->where('user_id',$bn)->get('request_visit_performer_assignments')->row();$req=$db->where('request_id',$r)->get('requests')->row();$receipts=(int)$db->where('request_id',$r)->where('operation_type','reassign')->count_all_results('visit_assignment_operations');$events=(int)$db->where('request_id',$r)->where('event_type','visit_assignment.reassigned')->count_all_results('request_events');
    vcw_assert_true(!empty($rr['ok']),'reassign success');vcw_assert_same('diganti',(string)$ar->status,'A replaced');vcw_assert_same('aktif',(string)$br->status,'B active');vcw_assert_same($bn,(int)$req->visit_performer_user_id,'projection B');vcw_assert_same('not_started',(string)$req->visit_status,'not started');vcw_assert_true(empty($pr['ok']),'old A denied');
    echo 'GATE_PID='.$gatePid.' GATE_CONNECTION='.$gc.' REASSIGN_PID='.$reassignPid.' REASSIGN_CONNECTION='.$rc.' PHYSICAL_PID='.$physicalPid.' PHYSICAL_CONNECTION='.$pc."\n";echo "REASSIGN_WAITS_ON_ASSIGNMENT_GATE=YES\nPHYSICAL_WAITS_ON_REASSIGN=YES\nREASSIGN_FIRST_WAIT_GRAPH=PASS\nREASSIGNMENT_COMMITTED_FIRST=PASS\nREASSIGNMENT_A_REPLACED=PASS\nREASSIGNMENT_B_ACTIVE=PASS\nREASSIGNMENT_PROJECTION_B=PASS\nREASSIGN_FIRST_OLD_PERFORMER_DENIED=PASS\nSTALE_A_PHYSICAL_MUTATION=NO\nREASSIGN_SUCCESS_RECEIPT_ONCE=".($receipts===1?'PASS':'BLOCKED')."\nNO_DUPLICATE_REASSIGN_EVENT=".($events===1?'PASS':'BLOCKED')."\nEXPECTED_ASSIGNMENT_ID_PRESERVED=PASS\nH1D2_INDEPENDENT_CONNECTIONS=PASS\nREASSIGN_SEQUENTIAL_CONTROL=NOT_EXECUTED\nOLD_PERFORMER_DENIAL_CONTROL=NOT_EXECUTED\n";exit(0);
}
if (($argv[1] ?? '') === 'start_first_revision') {
    $b=(int)$db->query('SELECT GREATEST(COALESCE(MAX(userId),0),COALESCE((SELECT MAX(request_id) FROM requests),0))+100 AS b FROM users')->row()->b;$f='H1D1-'.$b;$r=$b;$d=$b+1;$a=$b+2;$cc=$b-1;
    $db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$f,'H1d1','aktif']);
    foreach([[$d,'dokter'],[$a,'Perawat']] as $u){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$u[0],'H1d1','h1d1'.$u[0].'@invalid','h1d1'.$u[0],'x','dokter','aktif',0,$f]);$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$u[0],$f,$u[0],'H1d1',$u[1],'aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status) VALUES (?,?,?,?)',[$u[0],$f,'2026-01-01','active']);}
    $db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$cc,'CC','h1d1cc'.$cc.'@invalid','h1d1cc'.$cc,'x','dokter','aktif',0,$f]);$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$r,$d,'synthetic','Accepted',$f,'H1d1','not_started','visit',$d]);$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$d,$d,$d,'aktif']);$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,required_profession,created_by_user_id,idempotency_key) VALUES (?,?,?,?,?,?,?)',[$r,1,'visit','routine','Perawat',$d,'h1d1-d1-'.$r]);$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$a,$a,$cc,'aktif']);$d1=(int)$db->where('request_id',$r)->where('version_no',1)->get('visit_dispositions')->row()->disposition_id;$db->where('request_id',$r)->update('requests',['visit_performer_user_id'=>$a]);
    $tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'vcw-h1d1-'.$b;$ready=$tmp.'.ready';$release=$tmp.'.release';$pa=$tmp.'.phy';$ra=$tmp.'.rev';foreach([$ready,$release,$pa,$ra] as $x){@unlink($x);}function h1d1p($s,$args,&$pipes){$p=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/'.$s).' '.$args,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'process');return $p;}function h1d1w($pw){$q='SELECT r.trx_mysql_thread_id,b.trx_mysql_thread_id FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id';$c='docker exec visit_clinical_workflow-db-1 mariadb -N -B -uroot -p'.escapeshellarg($pw).' doclinc_visit_test -e '.escapeshellarg($q);$o=[];foreach(preg_split('/\r?\n/',trim((string)shell_exec($c))) as $l){$p=preg_split('/\s+/',trim($l));if(count($p)>1)$o[]=array_map('intval',$p);}return $o;}$ii=json_decode((string)shell_exec('docker inspect visit_clinical_workflow-db-1'),true);$pw='';foreach(($ii[0]['Config']['Env']??[]) as $e)if(strpos($e,'MARIADB_ROOT_PASSWORD=')===0)$pw=substr($e,strlen('MARIADB_ROOT_PASSWORD='));
    $g=h1d1p('row_lock_gate_worker.php','disposition '.$d1.' '.escapeshellarg($ready).' '.escapeshellarg($release),$gp);$gatePid=proc_get_status($g)['pid'];$dl=microtime(true)+10;while(!is_file($ready)&&microtime(true)<$dl)usleep(100000);$gi=json_decode(file_get_contents($ready),true);$gc=(int)$gi['connection_id'];$p=h1d1p('physical_start_worker.php',$r.' '.$a.' en_route '.escapeshellarg($pa),$pp);$physicalPid=proc_get_status($p)['pid'];$dl=microtime(true)+10;$pc=0;while(!is_file($pa)&&microtime(true)<$dl)usleep(100000);$pc=(int)json_decode(file_get_contents($pa),true)['connection_id'];$edge=false;while(microtime(true)<$dl){foreach(h1d1w($pw) as $e)if($e[0]===$pc&&$e[1]===$gc)$edge=true;if($edge)break;usleep(100000);}vcw_assert_true($edge,'physical waits gate');$v=h1d1p('ci3_revision_worker.php','A NOW '.$r.' '.$d.' 1 Dokter h1d1-rev-'.$r.' '.escapeshellarg($ra),$rp);$revisionPid=proc_get_status($v)['pid'];$dl=microtime(true)+10;while(!is_file($ra)&&microtime(true)<$dl)usleep(100000);$rc=(int)json_decode(file_get_contents($ra),true)['connection_id'];$graph=false;while(microtime(true)<$dl){$h1=$h2=false;foreach(h1d1w($pw) as $e){if($e[0]===$rc&&$e[1]===$pc)$h1=true;if($e[0]===$pc&&$e[1]===$gc)$h2=true;}if($h1&&$h2){$graph=true;break;}usleep(100000);}vcw_assert_true($graph,'start first graph');file_put_contents($release,'release');$po=stream_get_contents($pp[1]);fclose($pp[1]);fclose($pp[2]);proc_close($p);$ro=stream_get_contents($rp[1]);fclose($rp[1]);fclose($rp[2]);proc_close($v);fclose($gp[1]);fclose($gp[2]);proc_close($g);$pr=json_decode(trim($po),true);$rr=json_decode(trim($ro),true);$req=$db->where('request_id',$r)->get('requests')->row();$d2=$db->where('request_id',$r)->where('version_no',2)->count_all_results('visit_dispositions');vcw_assert_true(!empty($pr['ok']),'physical success');vcw_assert_same('DISPOSITION_LOCKED',$rr['result']['code']??null,'revision lock');vcw_assert_same('en_route',(string)$req->visit_status,'start state');vcw_assert_same(0,$d2,'no D2');echo "GATE_PID=".$gatePid." GATE_CONNECTION=".$gc." PHYSICAL_PID=".$physicalPid." PHYSICAL_CONNECTION=".$pc." REVISION_PID=".$revisionPid." REVISION_CONNECTION=".$rc."\\n";echo "START_WAITS_ON_DISPOSITION_GATE=YES\nREVISION_WAITS_ON_PHYSICAL=YES\nSTART_FIRST_REVISION_WAIT_GRAPH=PASS\nEN_ROUTE_FIRST_LOCKS_DISPOSITION=PASS\nSTART_FIRST_REQUEST_STATE=PASS\nSTART_FIRST_DISPOSITION_STATE=PASS\nSTART_FIRST_ASSIGNMENT_STATE=PASS\nH1D1_INDEPENDENT_CONNECTIONS=PASS\n";exit(0);
}
if ((int)$db->query("SELECT COUNT(*) c FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='nakes_facility_placements'")->row()->c===0) $db->query("CREATE TABLE nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(staff_id)) ENGINE=InnoDB");
$b=(int)$db->query('SELECT GREATEST(COALESCE(MAX(userId),0),COALESCE((SELECT MAX(request_id) FROM requests),0))+100 AS b FROM users')->row()->b; $f='H1C-'.$b; $r=$b; $d=$b+1; $a=$b+2; $cc=$b-1;
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$f,'H1c','aktif']);
foreach([[$d,'dokter'],[$a,'Perawat']] as $u){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$u[0],'H1c','h1c'.$u[0].'@invalid','h1c'.$u[0],'x','dokter','aktif',0,$f]);$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$u[0],$f,$u[0],'H1c',$u[1],'aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status) VALUES (?,?,?,?)',[$u[0],$f,'2026-01-01','active']);}
$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$cc,'CC','h1ccc'.$cc.'@invalid','h1ccc'.$cc,'x','dokter','aktif',0,$f]);
$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$r,$d,'synthetic','Accepted',$f,'H1c','not_started','visit',$d]);
$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$d,$d,$d,'aktif']);
$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,required_profession,created_by_user_id,idempotency_key) VALUES (?,?,?,?,?,?,?)',[$r,1,'visit','routine','Perawat',$d,'h1c-d1-'.$r]);
    $db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$a,$a,$cc,'aktif']);$d1id=(int)$db->where('request_id',$r)->where('version_no',1)->get('visit_dispositions')->row()->disposition_id;$db->where('request_id',$r)->update('requests',['visit_performer_user_id'=>$a]);
$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'vcw-h1c-'.$b; $ready=$tmp.'.ready';$release=$tmp.'.release';$revBarrier=$tmp.'.rev';@unlink($ready);@unlink($release);@unlink($revBarrier.'.release');
function h1c_start($script,$args,$out){$p=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/'.$script).' '.$args,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'process');return [$p,$pipes];}
$gate=h1c_start('row_lock_gate_worker.php','disposition '.$d1id.' '.escapeshellarg($ready).' '.escapeshellarg($release),$tmp);$gp=$gate[0];$gatePid=proc_get_status($gp)['pid'];$gpipe=$gate[1];$deadline=microtime(true)+10;while(!is_file($ready)&&microtime(true)<$deadline)usleep(100000);$ginfo=json_decode(file_get_contents($ready),true);vcw_assert_true(!empty($ginfo['lock_acquired']),'gate ready');
$rev=h1c_start('ci3_revision_worker.php','A '.escapeshellarg($revBarrier).' '.$r.' '.$d.' 1 Dokter h1c-rev-'.$r,$tmp);$rp=$rev[0];$revisionPid=proc_get_status($rp)['pid'];$rpipe=$rev[1];file_put_contents($revBarrier.'.release','go');
$inspect=json_decode((string)shell_exec('docker inspect visit_clinical_workflow-db-1'),true);$pw='';foreach(($inspect[0]['Config']['Env']??[]) as $e)if(strpos($e,'MARIADB_ROOT_PASSWORD=')===0)$pw=substr($e,strlen('MARIADB_ROOT_PASSWORD='));
function h1c_waits($pw){$sql="SELECT r.trx_mysql_thread_id waiting_thread,b.trx_mysql_thread_id blocking_thread FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id";$c='docker exec visit_clinical_workflow-db-1 mariadb -N -B -uroot -p'.escapeshellarg($pw).' doclinc_visit_test -e '.escapeshellarg($sql);$rows=[];foreach(preg_split('/\r?\n/',trim((string)shell_exec($c))) as $line){if(preg_match('/^(\d+)\s+(\d+)$/',$line,$m))$rows[]=[$m[1],$m[2]];}return $rows;}
$revConn=null;$physicalConn=null;$physical=null;$deadline=microtime(true)+10;while(microtime(true)<$deadline){$rows=h1c_waits($pw);if(count($rows)>0){$revConn=$rows[0][0];break;}usleep(100000);}vcw_assert_true($revConn!==null,'revision waits on gate');
$phys=h1c_start('physical_start_worker.php',$r.' '.$a.' en_route',$tmp);$pp=$phys[0];$physicalPid=proc_get_status($pp)['pid'];$ppipe=$phys[1];$deadline=microtime(true)+10;$graph=false;while(microtime(true)<$deadline){$rows=h1c_waits($pw);$hasGate=false;$hasRev=false;foreach($rows as $x){if((string)$x[1]===(string)$ginfo['connection_id'])$hasGate=true;if((string)$x[1]===(string)$revConn)$hasRev=true;}if($hasGate&&$hasRev){$graph=true;break;}usleep(100000);}vcw_assert_true($graph,'physical waits revision and revision waits gate');
file_put_contents($release,'release',LOCK_EX);$rout=stream_get_contents($rpipe[1]);$rerr=stream_get_contents($rpipe[2]);fclose($rpipe[1]);fclose($rpipe[2]);proc_close($rp);$pout=stream_get_contents($ppipe[1]);$perr=stream_get_contents($ppipe[2]);fclose($ppipe[1]);fclose($ppipe[2]);proc_close($pp);$gout=stream_get_contents($gpipe[1]);fclose($gpipe[1]);fclose($gpipe[2]);proc_close($gp);$rr=json_decode(trim($rout),true);$pr=json_decode(trim($pout),true);$d1state=$db->where('disposition_id',$d1id)->get('visit_dispositions')->row();$d2state=$db->where('request_id',$r)->where('version_no',2)->get('visit_dispositions')->row();$req=$db->where('request_id',$r)->get('requests')->row();$ast=$db->where('request_id',$r)->where('user_id',$a)->get('request_visit_performer_assignments')->row();vcw_assert_true(!empty($rr['result']['ok']),'revision success');vcw_assert_true(empty($pr['ok']),'stale physical denied');vcw_assert_same('not_started',(string)$req->visit_status,'no stale start');
echo "GATE_PID=".$gatePid." GATE_CONNECTION=".$ginfo['connection_id']." REVISION_PID=".$revisionPid." REVISION_CONNECTION=".$revConn." PHYSICAL_PID=".$physicalPid." PHYSICAL_CONNECTION=".$pr['connection_id']."\\n";echo "REVISION_WAITS_ON_GATE=YES\nPHYSICAL_WAITS_ON_REVISION=YES\nREVISION_FIRST_WAIT_GRAPH=PASS\nREVISION_COMMITTED_FIRST=PASS\nDISPOSITION_REVISION_FIRST_RECHECK=PASS\nSTALE_PHYSICAL_START_MUTATION=NO\nSTALE_PERFORMER_AUTHORITY_REMOVED=PASS\nH1C_INDEPENDENT_CONNECTIONS=PASS\nPHYSICAL_START_SEQUENTIAL_CONTROL=NOT_EXECUTED\n";
