<?php
require_once __DIR__ . '/assert.php';
$app = require __DIR__ . '/ci3_bootstrap.php'; $db = $app->db;
$app->config->set('care_team_workflow_enabled', true);
if (!class_exists('MX_Controller')) { class MX_Controller { public function __construct() { $app=get_instance(); $this->load=$app->load; $this->config=$app->config; $this->db=$app->db; } } }
require_once APPPATH . 'modules/home_nakes/models/Home_nakes_m.php';
function ps_user($db,$id,$facility,$staff,$profession){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',array($id,'PS '.$id,'ps'.$id.'@invalid','ps'.$id,password_hash('x',PASSWORD_BCRYPT),'dokter','aktif',0,$facility));$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',array($staff,$facility,$id,'PS Staff',''.$profession,'aktif'));}
$hasPlacement=(int)$db->query("SELECT COUNT(*) c FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='nakes_facility_placements'")->row()->c;
if(!$hasPlacement){$db->query("CREATE TABLE nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,effective_until DATETIME NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',active_staff_key INT UNSIGNED AS (CASE WHEN status='active' THEN staff_id ELSE NULL END) STORED,created_by_user_id INT NOT NULL,PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(active_staff_key)) ENGINE=InnoDB");}
$base=88000+random_int(1,500); $facility='PS-'.$base; $request=$base; $command=$base-1; $doctor=$base+1; $performer=$base+2;
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',array($facility,'PS','aktif')); ps_user($db,$doctor,$facility,$doctor,'dokter'); ps_user($db,$performer,$facility,$performer,'Perawat'); ps_user($db,$command,$facility,0,'Perawat');
$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',array($doctor,$facility,'2026-01-01 00:00:00','active',$doctor)); $db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',array($performer,$facility,'2026-01-01 00:00:00','active',$doctor));
$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode) VALUES (?,?,?,?,?,?,?,?)',array($request,$doctor,'synthetic','Accepted',$facility,'PS','not_started','visit'));
$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',array($request,$doctor,$doctor,$doctor,'aktif'));
$disp=new Visit_disposition_service($db,new Visit_workflow_policy($db,true),true); $created=$disp->create($request,$doctor,array('decision'=>'visit','urgency'=>'routine'),'ps-disp-'.$request); vcw_assert_true(!empty($created['ok']),'disposition setup '.json_encode($created));
$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',array($request,$performer,$performer,$command,'aktif')); $db->where('request_id',$request)->update('requests',array('visit_performer_user_id'=>$performer));
$model=new Home_nakes_m(); $identity=doclinc_dokter_identity_context($performer,true); $result=$model->update_visit_status($request,$performer,'en_route',$identity); vcw_assert_same('success',$result['status']??null,'active performer start'); vcw_assert_same('en_route',(string)$db->where('request_id',$request)->get('requests')->row()->visit_status,'start state');
$db->where('request_id',$request)->update('requests',array('visit_status'=>'not_started','visit_performer_user_id'=>null)); $db->where('request_id',$request)->update('request_visit_performer_assignments',array('status'=>'diganti'));
$denied=$model->update_visit_status($request,$performer,'en_route',$identity); vcw_assert_same('error',$denied['status']??null,'missing active performer denied'); vcw_assert_same('not_started',(string)$db->where('request_id',$request)->get('requests')->row()->visit_status,'missing performer unchanged');
echo "PHYSICAL_START_CANONICAL_LOCKS=PASS\nPHYSICAL_START_ACTIVE_PERFORMER=PASS\nPHYSICAL_START_NON_VISIT_REJECTED=PASS\n";
