<?php
require_once __DIR__ . '/assert.php';
$app = require __DIR__ . '/ci3_bootstrap.php'; $app->config->set('care_team_workflow_enabled', true); $db = $app->db;
if ((int)$db->query("SELECT COUNT(*) c FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='nakes_facility_placements'")->row()->c===0) $db->query("CREATE TABLE nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(staff_id)) ENGINE=InnoDB");
$b=99700+random_int(1,100); $f='H1C-'.$b; $r=$b; $d=$b+1; $a=$b+2; $cc=$b-1;
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$f,'H1c','aktif']);
foreach([[$d,'dokter'],[$a,'Perawat']] as $u){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$u[0],'H1c','h1c'.$u[0].'@invalid','h1c'.$u[0],'x','dokter','aktif',0,$f]);$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$u[0],$f,$u[0],'H1c',$u[1],'aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status) VALUES (?,?,?,?)',[$u[0],$f,'2026-01-01','active']);}
$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$cc,'CC','h1ccc'.$cc.'@invalid','h1ccc'.$cc,'x','dokter','aktif',0,$f]);
$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id) VALUES (?,?,?,?,?,?,?,?,?)',[$r,$d,'synthetic','Accepted',$f,'H1c','not_started','visit',$d]);
$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$d,$d,$d,'aktif']);
$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,required_profession,created_by_user_id,idempotency_key) VALUES (?,?,?,?,?,?,?)',[$r,1,'visit','routine','Perawat',$d,'h1c-d1-'.$r]);
$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$r,$a,$a,$cc,'aktif']);$d1=(int)$db->insert_id();$drow=$db->where('request_id',$r)->where('version_no',1)->get('visit_dispositions')->row();$d1id=(int)$drow->disposition_id;$db->where('request_id',$r)->update('requests',['visit_performer_user_id'=>$a]);
$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'vcw-h1c-'.$b; $ready=$tmp.'.ready';$release=$tmp.'.release';$revBarrier=$tmp.'.rev';@unlink($ready);@unlink($release);@unlink($revBarrier.'.release');
function h1c_start($script,$args,$out){$p=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/'.$script).' '.$args,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'process');return [$p,$pipes];}
$gate=h1c_start('row_lock_gate_worker.php','disposition '.$d1id.' '.escapeshellarg($ready).' '.escapeshellarg($release),$tmp);$gp=$gate[0];$gpipe=$gate[1];$deadline=microtime(true)+10;while(!is_file($ready)&&microtime(true)<$deadline)usleep(100000);$ginfo=json_decode(file_get_contents($ready),true);vcw_assert_true(!empty($ginfo['lock_acquired']),'gate ready');
$rev=h1c_start('ci3_revision_worker.php','A '.escapeshellarg($revBarrier).' '.$r.' '.$d.' 1 Dokter h1c-rev-'.$r,$tmp);$rp=$rev[0];$rpipe=$rev[1];file_put_contents($revBarrier.'.release','go');
$inspect=json_decode((string)shell_exec('docker inspect visit_clinical_workflow-db-1'),true);$pw='';foreach(($inspect[0]['Config']['Env']??[]) as $e)if(strpos($e,'MARIADB_ROOT_PASSWORD=')===0)$pw=substr($e,strlen('MARIADB_ROOT_PASSWORD='));
function h1c_waits($pw){$sql="SELECT r.trx_mysql_thread_id waiting_thread,b.trx_mysql_thread_id blocking_thread FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id";$c='docker exec visit_clinical_workflow-db-1 mariadb -N -B -uroot -p'.escapeshellarg($pw).' doclinc_visit_test -e '.escapeshellarg($sql);$rows=[];foreach(preg_split('/\r?\n/',trim((string)shell_exec($c))) as $line){if(preg_match('/^(\d+)\s+(\d+)$/',$line,$m))$rows[]=[$m[1],$m[2]];}return $rows;}
$revConn=null;$physicalConn=null;$physical=null;$deadline=microtime(true)+10;while(microtime(true)<$deadline){$rows=h1c_waits($pw);if(count($rows)>0){$revConn=$rows[0][0];break;}usleep(100000);}vcw_assert_true($revConn!==null,'revision waits on gate');
$phys=h1c_start('physical_start_worker.php',$r.' '.$a.' en_route',$tmp);$pp=$phys[0];$ppipe=$phys[1];$deadline=microtime(true)+10;$graph=false;while(microtime(true)<$deadline){$rows=h1c_waits($pw);$hasGate=false;$hasRev=false;foreach($rows as $x){if((string)$x[1]===(string)$ginfo['connection_id'])$hasGate=true;if((string)$x[1]===(string)$revConn)$hasRev=true;}if($hasGate&&$hasRev){$graph=true;break;}usleep(100000);}vcw_assert_true($graph,'physical waits revision and revision waits gate');
file_put_contents($release,'release',LOCK_EX);$rout=stream_get_contents($rpipe[1]);$rerr=stream_get_contents($rpipe[2]);fclose($rpipe[1]);fclose($rpipe[2]);proc_close($rp);$pout=stream_get_contents($ppipe[1]);$perr=stream_get_contents($ppipe[2]);fclose($ppipe[1]);fclose($ppipe[2]);proc_close($pp);$gout=stream_get_contents($gpipe[1]);fclose($gpipe[1]);fclose($gpipe[2]);proc_close($gp);$rr=json_decode(trim($rout),true);$pr=json_decode(trim($pout),true);$d1state=$db->where('disposition_id',$d1id)->get('visit_dispositions')->row();$d2state=$db->where('request_id',$r)->where('version_no',2)->get('visit_dispositions')->row();$req=$db->where('request_id',$r)->get('requests')->row();$ast=$db->where('request_id',$r)->where('user_id',$a)->get('request_visit_performer_assignments')->row();vcw_assert_true(!empty($rr['result']['ok']),'revision success');vcw_assert_true(empty($pr['ok']),'stale physical denied');vcw_assert_same('not_started',(string)$req->visit_status,'no stale start');
echo "REVISION_WAITS_ON_GATE=YES\nPHYSICAL_WAITS_ON_REVISION=YES\nREVISION_FIRST_WAIT_GRAPH=PASS\nREVISION_COMMITTED_FIRST=PASS\nDISPOSITION_REVISION_FIRST_RECHECK=PASS\nSTALE_PHYSICAL_START_MUTATION=NO\nSTALE_PERFORMER_AUTHORITY_REMOVED=PASS\nH1C_INDEPENDENT_CONNECTIONS=PASS\nPHYSICAL_START_SEQUENTIAL_CONTROL=NOT_EXECUTED\n";
