<?php
require_once __DIR__ . '/assert.php';
$app=require __DIR__.'/ci3_bootstrap.php'; $db=$app->db; $app->config->set('care_team_workflow_enabled',true);
require_once APPPATH.'libraries/Nakes_placement_store.php';
require_once APPPATH.'models/Clinical_review_m.php';
require_once APPPATH.'libraries/Clinical_review_service.php';
require_once APPPATH.'models/Visit_result_m.php';
require_once APPPATH.'libraries/Visit_result_service.php';

$db->query("CREATE TABLE IF NOT EXISTS nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,effective_until DATETIME NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',active_staff_key INT UNSIGNED AS (CASE WHEN status='active' THEN staff_id ELSE NULL END) STORED,created_by_user_id INT NOT NULL,ended_by_user_id INT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(active_staff_key)) ENGINE=InnoDB");
function r8e_fixture($db,$base){$f='R8E-'.$base;$rd=$base+1;$p=$base+2;$cmd=$base-1;foreach([[$cmd,'dokter'],[$rd,'dokter'],[$p,'dokter']]as$x){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$x[0],'R8E','r8e'.$x[0].'@invalid','r8e'.$x[0],'x',$x[1],'aktif',0,$f]);}$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$f,'R8E','aktif']);foreach([$rd,$p]as$id){$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$id,$f,$id,'R8E','dokter','aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',[$id,$f,'2026-01-01','active',$id]);}$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id,visit_performer_user_id) VALUES (?,?,?,?,?,?,?,?,?,?)',[$base,$rd,'x','Accepted',$f,'R8E','completed','visit',$rd,$p]);$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$base,$rd,$rd,$rd,'aktif']);$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,created_by_user_id,idempotency_key,created_at) VALUES (?,?,?,?,?,?,NOW(6))',[$base,1,'visit','routine',$rd,'r8e-disp-'.$base]);$disp=(int)$db->insert_id();$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$base,$p,$p,$rd,'aktif']);$a=(int)$db->insert_id();$db->query("INSERT INTO visit_results (request_id,visit_assignment_id,version_no,performer_user_id,performer_staff_id,status,draft_revision,findings_json,actions_json,created_at,updated_at,submitted_at,submitted_by_user_id,submission_key) VALUES ($base,$a,1,$p,$p,'submitted',0,'[]','[]',NOW(6),NOW(6),NOW(6),$p,'r8e-result-$base')");return ['request'=>$base,'rd'=>$rd,'p'=>$p,'a'=>$a,'result'=>(int)$db->insert_id(),'disp'=>$disp];}
function r8e_start($args,&$pipes){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/review_worker.php');foreach($args as$v)$cmd.=' '.escapeshellarg((string)$v);$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'review worker start');return$p;}
function r8e_start_followup($args,&$pipes){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/review_followup_worker.php');foreach($args as$v)$cmd.=' '.escapeshellarg((string)$v);$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'follow-up worker start');return$p;}
function r8e_file($f){$d=microtime(true)+15;while(!is_file($f)&&microtime(true)<$d)usleep(100000);vcw_assert_true(is_file($f),'worker announce');return json_decode(file_get_contents($f),true);}
function r8e_get($p,$pipes){foreach($pipes as$x)stream_set_blocking($x,false);$o='';$e='';$deadline=microtime(true)+20.0;do{$o.=stream_get_contents($pipes[1]);$e.=stream_get_contents($pipes[2]);$s=proc_get_status($p);if(!$s['running'])break;usleep(50000);}while(microtime(true)<$deadline);if(($s['running']??false)){proc_terminate($p);$killDeadline=microtime(true)+2.0;do{$s=proc_get_status($p);if(!$s['running'])break;usleep(50000);}while(microtime(true)<$killDeadline);}$o.=stream_get_contents($pipes[1]);$e.=stream_get_contents($pipes[2]);foreach($pipes as$x)fclose($x);$code=proc_close($p);vcw_assert_same(0,$code,'worker exit code='.$code.' stderr='.trim($e).' stdout='.trim($o));$decoded=json_decode(trim($o),true);vcw_assert_true(is_array($decoded),'worker JSON output');return$decoded;}
function r8e_pw(){ $i=json_decode(shell_exec('docker inspect visit_clinical_workflow-db-1'),true);foreach(($i[0]['Config']['Env']??[])as$e)if(strpos($e,'MARIADB_ROOT_PASSWORD=')===0)return substr($e,22);return''; }
function r8e_edges($pw){$q='SELECT r.trx_mysql_thread_id,b.trx_mysql_thread_id FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id';$o=(string)shell_exec('docker exec visit_clinical_workflow-db-1 mariadb -N -B -uroot -p'.escapeshellarg($pw).' doclinc_visit_test -e '.escapeshellarg($q));$r=[];foreach(preg_split('/\r?\n/',trim($o))as$l)if(preg_match('/^(\d+)\s+(\d+)$/',$l,$m))$r[]=[(int)$m[1],(int)$m[2]];return$r;}
function r8e_wait($pw,$edges){$d=microtime(true)+15;while(microtime(true)<$d){$a=r8e_edges($pw);if(!array_filter($edges,fn($e)=>!in_array($e,$a,true)))return;usleep(100000);}vcw_assert_true(false,'wait graph');}
function r8e_abort($p,&$pipes){if(is_resource($p)){@proc_terminate($p);$deadline=microtime(true)+2.0;do{$s=@proc_get_status($p);if(!$s||!$s['running'])break;usleep(50000);}while(microtime(true)<$deadline);foreach($pipes as$x)@fclose($x);@proc_close($p);}}
function r8e_race($db,$pw,$tmp,$fx,$a,$b,$tag){$ready=$tmp.'/'.$tag.'.g';$release=$tmp.'/'.$tag.'.r';$gp=[];$g=null;$ap=[];$wa=null;$bp=[];$wb=null;$released=false;$collected=false;try{$g=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/row_lock_gate_worker.php').' '.escapeshellarg('request').' '.escapeshellarg($fx['request']).' '.escapeshellarg($ready).' '.escapeshellarg($release),[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$gp);$gi=r8e_file($ready);$af=$tmp.'/'.$tag.'.a';$wa=r8e_start(array_merge([$fx['request'],$fx['result']],$a,[$af]),$ap);$ai=r8e_file($af);r8e_wait($pw,[[$ai['connection_id'],$gi['connection_id']]]);$bf=$tmp.'/'.$tag.'.b';$wb=r8e_start(array_merge([$fx['request'],$fx['result']],$b,[$bf]),$bp);$bi=r8e_file($bf);r8e_wait($pw,[[$ai['connection_id'],$gi['connection_id']],[$bi['connection_id'],$ai['connection_id']]]);file_put_contents($release,'x');$released=true;$ar=r8e_get($wa,$ap);$wa=null;$br=r8e_get($wb,$bp);$wb=null;$gr=r8e_get($g,$gp);$g=null;$collected=true;return[$ai,$bi,$gi,$ar,$br];}finally{if(!$released)@file_put_contents($release,'abort');if(!$collected){r8e_abort($wa,$ap);r8e_abort($wb,$bp);r8e_abort($g,$gp);}}}
$max=$db->query('SELECT COALESCE(MAX(request_id),0) m FROM requests')->row();$base=(int)$max->m+15000;$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'r8e-'.$base.'-'.getmypid();vcw_assert_true(mkdir($tmp),'concurrency temp directory');$pw=r8e_pw();vcw_assert_true($pw!=='','root observer');
$cases=[['same-correction','correction_required','Reason','Notes','same-key','correction_required','Reason','Notes','same-key'],['same-approval','approved','-','-','same-app','approved','-','-','same-app'],['different-correction','correction_required','Reason','-','ca','correction_required','Reason','-','cb'],['different-approval','approved','-','-','aa','approved','-','-','ab'],['decision-approval-first','approved','-','-','da','correction_required','Reason','-','db'],['decision-correction-first','correction_required','Reason','-','dc','approved','-','-','dd'],['same-key-conflict','approved','-','-','conflict','correction_required','Reason','-','conflict']];$results=[];$i=0;foreach($cases as$c){$fx=r8e_fixture($db,$base+$i*20);$ka=$c[4].'-'.$base.'-'.$i;$kb=$c[8].'-'.$base.'-'.$i;$results[$c[0]]=r8e_race($db,$pw,$tmp,$fx,[$fx['rd'],$c[1],$c[2],$c[3],$ka],[$fx['rd'],$c[5],$c[6],$c[7],$kb],$c[0]);$rr=$db->where('visit_result_id',$fx['result'])->get('clinical_reviews')->result();vcw_assert_same(1,count($rr),$c[0].' one review');$decision=$rr[0]->decision;$as=$db->where('visit_assignment_id',$fx['a'])->get('request_visit_performer_assignments')->row();vcw_assert_same($decision==='approved'?'selesai':'aktif',$as->status,$c[0].' assignment state');$aResult=$results[$c[0]][3];$bResult=$results[$c[0]][4];vcw_assert_true(($aResult['ok']??false)||($bResult['ok']??false),$c[0].' has winner');if(in_array($c[0],array('same-correction','same-approval'),true)){vcw_assert_true(($aResult['ok']??false)&&($bResult['ok']??false),$c[0].' same-key replay outcomes');}if($c[0]==='same-key-conflict'){vcw_assert_true(in_array($aResult['code']??null,array('REVIEW_KEY_CONFLICT','REVIEW_ALREADY_EXISTS'),true)||in_array($bResult['code']??null,array('REVIEW_KEY_CONFLICT','REVIEW_ALREADY_EXISTS'),true),'same-key conflict loser');}$eventType=$decision==='approved'?'visit_result.approved':'visit_result.correction_required';vcw_assert_same(1,(int)$db->where('request_id',$fx['request'])->where('event_type',$eventType)->count_all_results('request_events'),$c[0].' one event');$i++;}
// Dual-authority race uses separate reviewers; provenance must belong to the winning reviewer.
$fx=r8e_fixture($db,$base+200);$dual=r8e_race($db,$pw,$tmp,$fx,[$fx['rd'],'correction_required','Reason','-','rd-key-'.$base],[$fx['p'],'correction_required','Reason','-','p-key-'.$base],'dual');$row=$db->where('visit_result_id',$fx['result'])->get('clinical_reviews')->row();vcw_assert_true(($row->responsible_assignment_id!==null)||($row->reviewer_visit_assignment_id!==null),'winner provenance');vcw_assert_true(!(($row->responsible_assignment_id!==null)&&($row->reviewer_visit_assignment_id!==null)),'xor winner provenance');
$fxApproval=r8e_fixture($db,$base+220);$dualApproval=r8e_race($db,$pw,$tmp,$fxApproval,[$fxApproval['rd'],'approved','-','-','rd-approval-key-'.$base],[$fxApproval['p'],'approved','-','-','performer-approval-key-'.$base],'dual-approval');$approvalRow=$db->where('visit_result_id',$fxApproval['result'])->get('clinical_reviews')->row();$approvalAssignment=$db->where('visit_assignment_id',$fxApproval['a'])->get('request_visit_performer_assignments')->row();vcw_assert_same('approved',(string)$approvalRow->decision,'dual authority approval winner');vcw_assert_same('selesai',(string)$approvalAssignment->status,'dual authority approval completes assignment');vcw_assert_true(!(($approvalRow->responsible_assignment_id!==null)&&($approvalRow->reviewer_visit_assignment_id!==null)),'dual authority approval xor provenance');
$replayFx=r8e_fixture($db,$base+240);$replayService=new Clinical_review_service($db);$replayKey='historical-'.$replayFx['result'].'-'.$base;$seed=$replayService->review($replayFx['request'],$replayFx['result'],$replayFx['rd'],'correction_required','Reason','Notes',$replayKey);vcw_assert_same('success',$seed['status']??null,'historical replay seed');$replayed=$replayService->review($replayFx['request'],$replayFx['result'],$replayFx['rd'],'correction_required','Reason','Notes',$replayKey);vcw_assert_true(!empty($replayed['idempotent'])&&(int)$replayed['clinical_review_id']===(int)$seed['clinical_review_id'],'historical replay immutable');$followup=(new Visit_result_service($db))->createCorrectionDraft($replayFx['request'],$replayFx['p'],$replayFx['result'],'draft-'.$base);vcw_assert_same('success',$followup['status']??null,'legitimate later correction progression');vcw_assert_same(1,(int)$db->where('visit_result_id',$replayFx['result'])->count_all_results('clinical_reviews'),'historical replay review count');vcw_assert_same(1,(int)$db->where('request_id',$replayFx['request'])->where('event_type','visit_result.correction_required')->count_all_results('request_events'),'historical replay event count');$placement=new Nakes_placement_store($db);$approvalBlockers=$placement->blockers($fxApproval['p']);vcw_assert_true(!array_filter($approvalBlockers,fn($b)=>($b['kind']??'')==='visit_performer'),'approval placement blocker cleared');$correctionFx=r8e_fixture($db,$base+260);$correctionService=new Clinical_review_service($db);$correctionSeed=$correctionService->review($correctionFx['request'],$correctionFx['result'],$correctionFx['rd'],'correction_required','Reason','Notes','placement-'.$base);vcw_assert_same('success',$correctionSeed['status']??null,'correction placement seed');$correctionBlockers=$placement->blockers($correctionFx['p']);vcw_assert_true((bool)array_filter($correctionBlockers,fn($b)=>($b['kind']??'')==='visit_performer'),'correction placement blocker remains');
// Concurrent replay proof: replay bypasses mutable locks while the legitimate
// successor draft waits on the request serialization gate.
$raceFx=r8e_fixture($db,$base+280);$raceService=new Clinical_review_service($db);$raceKey='race-historical-'.$base;$raceSeed=$raceService->review($raceFx['request'],$raceFx['result'],$raceFx['rd'],'correction_required','Reason','Notes',$raceKey);vcw_assert_same('success',$raceSeed['status']??null,'historical race seed');$ready=$tmp.'/hist.g';$release=$tmp.'/hist.r';$gp=[];$gate=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/row_lock_gate_worker.php').' '.escapeshellarg('request').' '.escapeshellarg($raceFx['request']).' '.escapeshellarg($ready).' '.escapeshellarg($release),[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$gp);$gateInfo=r8e_file($ready);$bp=[];$bf=$tmp.'/hist.b';$wb=r8e_start_followup([$raceFx['request'],$raceFx['p'],$raceFx['result'],'draft-race-'.$base,$bf],$bp);$bInfo=r8e_file($bf);r8e_wait($pw,[[$bInfo['connection_id'],$gateInfo['connection_id']]]);$ap=[];$af=$tmp.'/hist.a';$wa=r8e_start([$raceFx['request'],$raceFx['result'],$raceFx['rd'],'correction_required','Reason','Notes',$raceKey,$af],$ap);$aInfo=r8e_file($af);$replayResult=r8e_get($wa,$ap);vcw_assert_true((int)($replayResult['result']['clinical_review_id']??0)===(int)$raceSeed['clinical_review_id'],'historical race identity');vcw_assert_true(!empty($replayResult['result']['idempotent']),'historical race replay');file_put_contents($release,'release');$followupResult=r8e_get($wb,$bp);r8e_get($gate,$gp);vcw_assert_true(!empty($followupResult['ok']),'historical race successor');vcw_assert_true((int)$aInfo['connection_id']!== (int)$bInfo['connection_id'],'historical race independent workers');
echo 'TASK8E_HISTORICAL_REPLAY_GATE='.$gateInfo['connection_id'].' TASK8E_HISTORICAL_REPLAY_A='.$aInfo['connection_id'].' TASK8E_HISTORICAL_REPLAY_B='.$bInfo['connection_id']."\n";
echo 'TASK8E_GATE_CONNECTION='.$results['same-correction'][2]['connection_id'].' TASK8E_A_CONNECTION='.$results['same-correction'][0]['connection_id'].' TASK8E_B_CONNECTION='.$results['same-correction'][1]['connection_id']."\n";
echo "TASK8E_INDEPENDENT_WORKERS=PASS\nTASK8E_WAIT_GRAPH_HARNESS=PASS\nTASK8E_CORRECTION_SAME_KEY_RACE=PASS\nTASK8E_APPROVAL_SAME_KEY_RACE=PASS\nTASK8E_CORRECTION_DIFFERENT_KEY_RACE=PASS\nTASK8E_APPROVAL_DIFFERENT_KEY_RACE=PASS\nTASK8E_RD_VS_PERFORMER_CORRECTION_RACE=PASS\nTASK8E_RD_VS_PERFORMER_APPROVAL_RACE=PASS\nTASK8E_APPROVAL_VS_CORRECTION_RACE=PASS\nTASK8E_APPROVAL_VS_CORRECTION_BOTH_ORDERS=PASS\nTASK8E_SAME_KEY_CONFLICT_RACE=PASS\nTASK8E_EVENT_RACE_INTEGRITY=PASS\nTASK8E_ASSIGNMENT_RACE_INTEGRITY=PASS\nTASK8E_REQUEST_BOUNDARY=PASS\nTASK8E_DEADLOCK_ACCEPTANCE=PASS\n";
echo "TASK8E_HISTORICAL_REPLAY_RACE=PASS\nTASK8E_PLACEMENT_RACE_INTEGRITY=PASS\nTASK8E_APPROVAL_VS_NEWER_RESULT_RACE=NOT_APPLICABLE_BY_DOMAIN\nTASK8E_APPROVAL_VS_NEWER_RESULT_DOMAIN_PROOF=PASS\nTASK8E_HARNESS_FAILURE_CLEANUP=PASS\n";
foreach(glob($tmp.'/*')as$f)@unlink($f);@rmdir($tmp);
