<?php
require_once __DIR__ . '/assert.php';
$app=require __DIR__.'/ci3_bootstrap.php';$db=$app->db;$app->config->set('care_team_workflow_enabled',true);require_once APPPATH.'libraries/Clinical_review_service.php';
$max=(int)$db->query('SELECT COALESCE(MAX(request_id),0)m FROM requests')->row()->m;$umax=(int)$db->query('SELECT COALESCE(MAX(userId),0)m FROM users')->row()->m;$smax=(int)$db->query('SELECT COALESCE(MAX(staff_id),0)m FROM puskesmas_staff')->row()->m;$base=max($max,$umax,$smax)+30000+random_int(1,1000000);$facility='R8X-'.$base;
foreach(array($base+1,$base+2,$base+101,$base+102)as$id)$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',array($id,'R8X','r8x'.$id.'@invalid','r8x'.$id,'x','dokter','aktif',0,$facility));
$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',array($base,'R8X CC','r8xcc'.$base.'@invalid','r8xcc'.$base,'x','dokter','aktif',0,$facility));
$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',array($facility,'R8X','aktif'));
$fx=array();foreach(array(array($base+1,$base+2),array($base+101,$base+102))as$n=>$pair){$req=$base+$n*100;$rd=$pair[0];$p=$pair[1];$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',array($p,$facility,$p,'R8X','dokter','aktif'));$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',array($rd,$facility,$rd,'R8X','dokter','aktif'));foreach(array($p,$rd)as$s)$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',array($s,$facility,'2026-01-01','active',$s));$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id,visit_performer_user_id) VALUES (?,?,?,?,?,?,?,?,?,?)',array($req,$rd,'x','Accepted',$facility,'R8X','completed','visit',$rd,$p));$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',array($req,$rd,$rd,$rd,'aktif'));$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,created_by_user_id,idempotency_key,created_at) VALUES (?,?,?,?,?,?,NOW(6))',array($req,1,'visit','routine',$rd,'xdisp-'.$req));$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',array($req,$p,$p,$rd,'aktif'));$a=(int)$db->insert_id();$db->query("INSERT INTO visit_results (request_id,visit_assignment_id,version_no,performer_user_id,performer_staff_id,status,draft_revision,findings_json,actions_json,created_at,updated_at,submitted_at,submitted_by_user_id,submission_key) VALUES ($req,$a,1,$p,$p,'submitted',0,'[]','[]',NOW(6),NOW(6),NOW(6),$p,'xres-$req')");$fx[]=array('request'=>$req,'result'=>(int)$db->insert_id(),'reviewer'=>$rd);}
$runId='r8x-'.getmypid().'-'.bin2hex(random_bytes(4));$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.$runId;mkdir($tmp);$startGate=$tmp.'/start';$procs=array();register_shutdown_function(function()use(&$procs,$tmp,$startGate){@file_put_contents($startGate,'abort');foreach($procs as$entry){$p=$entry[0];if(is_resource($p)){@proc_terminate($p);$deadline=microtime(true)+2.0;do{$s=@proc_get_status($p);if(!$s||!$s['running'])break;usleep(50000);}while(microtime(true)<$deadline);}foreach($entry[1]as$pipe){try{if(is_resource($pipe))fclose($pipe);}catch(Throwable $ignored){}}if(is_resource($p)){try{proc_close($p);}catch(Throwable $ignored){}}}foreach(glob($tmp.'/*')as$f)@unlink($f);@rmdir($tmp);});foreach($fx as$i=>$f){$announce=$tmp.'/'.$i;$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/review_worker.php').' '.escapeshellarg($f['request']).' '.escapeshellarg($f['result']).' '.escapeshellarg($f['reviewer']).' correction_required Reason Notes '.escapeshellarg('global-key-'.$base).' '.escapeshellarg($announce).' '.escapeshellarg($startGate);$pipes=array();$procs[]=array(proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes),$pipes);}
$deadline=microtime(true)+10.0;while((!is_file($tmp.'/0')||!is_file($tmp.'/1'))&&microtime(true)<$deadline){usleep(20000);}vcw_assert_true(is_file($tmp.'/0')&&is_file($tmp.'/1'),'cross request workers ready');file_put_contents($startGate,'start');
$out=array();foreach($procs as$entry){$o=stream_get_contents($entry[1][1]);$e=stream_get_contents($entry[1][2]);foreach($entry[1]as$x)fclose($x);$code=proc_close($entry[0]);vcw_assert_same(0,$code,'cross request worker '.trim($e));$out[]=json_decode(trim($o),true);}
$rows=$db->where('idempotency_key','global-key-'.$base)->get('clinical_reviews')->result();vcw_assert_same(1,count($rows),'global key owner');$codes=array($out[0]['code']??null,$out[1]['code']??null);vcw_assert_true(in_array('REVIEW_KEY_CONFLICT',$codes,true),'cross request conflict '.json_encode($out));$loser=$out[0]['ok']?$fx[1]:$fx[0];$sequential=(new Clinical_review_service($db))->review($loser['request'],$loser['result'],$loser['reviewer'],'correction_required','Reason','Notes','global-key-'.$base);vcw_assert_same('REVIEW_KEY_CONFLICT',$sequential['safe_error_code']??null,'sequential cross request conflict');echo 'TASK8E_CROSS_REQUEST_SAME_KEY_RACE=PASS\nTASK8E_CROSS_REQUEST_KEY_CONFLICT_DETERMINISTIC=PASS\nTASK8C_CROSS_REQUEST_KEY_CONFLICT_REGRESSION=PASS\n';foreach(glob($tmp.'/*')as$f)@unlink($f);@rmdir($tmp);
