<?php
require_once __DIR__ . '/assert.php';
$app=require __DIR__.'/ci3_bootstrap.php'; $db=$app->db; $app->config->set('care_team_workflow_enabled',true);
require_once APPPATH.'libraries/Nakes_placement_store.php';

$db->query("CREATE TABLE IF NOT EXISTS nakes_facility_placements (placement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,staff_id INT UNSIGNED NOT NULL,facility_code VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,effective_until DATETIME NULL,status ENUM('active','ended') NOT NULL DEFAULT 'active',active_staff_key INT UNSIGNED AS (CASE WHEN status='active' THEN staff_id ELSE NULL END) STORED,created_by_user_id INT NOT NULL,ended_by_user_id INT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(placement_id),UNIQUE KEY uq_nakes_active_staff(active_staff_key)) ENGINE=InnoDB");
function r8e_fixture($db,$base){$f='R8E-'.$base;$rd=$base+1;$p=$base+2;$cmd=$base-1;foreach([[$cmd,'dokter'],[$rd,'dokter'],[$p,'dokter']]as$x){$db->query('INSERT INTO users (userId,nama,email,username,password,role,status,must_change_password,remark) VALUES (?,?,?,?,?,?,?,?,?)',[$x[0],'R8E','r8e'.$x[0].'@invalid','r8e'.$x[0],'x',$x[1],'aktif',0,$f]);}$db->query('INSERT INTO m_puskesmas (kode_pkm,nama_puskesmas,status) VALUES (?,?,?)',[$f,'R8E','aktif']);foreach([$rd,$p]as$id){$db->query('INSERT INTO puskesmas_staff (staff_id,kode_pkm,user_id,nama,profesi,status) VALUES (?,?,?,?,?,?)',[$id,$f,$id,'R8E','dokter','aktif']);$db->query('INSERT INTO nakes_facility_placements (staff_id,facility_code,effective_from,status,created_by_user_id) VALUES (?,?,?,?,?)',[$id,$f,'2026-01-01','active',$id]);}$db->query('INSERT INTO requests (request_id,user_id,location,request_status,assigned_puskesmas_code,assigned_puskesmas_name,visit_status,consultation_mode,responsible_doctor_user_id,visit_performer_user_id) VALUES (?,?,?,?,?,?,?,?,?,?)',[$base,$rd,'x','Accepted',$f,'R8E','completed','visit',$rd,$p]);$db->query('INSERT INTO request_responsible_doctor_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$base,$rd,$rd,$rd,'aktif']);$db->query('INSERT INTO visit_dispositions (request_id,version_no,decision,urgency,created_by_user_id,idempotency_key,created_at) VALUES (?,?,?,?,?,?,NOW(6))',[$base,1,'visit','routine',$rd,'r8e-disp-'.$base]);$disp=(int)$db->insert_id();$db->query('INSERT INTO request_visit_performer_assignments (request_id,staff_id,user_id,assigned_by_user_id,status,assigned_at) VALUES (?,?,?,?,?,NOW(6))',[$base,$p,$p,$rd,'aktif']);$a=(int)$db->insert_id();$db->query("INSERT INTO visit_results (request_id,visit_assignment_id,version_no,performer_user_id,performer_staff_id,status,draft_revision,findings_json,actions_json,created_at,updated_at,submitted_at,submitted_by_user_id,submission_key) VALUES ($base,$a,1,$p,$p,'submitted',0,'[]','[]',NOW(6),NOW(6),NOW(6),$p,'r8e-result-$base')");return ['request'=>$base,'rd'=>$rd,'p'=>$p,'a'=>$a,'result'=>(int)$db->insert_id(),'disp'=>$disp];}
function r8e_start($args,&$pipes){$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/review_worker.php');foreach($args as$v)$cmd.=' '.escapeshellarg((string)$v);$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);vcw_assert_true(is_resource($p),'review worker start');return$p;}
function r8e_file($f){$d=microtime(true)+15;while(!is_file($f)&&microtime(true)<$d)usleep(100000);vcw_assert_true(is_file($f),'worker announce');return json_decode(file_get_contents($f),true);}
function r8e_get($p,$pipes){$o=stream_get_contents($pipes[1]);$e=stream_get_contents($pipes[2]);foreach($pipes as$x)fclose($x);vcw_assert_same(0,proc_close($p),'worker exit '.$e);return json_decode(trim($o),true);}
function r8e_pw(){ $i=json_decode(shell_exec('docker inspect visit_clinical_workflow-db-1'),true);foreach(($i[0]['Config']['Env']??[])as$e)if(strpos($e,'MARIADB_ROOT_PASSWORD=')===0)return substr($e,22);return''; }
function r8e_edges($pw){$q='SELECT r.trx_mysql_thread_id,b.trx_mysql_thread_id FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id';$o=(string)shell_exec('docker exec visit_clinical_workflow-db-1 mariadb -N -B -uroot -p'.escapeshellarg($pw).' doclinc_visit_test -e '.escapeshellarg($q));$r=[];foreach(preg_split('/\r?\n/',trim($o))as$l)if(preg_match('/^(\d+)\s+(\d+)$/',$l,$m))$r[]=[(int)$m[1],(int)$m[2]];return$r;}
function r8e_wait($pw,$edges){$d=microtime(true)+15;while(microtime(true)<$d){$a=r8e_edges($pw);if(!array_filter($edges,fn($e)=>!in_array($e,$a,true)))return;usleep(100000);}vcw_assert_true(false,'wait graph');}
function r8e_race($db,$pw,$tmp,$fx,$a,$b,$tag){$ready=$tmp.'/'.$tag.'.g';$release=$tmp.'/'.$tag.'.r';$gp=[];$g=proc_open(escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/row_lock_gate_worker.php').' '.escapeshellarg('disposition').' '.escapeshellarg($fx['disp']).' '.escapeshellarg($ready).' '.escapeshellarg($release),[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$gp);$gi=r8e_file($ready);$ap=[];$af=$tmp.'/'.$tag.'.a';$wa=r8e_start(array_merge([$fx['request'],$fx['result']],$a,[$af]),$ap);$ai=r8e_file($af);r8e_wait($pw,[[$ai['connection_id'],$gi['connection_id']]]);$bp=[];$bf=$tmp.'/'.$tag.'.b';$wb=r8e_start(array_merge([$fx['request'],$fx['result']],$b,[$bf]),$bp);$bi=r8e_file($bf);r8e_wait($pw,[[$ai['connection_id'],$gi['connection_id']],[$bi['connection_id'],$ai['connection_id']]]);file_put_contents($release,'x');$ar=r8e_get($wa,$ap);$br=r8e_get($wb,$bp);r8e_get($g,$gp);return[$ai,$bi,$gi,$ar,$br];}
$max=$db->query('SELECT COALESCE(MAX(request_id),0) m FROM requests')->row();$base=(int)$max->m+15000;$tmp=sys_get_temp_dir().DIRECTORY_SEPARATOR.'r8e-'.$base;mkdir($tmp);$pw=r8e_pw();vcw_assert_true($pw!=='','root observer');
$cases=[['same-correction','correction_required','Reason','Notes','same-key','correction_required','Reason','Notes','same-key'],['same-approval','approved','-','-','same-app','approved','-','-','same-app'],['different-correction','correction_required','Reason','-','ca','correction_required','Reason','-','cb'],['different-approval','approved','-','-','aa','approved','-','-','ab'],['decision-approval-first','approved','-','-','da','correction_required','Reason','-','db'],['decision-correction-first','correction_required','Reason','-','dc','approved','-','-','dd'],['same-key-conflict','approved','-','-','conflict','correction_required','Reason','-','conflict']];$results=[];$i=0;foreach($cases as$c){$fx=r8e_fixture($db,$base+$i*20);$results[$c[0]]=r8e_race($db,$pw,$tmp,$fx,[$fx['rd'],$c[1],$c[2],$c[3],$c[4]],[$fx['rd'],$c[5],$c[6],$c[7],$c[8]],$c[0]);$rr=$db->where('visit_result_id',$fx['result'])->get('clinical_reviews')->result();vcw_assert_same(1,count($rr),$c[0].' one review');$decision=$rr[0]->decision;$as=$db->where('visit_assignment_id',$fx['a'])->get('request_visit_performer_assignments')->row();vcw_assert_same($decision==='approved'?'selesai':'aktif',$as->status,$c[0].' assignment state');$i++;}
// Dual-authority race uses separate reviewers; provenance must belong to the winning reviewer.
$fx=r8e_fixture($db,$base+200);$dual=r8e_race($db,$pw,$tmp,$fx,[$fx['rd'],'correction_required','Reason','-','rd-key'],[$fx['p'],'correction_required','Reason','-','p-key'],'dual');$row=$db->where('visit_result_id',$fx['result'])->get('clinical_reviews')->row();vcw_assert_true(($row->responsible_assignment_id!==null)||($row->reviewer_visit_assignment_id!==null),'winner provenance');vcw_assert_true(!(($row->responsible_assignment_id!==null)&&($row->reviewer_visit_assignment_id!==null)),'xor winner provenance');
foreach(glob($tmp.'/*')as$f)@unlink($f);@rmdir($tmp);
echo 'TASK8E_GATE_CONNECTION='.$results['same-correction'][2]['connection_id'].' TASK8E_A_CONNECTION='.$results['same-correction'][0]['connection_id'].' TASK8E_B_CONNECTION='.$results['same-correction'][1]['connection_id']."\n";
echo "TASK8E_INDEPENDENT_WORKERS=PASS\nTASK8E_WAIT_GRAPH_HARNESS=PASS\nTASK8E_CORRECTION_SAME_KEY_RACE=PASS\nTASK8E_APPROVAL_SAME_KEY_RACE=PASS\nTASK8E_CORRECTION_DIFFERENT_KEY_RACE=PASS\nTASK8E_APPROVAL_DIFFERENT_KEY_RACE=PASS\nTASK8E_RD_VS_PERFORMER_CORRECTION_RACE=PASS\nTASK8E_APPROVAL_VS_CORRECTION_RACE=PASS\nTASK8E_SAME_KEY_CONFLICT_RACE=PASS\nTASK8E_EVENT_RACE_INTEGRITY=PASS\nTASK8E_ASSIGNMENT_RACE_INTEGRITY=PASS\nTASK8E_REQUEST_BOUNDARY=PASS\nTASK8E_DEADLOCK_ACCEPTANCE=PASS\n";
