<?php
defined('BASEPATH') or exit('No direct script access allowed');
require_once APPPATH.'models/Clinical_amendment_m.php'; require_once APPPATH.'helpers/request_event_helper.php';
class Clinical_amendment_service {
 private $db; private $model; private $allowed=array('diagnosis','treatment','recommendations','anamnesis');
 public function __construct($db=null,$model=null){$this->db=$db?:get_instance()->db;$this->model=$model?:new Clinical_amendment_m($this->db);}
 public function effectiveValues($recordId){$record=$this->db->where('record_id',(int)$recordId)->get('medicalrecords')->row();if(!$record)return null;$values=[];foreach($this->allowed as $f){if($this->db->field_exists($f,'medicalrecords'))$values[$f]=(string)($record->$f??'');}$q=$this->db->query('SELECT i.field_key,i.corrected_value FROM clinical_amendment_items i JOIN clinical_amendments a ON a.amendment_id=i.amendment_id WHERE a.record_id=? ORDER BY a.sequence_no ASC,i.item_order ASC',[(int)$recordId]);foreach($q->result() as $i)$values[$i->field_key]=(string)$i->corrected_value;return $values;}
 public function amend($requestId,$recordId,$userId,$reason,array $items,$key){$requestId=(int)$requestId;$recordId=(int)$recordId;$userId=(int)$userId;$reason=trim((string)$reason);$key=trim((string)$key);if($requestId<1||$recordId<1||$userId<1||$reason===''||$key===''||strlen($key)>191||empty($items))return $this->fail('INVALID_AMENDMENT_INPUT');if(!$this->db->trans_begin())return $this->fail('WRITE_FAILED');
  try{$old=$this->model->byKey($key);if($old){if((int)$old->record_id!==$recordId||(int)$old->request_id!==$requestId||(int)$old->created_by_user_id!==$userId||trim((string)$old->reason)!==$reason||!$this->payloadMatches((int)$old->amendment_id,$items))return $this->rollback('AMENDMENT_KEY_CONFLICT');$this->db->trans_commit();return ['status'=>'success','amendment_id'=>(int)$old->amendment_id,'idempotent'=>true];}
   $record=$this->db->query('SELECT * FROM medicalrecords WHERE record_id=? AND request_id=? LIMIT 1 FOR UPDATE',[$recordId,$requestId])->row();if(!$record)return $this->rollback('CLINICAL_RECORD_NOT_FOUND');$serialized=$this->model->byKeyForUpdate($key);if($serialized){if((int)$serialized->record_id!==$recordId||(int)$serialized->request_id!==$requestId||(int)$serialized->created_by_user_id!==$userId||trim((string)$serialized->reason)!==$reason||!$this->payloadMatches((int)$serialized->amendment_id,$items))return $this->rollback('AMENDMENT_KEY_CONFLICT');$this->db->trans_commit();return ['status'=>'success','amendment_id'=>(int)$serialized->amendment_id,'idempotent'=>true];}if($record->clinical_finalized_at===null)return $this->rollback('CLINICAL_RECORD_NOT_FINALIZED');if((int)$record->clinical_finalized_by_user_id!==$userId)return $this->rollback('ACCESS_DENIED');
   $normalized=[];$seen=[];$current=[];foreach($this->allowed as $f){if($this->db->field_exists($f,'medicalrecords'))$current[$f]=(string)($record->$f??'');}
   $latest=$this->model->latestForUpdate($recordId);if($latest){$q=$this->db->query('SELECT i.field_key,i.corrected_value FROM clinical_amendment_items i JOIN clinical_amendments a ON a.amendment_id=i.amendment_id WHERE a.record_id=? ORDER BY a.sequence_no ASC,i.item_order ASC FOR UPDATE',[$recordId]);foreach($q->result() as $i)$current[$i->field_key]=(string)$i->corrected_value;}
   foreach($items as $item){$field=is_array($item)?trim((string)($item['field_key']??'')):'';if($field===''||!in_array($field,$this->allowed,true)||isset($seen[$field])||!array_key_exists($field,$current))return $this->rollback('INVALID_AMENDMENT_FIELD');$seen[$field]=true;$value=is_array($item)?(string)($item['corrected_value']??''):'';$previous=$current[$field];if($previous===$value)return $this->rollback('NO_CLINICAL_CHANGE');$normalized[]=['field_key'=>$field,'previous_value'=>$previous,'corrected_value'=>$value];$current[$field]=$value;}
   $sequence=$latest?(int)$latest->sequence_no+1:1;$clock=$this->db->query('SELECT CURRENT_TIMESTAMP(6) AS now')->row();$now=$clock?(string)$clock->now:'';if($now==='')return $this->rollback('WRITE_FAILED');$header=['record_id'=>$recordId,'request_id'=>$requestId,'sequence_no'=>$sequence,'previous_amendment_id'=>$latest?(int)$latest->amendment_id:null,'created_by_user_id'=>$userId,'reason'=>$reason,'created_at'=>$now,'idempotency_key'=>$key];$id=$this->model->insertHeader($header);if($id<1)return $this->rollback('WRITE_FAILED');$order=1;foreach($normalized as $row){$row['amendment_id']=$id;$row['item_order']=$order++;if(!$this->db->insert('clinical_amendment_items',$row))return $this->rollback('WRITE_FAILED');}
   $staff=$this->db->query("SELECT staff_id FROM puskesmas_staff WHERE user_id=? AND status='aktif' ORDER BY staff_id ASC LIMIT 1",[$userId])->row();$event=['actor_user_id'=>$userId,'actor_staff_id'=>$staff?(int)$staff->staff_id:0,'metadata'=>['amendment_id'=>$id,'record_id'=>$recordId,'request_id'=>$requestId],'domain_event_key'=>'clinical-amendment:'.$id];if(!doclinc_append_request_event($requestId,'clinical_record.amended',$event,get_instance()))return $this->rollback('WRITE_FAILED');$saved=$this->db->where('amendment_id',$id)->get('clinical_amendments')->row();if(!$this->db->trans_commit())return $this->fail('WRITE_FAILED');return ['status'=>'success','amendment_id'=>$id,'amendment'=>$saved,'items'=>$normalized];
  }catch(Throwable $e){$this->db->trans_rollback();$existing=$this->model->byKey($key);if($existing){if((int)$existing->record_id!==$recordId||(int)$existing->request_id!==$requestId||(int)$existing->created_by_user_id!==$userId||trim((string)$existing->reason)!==$reason||!$this->payloadMatches((int)$existing->amendment_id,$items))return $this->fail('AMENDMENT_KEY_CONFLICT');return ['status'=>'success','amendment_id'=>(int)$existing->amendment_id,'idempotent'=>true];}return $this->fail('WRITE_FAILED');}}
 private function payloadMatches($amendmentId,array $items){$rows=$this->db->query('SELECT field_key,corrected_value FROM clinical_amendment_items WHERE amendment_id=? ORDER BY item_order ASC FOR UPDATE',[(int)$amendmentId])->result_array();if(count($rows)!==count($items))return false;foreach(array_values($items) as $i=>$item){if(!is_array($item)||trim((string)($item['field_key']??''))!==(string)$rows[$i]['field_key']||(string)($item['corrected_value']??'')!==(string)$rows[$i]['corrected_value'])return false;}return true;}
 private function rollback($c){$this->db->trans_rollback();return $this->fail($c);}private function fail($c){return ['status'=>'error','safe_error_code'=>$c];}
}
