CREATE TABLE `clinical_master_record_revisions` (
  `clinical_master_record_revision_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinical_master_dataset_id` BIGINT UNSIGNED NOT NULL,
  `source_key_canonicalization` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_key_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_key_canonical` VARCHAR(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `source_record_canonicalization` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_record_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `revision_number` INT UNSIGNED NOT NULL,
  `first_import_item_id` BIGINT UNSIGNED NOT NULL,
  `last_import_item_id` BIGINT UNSIGNED NOT NULL,
  `first_seen_at` DATETIME(6) NOT NULL,
  `last_seen_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`clinical_master_record_revision_id`),
  UNIQUE KEY `uq_clinical_record_revision_identity` (`clinical_master_dataset_id`, `source_key_sha256`, `revision_number`),
  UNIQUE KEY `uq_clinical_record_revision_checksum` (`clinical_master_dataset_id`, `source_key_sha256`, `source_record_sha256`),
  KEY `idx_clinical_record_revision_record_sha` (`source_record_sha256`),
  KEY `idx_clinical_record_revision_first_item` (`first_import_item_id`),
  KEY `idx_clinical_record_revision_last_item` (`last_import_item_id`),
  CONSTRAINT `fk_clinical_record_revision_dataset` FOREIGN KEY (`clinical_master_dataset_id`) REFERENCES `clinical_master_datasets` (`clinical_master_dataset_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_clinical_record_revision_first_item` FOREIGN KEY (`first_import_item_id`) REFERENCES `clinical_master_import_items` (`import_item_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_clinical_record_revision_last_item` FOREIGN KEY (`last_import_item_id`) REFERENCES `clinical_master_import_items` (`import_item_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_clinical_record_revision_key_profile` CHECK (`source_key_canonicalization` = 'rfc8785-jcs-v1'),
  CONSTRAINT `chk_clinical_record_revision_record_profile` CHECK (`source_record_canonicalization` = 'rfc8785-jcs-v1'),
  CONSTRAINT `chk_clinical_record_revision_sha256` CHECK (`source_key_sha256` REGEXP '^[0-9a-f]{64}$' AND `source_record_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_record_revision_number` CHECK (`revision_number` >= 1),
  CONSTRAINT `chk_clinical_record_revision_source_key` CHECK (`source_key_canonical` <> '' AND OCTET_LENGTH(`source_key_canonical`) = OCTET_LENGTH(TRIM(`source_key_canonical`)) AND JSON_VALID(`source_key_canonical`) AND JSON_TYPE(`source_key_canonical`) = 'OBJECT'),
  CONSTRAINT `chk_clinical_record_revision_seen_at` CHECK (`last_seen_at` >= `first_seen_at`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
