CREATE TABLE `clinical_reference_term_types` (
  `clinical_reference_term_type_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `term_type_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `domain_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `entity_key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `description` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `governance_status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
  `runtime_reference_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `runtime_selection_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `decision_reason` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `decision_actor` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `decided_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`clinical_reference_term_type_id`),
  UNIQUE KEY `uq_clinical_reference_term_type_key` (`term_type_key`),
  KEY `idx_clinical_reference_term_type_domain_entity` (`domain_key`, `entity_key`),
  KEY `idx_clinical_reference_term_type_governance` (`governance_status`, `runtime_reference_enabled`, `runtime_selection_enabled`),
  CONSTRAINT `chk_clinical_reference_term_type_keys` CHECK (`term_type_key` REGEXP '^[a-z][a-z0-9_]*$' AND `domain_key` REGEXP '^[a-z][a-z0-9_]*$' AND `entity_key` REGEXP '^[a-z][a-z0-9_]*$'),
  CONSTRAINT `chk_clinical_reference_term_type_status` CHECK (`governance_status` IN ('draft','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_reference_term_type_booleans` CHECK (`runtime_reference_enabled` IN (0,1) AND `runtime_selection_enabled` IN (0,1)),
  CONSTRAINT `chk_clinical_reference_term_type_selection` CHECK (`runtime_selection_enabled` = 0 OR `runtime_reference_enabled` = 1),
  CONSTRAINT `chk_clinical_reference_term_type_runtime` CHECK (`runtime_reference_enabled` = 0 AND `runtime_selection_enabled` = 0 OR `governance_status` = 'approved'),
  CONSTRAINT `chk_clinical_reference_term_type_retired` CHECK (`governance_status` <> 'retired' OR `runtime_reference_enabled` = 0 AND `runtime_selection_enabled` = 0),
  CONSTRAINT `chk_clinical_reference_term_type_decision` CHECK (`governance_status` NOT IN ('approved','rejected','retired') OR `decision_actor` IS NOT NULL AND OCTET_LENGTH(`decision_actor`) > 0 AND OCTET_LENGTH(`decision_actor`) = OCTET_LENGTH(TRIM(`decision_actor`)) AND `decided_at` IS NOT NULL),
  CONSTRAINT `chk_clinical_reference_term_type_actor` CHECK (`decision_actor` IS NULL OR OCTET_LENGTH(`decision_actor`) > 0 AND OCTET_LENGTH(`decision_actor`) = OCTET_LENGTH(TRIM(`decision_actor`))),
  CONSTRAINT `chk_clinical_reference_term_type_reason` CHECK (`decision_reason` IS NULL OR OCTET_LENGTH(`decision_reason`) > 0 AND OCTET_LENGTH(`decision_reason`) = OCTET_LENGTH(TRIM(`decision_reason`)))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
