CREATE TABLE `clinical_reference_terms` (
  `clinical_reference_term_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinical_reference_term_type_id` BIGINT UNSIGNED NOT NULL,
  `term_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `preferred_label` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `display_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `governance_status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
  `runtime_reference_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `runtime_selection_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `effective_from` DATE NULL,
  `effective_to` DATE NULL,
  `retired_at` DATETIME(6) NULL,
  `is_current` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `replacement_term_id` BIGINT UNSIGNED NULL,
  `decision_reason` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `decision_actor` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `decided_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`clinical_reference_term_id`),
  UNIQUE KEY `uq_clinical_reference_term_type_code` (`clinical_reference_term_type_id`, `term_code`),
  UNIQUE KEY `uq_clinical_reference_term_id_type` (`clinical_reference_term_id`, `clinical_reference_term_type_id`),
  KEY `idx_clinical_reference_term_governance` (`clinical_reference_term_type_id`, `governance_status`, `is_current`),
  KEY `idx_clinical_reference_term_label` (`preferred_label`),
  KEY `idx_clinical_reference_term_replacement` (`replacement_term_id`, `clinical_reference_term_type_id`),
  CONSTRAINT `fk_clinical_reference_term_type` FOREIGN KEY (`clinical_reference_term_type_id`) REFERENCES `clinical_reference_term_types` (`clinical_reference_term_type_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_clinical_reference_term_replacement` FOREIGN KEY (`replacement_term_id`, `clinical_reference_term_type_id`) REFERENCES `clinical_reference_terms` (`clinical_reference_term_id`, `clinical_reference_term_type_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_clinical_reference_term_values` CHECK (`term_code` <> '' AND OCTET_LENGTH(`term_code`) = OCTET_LENGTH(TRIM(`term_code`)) AND !(`term_code` REGEXP '[[:cntrl:]]') AND `preferred_label` <> '' AND OCTET_LENGTH(`preferred_label`) = OCTET_LENGTH(TRIM(`preferred_label`)) AND !(`preferred_label` REGEXP '[[:cntrl:]]')),
  CONSTRAINT `chk_clinical_reference_term_status` CHECK (`governance_status` IN ('draft','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_reference_term_booleans` CHECK (`runtime_reference_enabled` IN (0,1) AND `runtime_selection_enabled` IN (0,1) AND `is_current` IN (0,1)),
  CONSTRAINT `chk_clinical_reference_term_selection` CHECK (`runtime_selection_enabled` = 0 OR `runtime_reference_enabled` = 1),
  CONSTRAINT `chk_clinical_reference_term_runtime` CHECK (`runtime_reference_enabled` = 0 OR `governance_status` = 'approved' AND `is_current` = 1 AND `retired_at` IS NULL),
  CONSTRAINT `chk_clinical_reference_term_effective_dates` CHECK (`effective_to` IS NULL OR `effective_from` IS NULL OR `effective_to` >= `effective_from`),
  CONSTRAINT `chk_clinical_reference_term_retired_at` CHECK (`retired_at` IS NULL OR `is_current` = 0 AND `runtime_reference_enabled` = 0 AND `runtime_selection_enabled` = 0),
  CONSTRAINT `chk_clinical_reference_term_retired_status` CHECK (`governance_status` <> 'retired' OR `is_current` = 0 AND `retired_at` IS NOT NULL AND `runtime_reference_enabled` = 0 AND `runtime_selection_enabled` = 0),
  CONSTRAINT `chk_clinical_reference_term_replacement_state` CHECK (`replacement_term_id` IS NULL OR `is_current` = 0),
  CONSTRAINT `chk_clinical_reference_term_decision` CHECK (`governance_status` NOT IN ('approved','rejected','retired') OR `decision_actor` IS NOT NULL AND OCTET_LENGTH(`decision_actor`) > 0 AND OCTET_LENGTH(`decision_actor`) = OCTET_LENGTH(TRIM(`decision_actor`)) AND `decided_at` IS NOT NULL),
  CONSTRAINT `chk_clinical_reference_term_actor` CHECK (`decision_actor` IS NULL OR OCTET_LENGTH(`decision_actor`) > 0 AND OCTET_LENGTH(`decision_actor`) = OCTET_LENGTH(TRIM(`decision_actor`))),
  CONSTRAINT `chk_clinical_reference_term_reason` CHECK (`decision_reason` IS NULL OR OCTET_LENGTH(`decision_reason`) > 0 AND OCTET_LENGTH(`decision_reason`) = OCTET_LENGTH(TRIM(`decision_reason`)))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
