CREATE TABLE `clinical_reference_term_labels` (
  `clinical_reference_term_label_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clinical_reference_term_id` BIGINT UNSIGNED NOT NULL,
  `label_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `language_code` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `label_value` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `governance_status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
  `runtime_search_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `effective_from` DATE NULL,
  `effective_to` DATE NULL,
  `retired_at` DATETIME(6) NULL,
  `is_current` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `decision_reason` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `decision_actor` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `decided_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`clinical_reference_term_label_id`),
  UNIQUE KEY `uq_clinical_reference_term_label_exact` (`clinical_reference_term_id`, `label_type`, `language_code`, `label_value`),
  KEY `idx_clinical_reference_term_label_search` (`language_code`, `label_value`),
  KEY `idx_clinical_reference_term_label_state` (`clinical_reference_term_id`, `is_current`, `governance_status`),
  CONSTRAINT `fk_clinical_reference_term_label_term` FOREIGN KEY (`clinical_reference_term_id`) REFERENCES `clinical_reference_terms` (`clinical_reference_term_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_clinical_reference_term_label_type` CHECK (`label_type` IN ('synonym','search_alias','abbreviation','legacy_label')),
  CONSTRAINT `chk_clinical_reference_term_label_language` CHECK (`language_code` REGEXP '^[a-z]{2,3}(-[a-z0-9]{2,8})*$'),
  CONSTRAINT `chk_clinical_reference_term_label_value` CHECK (`label_value` <> '' AND OCTET_LENGTH(`label_value`) = OCTET_LENGTH(TRIM(`label_value`)) AND !(`label_value` REGEXP '[[:cntrl:]]')),
  CONSTRAINT `chk_clinical_reference_term_label_status` CHECK (`governance_status` IN ('draft','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_reference_term_label_booleans` CHECK (`runtime_search_enabled` IN (0,1) AND `is_current` IN (0,1)),
  CONSTRAINT `chk_clinical_reference_term_label_runtime` CHECK (`runtime_search_enabled` = 0 OR `governance_status` = 'approved' AND `is_current` = 1 AND `retired_at` IS NULL),
  CONSTRAINT `chk_clinical_reference_term_label_dates` CHECK (`effective_to` IS NULL OR `effective_from` IS NULL OR `effective_to` >= `effective_from`),
  CONSTRAINT `chk_clinical_reference_term_label_retirement` CHECK (`retired_at` IS NULL OR `is_current` = 0 AND `runtime_search_enabled` = 0),
  CONSTRAINT `chk_clinical_reference_term_label_retired_status` CHECK (`governance_status` <> 'retired' OR `is_current` = 0 AND `retired_at` IS NOT NULL AND `runtime_search_enabled` = 0),
  CONSTRAINT `chk_clinical_reference_term_label_decision` CHECK (`governance_status` NOT IN ('approved','rejected','retired') OR `decision_actor` IS NOT NULL AND OCTET_LENGTH(`decision_actor`) > 0 AND OCTET_LENGTH(`decision_actor`) = OCTET_LENGTH(TRIM(`decision_actor`)) AND `decided_at` IS NOT NULL),
  CONSTRAINT `chk_clinical_reference_term_label_actor` CHECK (`decision_actor` IS NULL OR OCTET_LENGTH(`decision_actor`) > 0 AND OCTET_LENGTH(`decision_actor`) = OCTET_LENGTH(TRIM(`decision_actor`))),
  CONSTRAINT `chk_clinical_reference_term_label_reason` CHECK (`decision_reason` IS NULL OR OCTET_LENGTH(`decision_reason`) > 0 AND OCTET_LENGTH(`decision_reason`) = OCTET_LENGTH(TRIM(`decision_reason`)))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
