<?php

return array(
	'allowed_roots_environment' => 'DOCLINK_CLINICAL_PACKAGE_ALLOWED_ROOTS',
	'database_environment_variables' => array(
		'host' => 'DOCLINK_CLINICAL_SCHEMA_DB_HOST',
		'port' => 'DOCLINK_CLINICAL_SCHEMA_DB_PORT',
		'database' => 'DOCLINK_CLINICAL_SCHEMA_DB_NAME',
		'user' => 'DOCLINK_CLINICAL_SCHEMA_DB_USER',
		'password' => 'DOCLINK_CLINICAL_SCHEMA_DB_PASSWORD',
		'allowed_users' => 'DOCLINK_CLINICAL_SCHEMA_ALLOWED_USERS',
	),
	'write_database_environment_variables' => array(
		'host' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_DB_HOST',
		'port' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_DB_PORT',
		'database' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_DB_NAME',
		'user' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_DB_USER',
		'password' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_DB_PASSWORD',
		'allowed_users' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_ALLOWED_USERS',
	),
	'metadata_write_enabled_environment' => 'DOCLINK_CLINICAL_PACKAGE_METADATA_WRITE_ENABLED',
	'metadata_write_lock_timeout_environment' => 'DOCLINK_CLINICAL_PACKAGE_WRITE_LOCK_TIMEOUT_SECONDS',
	'hard_rejected_database_users' => array('doclinc-staging-user'),
	'metadata_registration_pins' => array(
		'package_key' => 'doclink-clinical-master',
		'package_version' => 'v1',
		'manifest_checksum' => '92ab0175e3fcb8681963bf4a3f9fdd7cad7fef9ef8db680978124f206f1e5417',
		'manifest_schema_version' => '1.0',
		'package_checksum' => 'fa512de0909e5e1f4fe6d394ca3b8103f5cefd98389f39ae016c4438e992fc34',
		'package_checksum_profile' => 'doclink-package-jcs-v1',
		'package_file_count' => 51,
		'package_snapshot_sha256' => 'e9373c66742caa172d83e05f265f76130e3343f298d13f9bb19cf16e22b6d493',
		'declared_dataset_count' => 47,
		'observed_dataset_count' => 47,
		'declared_record_count' => 14869,
		'observed_record_count' => 14869,
	),
	'established_validator_file' => dirname(__DIR__) . '/clinical_master/ClinicalMasterValidator.php',
	'established_rules_file' => dirname(__DIR__) . '/clinical_master/rules.php',
);
