CREATE TABLE `clinical_master_metadata_registration_events` (
  `metadata_registration_event_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `operation_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `execution_mode` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `registration_reference` VARCHAR(191) COLLATE utf8mb4_bin NOT NULL,
  `package_key` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_checksum` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_checksum_profile` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_snapshot_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `metadata_entity_count` SMALLINT UNSIGNED NOT NULL,
  `metadata_rows_planned` SMALLINT UNSIGNED NOT NULL,
  `metadata_rows_inserted` SMALLINT UNSIGNED NOT NULL,
  `state_before` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `state_after` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `result` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `idempotent_noop` TINYINT UNSIGNED NOT NULL,
  `metadata_transaction_committed` TINYINT UNSIGNED NOT NULL,
  `safe_failure_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `occurred_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`metadata_registration_event_id`),
  KEY `idx_clinical_metadata_registration_reference` (`registration_reference`),
  KEY `idx_clinical_metadata_registration_package` (`package_key`, `package_version`, `package_checksum`),
  KEY `idx_clinical_metadata_registration_snapshot` (`package_snapshot_sha256`),
  KEY `idx_clinical_metadata_registration_occurred` (`occurred_at`),
  KEY `idx_clinical_metadata_registration_result_occurred` (`result`, `occurred_at`),
  CONSTRAINT `chk_clinical_metadata_registration_operation` CHECK (`operation_type` = 'metadata_registration'),
  CONSTRAINT `chk_clinical_metadata_registration_execution_mode` CHECK (`execution_mode` = 'apply'),
  CONSTRAINT `chk_clinical_metadata_registration_checksum` CHECK (`package_checksum` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_metadata_registration_snapshot` CHECK (`package_snapshot_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_metadata_registration_checksum_profile` CHECK (`package_checksum_profile` = 'doclink-package-jcs-v1'),
  CONSTRAINT `chk_clinical_metadata_registration_entity_count` CHECK (`metadata_entity_count` > 0),
  CONSTRAINT `chk_clinical_metadata_registration_rows_planned` CHECK (`metadata_rows_planned` = `metadata_entity_count`),
  CONSTRAINT `chk_clinical_metadata_registration_rows_inserted` CHECK (`metadata_rows_inserted` = 0 OR `metadata_rows_inserted` = `metadata_entity_count`),
  CONSTRAINT `chk_clinical_metadata_registration_noop_boolean` CHECK (`idempotent_noop` IN (0,1)),
  CONSTRAINT `chk_clinical_metadata_registration_committed_boolean` CHECK (`metadata_transaction_committed` IN (0,1)),
  CONSTRAINT `chk_clinical_metadata_registration_state_before` CHECK (`state_before` IS NULL OR `state_before` IN ('new','exact_match','conflict')),
  CONSTRAINT `chk_clinical_metadata_registration_state_after` CHECK (`state_after` IS NULL OR `state_after` IN ('exact_match','conflict')),
  CONSTRAINT `chk_clinical_metadata_registration_result` CHECK (`result` IN ('committed','idempotent_noop','rejected','rolled_back')),
  CONSTRAINT `chk_clinical_metadata_registration_result_consistency` CHECK (
    `result` = 'committed' AND `state_before` = 'new' AND `state_after` = 'exact_match' AND `metadata_rows_inserted` = `metadata_entity_count` AND `idempotent_noop` = 0 AND `metadata_transaction_committed` = 1 AND `safe_failure_code` IS NULL
    OR `result` = 'idempotent_noop' AND `state_before` = 'exact_match' AND `state_after` = 'exact_match' AND `metadata_rows_inserted` = 0 AND `idempotent_noop` = 1 AND `metadata_transaction_committed` = 1 AND `safe_failure_code` IS NULL
    OR `result` = 'rejected' AND `metadata_rows_inserted` = 0 AND `idempotent_noop` = 0 AND `metadata_transaction_committed` = 0 AND `safe_failure_code` IS NOT NULL
    OR `result` = 'rolled_back' AND `metadata_rows_inserted` = 0 AND `idempotent_noop` = 0 AND `metadata_transaction_committed` = 0 AND `safe_failure_code` IS NOT NULL
  ),
  CONSTRAINT `chk_clinical_metadata_registration_reference` CHECK (TRIM(`registration_reference`) <> '' AND !(`registration_reference` REGEXP '[[:cntrl:]]')),
  CONSTRAINT `chk_clinical_metadata_registration_package_identity` CHECK (TRIM(`package_key`) <> '' AND TRIM(`package_version`) <> ''),
  CONSTRAINT `chk_clinical_metadata_registration_failure_code` CHECK (`safe_failure_code` IS NULL OR `safe_failure_code` REGEXP '^[a-z0-9_]+$')
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
