<?php

return array(
    'memory_warning_threshold_bytes' => 134217728,
    'canonical_statuses' => array(
        'draft',
        'in_review',
        'approved',
        'rejected',
        'retired',
    ),
    'review_types' => array(
        'clinical',
        'clinical_coder',
        'pharmacy',
        'product',
        'security',
    ),
    'expected_schema_definitions' => array(
        'canonicalStatus',
        'reviewType',
        'sha256',
        'relativePath',
        'uniqueKey',
        'sourceStatusMapping',
        'canonicalStatusSource',
        'reviewGovernance',
        'dependencyPolicy',
        'dependencyDetail',
        'runtimePolicyBase',
        'runtimePolicies',
        'submanifest',
        'dataset',
    ),
    'required_manifest_fields' => array(
        '$schema',
        'manifest_schema_version',
        'package_id',
        'package_version',
        'package_status',
        'production_ready',
        'runtime_enabled',
        'contains_patient_data',
        'contains_personal_data',
        'contains_credentials',
        'package_summary',
        'governance_notices',
        'review_governance',
        'dependency_policy',
        'runtime_policies',
        'submanifests',
        'datasets',
    ),
    'required_dataset_fields' => array(
        'dataset_id',
        'path',
        'domain',
        'entity',
        'version',
        'source',
        'source_version',
        'source_status',
        'license_status',
        'language',
        'record_count',
        'sha256',
        'json_root_type',
        'unique_key',
        'dependencies',
        'seed_order',
        'review_type',
        'canonical_review_status',
        'canonical_status_source',
        'runtime_selectable',
        'runtime_enabled',
        'clinical_review_required',
        'pharmacy_review_required',
        'master_reference_only',
        'notes',
    ),
    'allowed_empty_unique_key_components' => array(),
    'required_local_fields' => array(
        'MASTER_RED_FLAG' => array('pertanyaan_kode', 'nilai_pemicu'),
    ),
    'relations' => array(
        array(
            'source_dataset' => 'MASTER_KELUHAN_GEJALA',
            'source_fields' => array('keluhan_kode'),
            'target_dataset' => 'MASTER_KELUHAN',
            'target_fields' => array('kode'),
            'relation_type' => 'explicit_record_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Complaint code must exist in the complaint master.',
        ),
        array(
            'source_dataset' => 'MASTER_KELUHAN_GEJALA',
            'source_fields' => array('gejala_kode'),
            'target_dataset' => 'MASTER_GEJALA',
            'target_fields' => array('kode'),
            'relation_type' => 'explicit_record_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Symptom code must exist in the symptom master.',
        ),
        array(
            'source_dataset' => 'MASTER_KELUHAN_PERTANYAAN',
            'source_fields' => array('keluhan_kode'),
            'target_dataset' => 'MASTER_KELUHAN',
            'target_fields' => array('kode'),
            'relation_type' => 'explicit_record_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Complaint code must exist in the complaint master.',
        ),
        array(
            'source_dataset' => 'MASTER_KELUHAN_PERTANYAAN',
            'source_fields' => array('pertanyaan_kode'),
            'target_dataset' => 'MASTER_PERTANYAAN_KLINIS',
            'target_fields' => array('kode'),
            'relation_type' => 'explicit_record_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Question code must exist in the clinical-question master.',
        ),
        array(
            'source_dataset' => 'MASTER_OPSI_JAWABAN',
            'source_fields' => array('grup'),
            'target_dataset' => 'MASTER_PERTANYAAN_KLINIS',
            'target_fields' => array('grup_opsi'),
            'relation_type' => 'declared_option_group_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'The observed option group references a declared question option group; no pertanyaan_kode field is invented.',
        ),
        array(
            'source_dataset' => 'MASTER_RED_FLAG',
            'source_fields' => array('pertanyaan_kode'),
            'target_dataset' => 'MASTER_PERTANYAAN_KLINIS',
            'target_fields' => array('kode'),
            'relation_type' => 'declared_red_flag_question_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Red flags reference observed question codes only; tingkat_urgensi is not treated as an urgency-master foreign key.',
        ),
        array(
            'source_dataset' => 'MASTER_ICD10_BLOCK_WHO_2019',
            'source_fields' => array('chapter_code'),
            'target_dataset' => 'MASTER_ICD10_CHAPTER_WHO_2019',
            'target_fields' => array('kode'),
            'relation_type' => 'icd_block_chapter_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'ICD block chapter code must exist in the chapter dataset.',
        ),
        array(
            'source_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'source_fields' => array('chapter_code'),
            'target_dataset' => 'MASTER_ICD10_CHAPTER_WHO_2019',
            'target_fields' => array('kode'),
            'relation_type' => 'icd_diagnosis_chapter_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Diagnosis chapter code must exist in the chapter dataset.',
        ),
        array(
            'source_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'source_fields' => array('block_code'),
            'target_dataset' => 'MASTER_ICD10_BLOCK_WHO_2019',
            'target_fields' => array('kode'),
            'relation_type' => 'icd_diagnosis_block_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Diagnosis block code must exist in the block dataset.',
        ),
        array(
            'source_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'source_fields' => array('parent_code'),
            'target_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'target_fields' => array('kode_icd10'),
            'relation_type' => 'icd_diagnosis_parent',
            'missing_value_policy' => 'category_parent_is_block',
            'strict' => true,
            'notes' => 'Category parents are block codes; subcategory parents must be diagnosis categories.',
        ),
        array(
            'source_dataset' => 'MASTER_DIAGNOSIS_ALIAS_INDONESIA_STARTER',
            'source_fields' => array('kode_icd10'),
            'target_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'target_fields' => array('kode_icd10'),
            'relation_type' => 'icd_alias_reference',
            'missing_value_policy' => 'error',
            'strict' => true,
            'notes' => 'Alias code must exist in the diagnosis dataset.',
        ),
        array(
            'source_dataset' => 'ICD10_LEGACY_CODE_REVIEW',
            'source_fields' => array('legacy_code'),
            'target_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'target_fields' => array('kode_icd10'),
            'relation_type' => 'contextual_review',
            'missing_value_policy' => 'allow_missing',
            'strict' => false,
            'notes' => 'Legacy codes need not exist in WHO diagnosis data and are never automatically mapped or imported.',
        ),
        array(
            'source_dataset' => 'ICD10_LEGACY_CODE_REVIEW',
            'source_fields' => array('candidate_who_icd10_2019'),
            'target_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
            'target_fields' => array('kode_icd10'),
            'relation_type' => 'proposed_replacement_reference',
            'missing_value_policy' => 'allow_missing_or_null',
            'strict' => true,
            'notes' => 'An explicitly supplied candidate is checked for existence but no replacement mapping is produced.',
        ),
    ),
    'icd' => array(
        'chapter_dataset' => 'MASTER_ICD10_CHAPTER_WHO_2019',
        'block_dataset' => 'MASTER_ICD10_BLOCK_WHO_2019',
        'diagnosis_dataset' => 'MASTER_DIAGNOSIS_ICD10_WHO_2019',
        'alias_dataset' => 'MASTER_DIAGNOSIS_ALIAS_INDONESIA_STARTER',
        'legacy_dataset' => 'ICD10_LEGACY_CODE_REVIEW',
        'submanifest_path' => '00_icd10_manifest.json',
    ),
);
