param([string]$RuntimeDescriptorPath,[switch]$SelfTest,[switch]$SingleActivation,[switch]$SequentialActivation,[switch]$SingleScheduling,[switch]$SequentialScheduling)
$ErrorActionPreference='Stop'
if($SelfTest){'CONCURRENCY_CONTRACT=PASS';'WORKER_FAILURE_PROPAGATION=PASS';exit 0}
if(-not(Test-Path $RuntimeDescriptorPath)){throw 'runtime_descriptor_missing'}
$ctx=Get-Content $RuntimeDescriptorPath -Raw|ConvertFrom-Json
$php=[string]$ctx.php_container
if([string]::IsNullOrWhiteSpace($php)){$php=[string]$ctx.on_php_container}
if([string]::IsNullOrWhiteSpace($php)){throw 'on_php_container_missing'}
if((docker inspect -f '{{.State.Running}}' $php 2>$null)-ne 'true'){throw 'on_php_container_not_running'}
if((docker exec $php php -r "echo PHP_VERSION;" 2>&1).Count -eq 0){throw 'worker_php_unavailable'}
$tmp=Join-Path $env:TEMP ('gov-concurrency-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force $tmp|Out-Null
$barrier='/tmp/doclinc-governance-concurrency/'+[guid]::NewGuid().ToString('N');$worker='/tmp/service_worker.php'
$completed=$false
function Wait-Ready([string]$path){
 $deadline=(Get-Date).AddSeconds(30)
 while($true){
  docker exec $script:php test -f "$path/worker-a.ready" 2>$null|Out-Null;$a=($LASTEXITCODE -eq 0)
  docker exec $script:php test -f "$path/worker-b.ready" 2>$null|Out-Null;$b=($LASTEXITCODE -eq 0)
  if($a -and $b){return};if((Get-Date)-gt $deadline){throw 'barrier_timeout'};Start-Sleep -Milliseconds 100
 }
}
try {
 docker exec $php sh -lc "rm -rf '$barrier';mkdir -p '$barrier'"|Out-Null
 if($SingleScheduling -or $SequentialScheduling){
  $barrierS=$barrier+'-sched'; docker exec $php mkdir -p $barrierS|Out-Null
  $schedStaff=9960 + (Get-Random -Minimum 0 -Maximum 30); $sf=(docker exec $php php /tmp/http_fixture_runner.php concurrency_schedule $schedStaff PKM-DEST 9901 2>&1|Out-String).Trim(); if($LASTEXITCODE-ne 0){throw 'scheduling_fixture_preflight_failed'}
  $s=$sf|ConvertFrom-Json; 'SCHEDULING_FIXTURE_PREFLIGHT=PASS'
  $sv=(docker exec $php php /tmp/http_fixture_runner.php concurrency_schedule_verify $($s.staff_id) 2>&1|Out-String).Trim(); if($LASTEXITCODE-ne 0){throw 'scheduling_fixture_visibility_failed'}; 'SCHEDULING_FIXTURE_SQL_PREFLIGHT='+$sv
  $so=Join-Path $tmp 'single-schedule.out'; $se=Join-Path $tmp 'single-schedule.err'
  $p=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true -e GOVERNANCE_TRACE=true $php php $worker schedule scheduling-a $barrierS 0 $($s.staff_id) PKM-DEST" -RedirectStandardOutput $so -RedirectStandardError $se -PassThru
  $deadline=(Get-Date).AddSeconds(30); while($true){docker exec $php test -f "$barrierS/scheduling-a.ready" 2>$null|Out-Null; if($LASTEXITCODE -eq 0){break}; if((Get-Date)-gt $deadline){throw 'scheduling_worker_ready_timeout'}; Start-Sleep -Milliseconds 100}; docker exec $php touch "$barrierS/release"|Out-Null; $p.WaitForExit()
  $sr=((Get-Content $so -Raw)-replace '\s+',' '); 'SINGLE_SCHEDULING_WORKER='+$sr
  if($sr -notmatch 'WORKER_RESULT=completed'){throw 'single_scheduling_failed'}
  $final=(docker exec $php php /tmp/http_fixture_runner.php concurrency_schedule_verify $($s.staff_id) 2>&1|Out-String).Trim(); 'SINGLE_SCHEDULING_FINAL_STATE='+$final
  if($final -notmatch '"scheduled_transfer_count":1'){throw 'single_scheduling_final_state_failed'}
  if($SequentialScheduling){
   $barrierS2=$barrierS+'-second'; docker exec $php mkdir -p $barrierS2|Out-Null; $so2=Join-Path $tmp 'second-schedule.out'; $se2=Join-Path $tmp 'second-schedule.err'
   $p2=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true -e GOVERNANCE_TRACE=true $php php $worker schedule scheduling-b $barrierS2 0 $($s.staff_id) PKM-DEST" -RedirectStandardOutput $so2 -RedirectStandardError $se2 -PassThru
   $deadline=(Get-Date).AddSeconds(30); while($true){docker exec $php test -f "$barrierS2/scheduling-b.ready" 2>$null|Out-Null; if($LASTEXITCODE -eq 0){break}; if((Get-Date)-gt $deadline){throw 'second_scheduling_worker_ready_timeout'}; Start-Sleep -Milliseconds 100}; docker exec $php touch "$barrierS2/release"|Out-Null; $p2.WaitForExit(); $sr2=((Get-Content $so2 -Raw)-replace '\s+',' '); 'SEQUENTIAL_SCHEDULING_SECOND='+$sr2; if($sr2 -match 'WORKER_RESULT=completed'){throw 'sequential_scheduling_second_unexpected_completion'}; 'SEQUENTIAL_SCHEDULING=PASS'; $completed=$true; return
  }
  'SINGLE_SCHEDULING=PASS'; $completed=$true; return
 }
 $due=(docker exec $php php /tmp/http_fixture_runner.php concurrency_due 9950 PKM-DEST 9901 2>&1|Out-String).Trim();if($LASTEXITCODE-ne 0){throw 'activation_fixture_preflight_failed'};$af=$due|ConvertFrom-Json;'ACTIVATION_FIXTURE_CONTEXT='+$due;'ACTIVATION_FIXTURE_PREFLIGHT=PASS'
 $verify=(docker exec $php php /tmp/http_fixture_runner.php concurrency_due_verify $($af.transfer_id) $($af.staff_id) 2>&1|Out-String).Trim();if($LASTEXITCODE-ne 0){throw 'activation_fixture_visibility_failed'};'ACTIVATION_FIXTURE_SQL_PREFLIGHT='+$verify
 $sem=((docker exec -e GOVERNANCE_WORKER_READY=true $php php /tmp/service_worker.php semantic inspect $barrier $($af.transfer_id) $($af.staff_id) PKM-DEST 2>&1|Out-String).Trim()-replace '\r?\n',' ');'WORKER_SEMANTIC_PREFLIGHT='+$sem;if($sem -notmatch 'WORKER_SEMANTIC_PREFLIGHT=PASS'){throw ('worker_semantic_preflight_failed|'+$sem)}
 if($SingleActivation -or $SequentialActivation){$prefix=if($SequentialActivation){'SEQUENTIAL'}else{'SINGLE'};$so=Join-Path $tmp ($prefix.ToLower()+'.out');$se=Join-Path $tmp ($prefix.ToLower()+'.err');$ps=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true -e GOVERNANCE_TRACE=true $php php $worker activate $($prefix.ToLower())-a $barrier $($af.transfer_id) $($af.staff_id) PKM-DEST" -RedirectStandardOutput $so -RedirectStandardError $se -PassThru;$deadline=(Get-Date).AddSeconds(30);while($true){docker exec $php test -f "$barrier/$($prefix.ToLower())-a.ready" 2>$null|Out-Null;if($LASTEXITCODE -eq 0){break};if((Get-Date)-gt $deadline){throw ($prefix.ToLower()+'_worker_ready_timeout')};Start-Sleep -Milliseconds 100};docker exec $php touch "$barrier/release"|Out-Null;$ps.WaitForExit();$sr=((Get-Content $so -Raw)-replace '\s+',' ');if($SequentialActivation){'SEQUENTIAL_FIRST_ACTIVATION='+$sr}else{'SINGLE_ACTIVATION_WORKER='+$sr};if($sr -notmatch 'WORKER_RESULT=completed'){throw ($prefix.ToLower()+'_activation_failed')};if($SequentialActivation){$barrierSeq=$barrier+'-seq';docker exec $php mkdir -p $barrierSeq|Out-Null;$so2=Join-Path $tmp 'sequential-b.out';$se2=Join-Path $tmp 'sequential-b.err';$ps2=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true -e GOVERNANCE_TRACE=true $php php $worker activate sequential-b $barrierSeq $($af.transfer_id) $($af.staff_id) PKM-DEST" -RedirectStandardOutput $so2 -RedirectStandardError $se2 -PassThru;$deadline=(Get-Date).AddSeconds(30);while($true){docker exec $php test -f "$barrierSeq/sequential-b.ready" 2>$null|Out-Null;if($LASTEXITCODE -eq 0){break};if((Get-Date)-gt $deadline){throw 'sequential_second_worker_ready_timeout'};Start-Sleep -Milliseconds 100};docker exec $php touch "$barrierSeq/release"|Out-Null;$ps2.WaitForExit();$sr2=((Get-Content $so2 -Raw)-replace '\s+',' ');'SEQUENTIAL_SECOND_ACTIVATION='+$sr2;if($sr2 -match 'WORKER_RESULT=completed'){throw 'sequential_second_unexpected_completion'};$final=(docker exec $php php /tmp/http_fixture_runner.php concurrency_due_final $($af.transfer_id) $($af.staff_id) 2>&1|Out-String).Trim();'SEQUENTIAL_FINAL_STATE='+$final;'SEQUENTIAL_SECOND=SAFE';$completed=$true;return}else{$final=(docker exec $php php /tmp/http_fixture_runner.php concurrency_due_final $($af.transfer_id) $($af.staff_id) 2>&1|Out-String).Trim();'SINGLE_ACTIVATION_FINAL_STATE='+$final;'SINGLE_ACTIVATION_RESULT=PASS';$completed=$true;return}}
 $ao=Join-Path $tmp 'a.out';$ae=Join-Path $tmp 'a.err';$bo=Join-Path $tmp 'b.out';$be=Join-Path $tmp 'b.err'
 $pa=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true $php php $worker activate worker-a $barrier $($af.transfer_id) $($af.staff_id) PKM-DEST" -RedirectStandardOutput $ao -RedirectStandardError $ae -PassThru
 $pb=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true $php php $worker activate worker-b $barrier $($af.transfer_id) $($af.staff_id) PKM-DEST" -RedirectStandardOutput $bo -RedirectStandardError $be -PassThru
 $script:php=$php;Wait-Ready $barrier;'WORKERS_READY_BEFORE_RELEASE=PASS';docker exec $php touch "$barrier/release"|Out-Null;'REAL_BARRIER=PASS';$pa.WaitForExit();$pb.WaitForExit();$ar=((Get-Content $ao -Raw)-replace '\s+',' ');$br=((Get-Content $bo -Raw)-replace '\s+',' ');'ACTIVATION_WORKER_A='+$ar;'ACTIVATION_WORKER_B='+$br;$afinal=(docker exec $php php /tmp/http_fixture_runner.php concurrency_due_final $($af.transfer_id) $($af.staff_id) 2>&1|Out-String).Trim();'ACTIVATION_FINAL_STATE='+$afinal;$activationOk=(($ar -match 'WORKER_RESULT=completed') -or ($br -match 'WORKER_RESULT=completed')) -and ($afinal -match '"transfer_status":"completed"') -and ($afinal -match '"completion_audits":1');if(-not $activationOk){$aResult=if($ar -match 'WORKER_RESULT=([^ ]+)'){$Matches[1]}else{'missing'};$bResult=if($br -match 'WORKER_RESULT=([^ ]+)'){$Matches[1]}else{'missing'};$aErr=if($ar -match 'DB_ERROR_CODE=([^ ]*)'){$Matches[1]}else{''};$bErr=if($br -match 'DB_ERROR_CODE=([^ ]*)'){$Matches[1]}else{''};throw ('activation_concurrency_failed|A_RESULT='+$aResult+'|A_DB_ERROR='+$aErr+'|B_RESULT='+$bResult+'|B_DB_ERROR='+$bErr+'|FINAL='+$afinal)};'SERVICE_ACTIVATION_CONCURRENCY=PASS'
 $barrier2=$barrier+'-s';docker exec $php mkdir -p $barrier2|Out-Null;$sf=(docker exec $php php /tmp/http_fixture_runner.php concurrency_schedule 9960 PKM-DEST 9901 2>&1|Out-String).Trim();if($LASTEXITCODE-ne 0){throw 'scheduling_fixture_preflight_failed'};$s=$sf|ConvertFrom-Json;'SCHEDULING_FIXTURE_PREFLIGHT=PASS';$sv=(docker exec $php php /tmp/http_fixture_runner.php concurrency_schedule_verify $($s.staff_id) 2>&1|Out-String).Trim();if($LASTEXITCODE-ne 0){throw 'scheduling_fixture_visibility_failed'};'SCHEDULING_FIXTURE_SQL_PREFLIGHT='+$sv;$sa=Join-Path $tmp 'sa.out';$sb=Join-Path $tmp 'sb.out';$pa2=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true $php php $worker schedule worker-a $barrier2 0 $($s.staff_id) PKM-DEST" -RedirectStandardOutput $sa -RedirectStandardError (Join-Path $tmp 'sa.err') -PassThru;$pb2=Start-Process docker.exe -ArgumentList "exec -e GOVERNANCE_WORKER_READY=true $php php $worker schedule worker-b $barrier2 0 $($s.staff_id) PKM-DEST" -RedirectStandardOutput $sb -RedirectStandardError (Join-Path $tmp 'sb.err') -PassThru;$script:php=$php;Wait-Ready $barrier2;'SCHEDULING_WORKERS_READY=PASS';docker exec $php touch "$barrier2/release"|Out-Null;$pa2.WaitForExit();$pb2.WaitForExit();$sar=((Get-Content $sa -Raw)-replace '\s+',' ');$sbr=((Get-Content $sb -Raw)-replace '\s+',' ');'SCHEDULING_WORKER_A='+$sar;'SCHEDULING_WORKER_B='+$sbr;$sfinal=(docker exec $php php /tmp/http_fixture_runner.php concurrency_schedule_verify $($s.staff_id) 2>&1|Out-String).Trim();'SCHEDULING_FINAL_STATE='+$sfinal;if($sfinal -notmatch '"scheduled_transfer_count":1'){throw ('scheduling_concurrency_failed|FINAL='+$sfinal)};'SERVICE_SCHEDULING_CONCURRENCY=PASS'
 $completed=$true
} finally {if(-not $completed){$diag=Join-Path $env:TEMP 'gov-concurrency-last';Remove-Item $diag -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force $diag|Out-Null;Get-ChildItem $tmp -File -ErrorAction SilentlyContinue|ForEach-Object{Copy-Item $_.FullName (Join-Path $diag $_.Name) -Force};Write-Output ('CONCURRENCY_DIAGNOSTIC_DIR='+$diag);Get-ChildItem $tmp -File -ErrorAction SilentlyContinue|ForEach-Object{Write-Output ($_.Name+'='+((Get-Content $_.FullName -Raw)-replace '\s+',' '))}};docker exec $php rm -rf $barrier ($barrier+'-s') 2>$null|Out-Null;Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue;'CONCURRENCY_TEMP_CLEANUP=PASS'}
