<?php
declare(strict_types=1);
$op=$argv[1]??''; $worker=$argv[2]??'worker'; $barrier=$argv[3]??''; $transfer=(int)($argv[4]??0); $staff=(int)($argv[5]??0); $destination=(string)($argv[6]??'PKM-DEST');
if(!in_array($op,['schedule','activate','semantic'],true)||getenv('GOVERNANCE_WORKER_READY')!=='true'||$barrier===''){echo "WORKER_RESULT=BLOCKED\nWORKER_REASON=runtime_context_missing\n";exit(2);}
define('BASEPATH','/var/www/html/system/'); define('APPPATH','/var/www/html/application/'); define('FCPATH','/var/www/html/'); define('ENVIRONMENT','staging');
require_once BASEPATH.'core/Common.php'; require_once BASEPATH.'database/DB.php';
$db=DB(['dsn'=>'','hostname'=>getenv('DB_HOST'),'username'=>getenv('DB_USER'),'password'=>getenv('DB_PASS'),'database'=>getenv('DB_NAME'),'dbdriver'=>'mysqli','dbprefix'=>'','pconnect'=>false,'db_debug'=>false,'cache_on'=>false,'cachedir'=>'','char_set'=>'utf8','dbcollat'=>'utf8_general_ci','port'=>3306,'stricton'=>false],true);
final class GovernanceWorkerLoader{private $db;public function __construct($db){$this->db=$db;}public function database($group='default',$return=false){return $this->db;}}
final class GovernanceWorkerApplication{public $db;public $load;public function __construct($db){$this->db=$db;$this->load=new GovernanceWorkerLoader($db);}}
$GLOBALS['governance_worker_application']=new GovernanceWorkerApplication($db); function &get_instance(){return $GLOBALS['governance_worker_application'];}
require_once APPPATH.'helpers/request_authz_helper.php'; require_once APPPATH.'libraries/Nakes_placement_policy.php'; require_once APPPATH.'libraries/Nakes_placement_store.php'; require_once APPPATH.'libraries/Nakes_placement_service.php';
class GovernanceTracingStore extends Nakes_placement_store { public $trace=array(); private function t($m,$r){$this->trace[]=array('method'=>$m,'result'=>$r);} private function em(Throwable $e){return preg_replace('/[\r\n]+/',' ',substr((string)$e->getMessage(),0,200));} public function transaction($cb){$this->t('transaction.enter','ENTERED');$r=parent::transaction(function()use($cb){try{$x=$cb();$this->t('transaction.callback',is_array($x)?'ARRAY':($x===false?'FALSE':gettype($x)));return $x;}catch(Throwable $e){$this->t('transaction.callback_exception',get_class($e).':'.(string)$e->getCode().':'.$this->em($e));throw $e;}});$this->t('transaction.return',$r===false?'FALSE':(is_array($r)?'ARRAY':gettype($r)));return $r;} public function transfer($id,$lock=false){$r=parent::transfer($id,$lock);$this->t('transfer('.(int)$id.','.($lock?'true':'false').')',$r?('FOUND:'.($r['status']??'')):'NOT_FOUND');return $r;} public function activePlacement($id){$r=parent::activePlacement($id);$this->t('activePlacement('.(int)$id.')',$r?('FOUND:'.($r['placement_id']??'')):'NOT_FOUND');return $r;} public function blockers($id){$r=parent::blockers($id);$this->t('blockers('.(int)$id.')','COUNT:'.count($r));return $r;} public function endPlacement($id,$now){$r=parent::endPlacement($id,$now);$this->t('endPlacement('.(int)$id.')',$r?'SUCCESS':'FALSE');return $r;} public function insertPlacement($row){$r=parent::insertPlacement($row);$this->t('insertPlacement',$r?'SUCCESS':'FALSE');return $r;} public function updateProjection($id,$dest){$r=parent::updateProjection($id,$dest);$this->t('updateProjection('.(int)$id.')',$r?'SUCCESS':'FALSE');return $r;} public function completeTransfer($id,$now){$r=parent::completeTransfer($id,$now);$this->t('completeTransfer('.(int)$id.')',$r?'SUCCESS':'FALSE');return $r;} public function audit($event,$data){try{$r=parent::audit($event,$data);$this->t('audit('.$event.')',$r?'SUCCESS':'FALSE');return $r;}catch(Throwable $e){$this->t('audit_exception',get_class($e).':'.(string)$e->getCode().':'.$this->em($e));throw $e;}} }
$meta=$db->query('SELECT DATABASE() AS db_name, @@server_id AS server_id, CONNECTION_ID() AS id')->row();$id=(int)$meta->id;
$pre=array('identity_valid'=>false,'destination_active'=>false,'active_placement'=>false,'transfer_scheduled'=>false,'blocker_count'=>0);
if($staff>0 && function_exists('doclinc_dokter_identity_context')){$identity=doclinc_dokter_identity_context($staff,true);$pre['identity_valid']=!empty($identity['valid']) && (($identity['account_type']??'')==='personal') && (($identity['role']??'')==='dokter') && (($identity['user_status']??'')==='aktif');}
$destRow=$db->query("SELECT status FROM m_puskesmas WHERE kode_pkm='".$db->escape_str(strtoupper($destination))."' LIMIT 1");$pre['destination_active']=($destRow && ($r=$destRow->row()) && (string)$r->status==='aktif');
if($staff>0){$q=$db->query("SELECT status FROM nakes_facility_placements WHERE staff_id=".(int)$staff." AND status='active' LIMIT 1");$pre['active_placement']=($q && $q->num_rows>0);$q=$db->query("SELECT status FROM nakes_facility_transfers WHERE transfer_id=".(int)$transfer." AND status='scheduled' LIMIT 1");$pre['transfer_scheduled']=($q && $q->num_rows>0);}
$store=(getenv('GOVERNANCE_TRACE')==='true')?new GovernanceTracingStore($db):new Nakes_placement_store($db); $semantic=$store->transaction(function() use ($store,$staff,$transfer){$active=$staff>0?$store->activePlacement($staff):null;$row=$transfer>0?$store->transfer($transfer,true):null;$due=$row && strtotime(date('Y-m-d H:i:s'))>=strtotime((string)$row['effective_at']);return ['active'=>$active,'transfer'=>$row,'due'=>(bool)$due];}); $semanticActive=$semantic['active']??null; $semanticTransfer=$semantic['transfer']??null; $pre['store_active_placement']=($semanticActive!==null); $pre['store_transfer_scheduled']=($semanticTransfer!==null && (string)$semanticTransfer['status']==='scheduled'); $pre['store_transfer_due']=(bool)($semantic['due']??false); $service=new Nakes_placement_service($store,true,['user_id'=>9901,'role'=>'admin','status'=>'aktif']); $result=false;$callEntered=false;$callReturned=false;$callException='';
if($op==='semantic'){echo "WORKER_SEMANTIC_PREFLIGHT=".(($pre['identity_valid']&&$pre['store_active_placement']&&$pre['store_transfer_scheduled']&&$pre['store_transfer_due'])?'PASS':'FAIL')." DATABASE=".(string)$meta->db_name." SERVER_ID=".(string)$meta->server_id." PRE_IDENTITY=".($pre['identity_valid']?'YES':'NO')." PRE_STORE_ACTIVE=".($pre['store_active_placement']?'YES':'NO')." PRE_STORE_TRANSFER=".($pre['store_transfer_scheduled']?'YES':'NO')." PRE_DUE=".($pre['store_transfer_due']?'YES':'NO')."\n";exit(0);}
file_put_contents($barrier.'/'.$worker.'.ready',(string)$id); $deadline=microtime(true)+30; while(!is_file($barrier.'/release')){if(microtime(true)>$deadline){echo "WORKER_RESULT=TIMEOUT\n";exit(3);}usleep(10000);}
try{$callEntered=true;if($op==='activate')$result=$service->activate($transfer,date('Y-m-d H:i:s')); else $result=$service->schedule(['staff_id'=>$staff,'destination_facility'=>$destination,'effective_at'=>'2031-01-01 00:00:00','reason'=>'concurrency']);$callReturned=true;}catch(Throwable $e){$callException=get_class($e);}
$err=$db->error();$resultClass=$result?'completed':($callException!==''?'exception':'safe_conflict');$traceOut=isset($store->trace)?json_encode($store->trace):'[]';$canManage=Nakes_placement_policy::canManageTransfer(['user_id'=>9901,'role'=>'admin','status'=>'aktif']);echo 'WORKER='.$worker."\nOPERATION=$op\nINPUT_TRANSFER=$transfer\nINPUT_STAFF=$staff\nDATABASE=".(string)$meta->db_name."\nSERVER_ID=".(string)$meta->server_id."\nDB_CONNECTION_ID=$id\nFEATURE_ENABLED=YES\nCAN_MANAGE_TRANSFER=".($canManage?'YES':'NO')."\nPRECHECK=".json_encode($pre)."\nSERVICE_CALL_ENTERED=".($callEntered?'YES':'NO')."\nSERVICE_CALL_RETURNED=".($callReturned?'YES':'NO')."\nSERVICE_RESULT_CLASS=$resultClass\nEXCEPTION_CLASS=$callException\nDB_ERROR_CODE=".(string)($err['code']??'')."\nDB_ERROR_MESSAGE_SAFE=".preg_replace('/[\r\n]+/',' ',(string)($err['message']??''))."\nTRACE=$traceOut\nWORKER_RESULT=".($result?'completed':'safe_conflict')."\n"; exit(0);
