<?php
defined('BASEPATH') or exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$base_url = getenv('APP_BASE_URL') ?: getenv('DOCLINC_BASE_URL') ?: getenv('CI_BASE_URL');
if ($base_url) {
	$config['base_url'] = rtrim($base_url, '/') . '/';
} else {
	$https = (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) === 'on')
		|| (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
		|| (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && strtolower($_SERVER['HTTP_X_FORWARDED_SSL']) === 'on');
	$protocol = $https ? 'https' : 'http';
	$host = !empty($_SERVER['HTTP_X_FORWARDED_HOST']) ? $_SERVER['HTTP_X_FORWARDED_HOST'] : ($_SERVER['HTTP_HOST'] ?? 'localhost');
	$host = preg_replace('/[^a-z0-9.\-:_]/i', '', $host);
	$script_name = $_SERVER['SCRIPT_NAME'] ?? '';
	$base_path = str_replace(basename($script_name), '', $script_name);
	$config['base_url'] = $protocol . '://' . $host . $base_path;
}

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;

$first_login_password_flag = strtolower(trim((string) (getenv('DOCLINC_FIRST_LOGIN_PASSWORD_CHANGE_ENABLED') ?: '')));
$first_login_password_environment = strtolower(trim((string) (getenv('DOCLINC_FIRST_LOGIN_PASSWORD_CHANGE_ENVIRONMENT') ?: '')));
$config['first_login_password_change_enabled'] = in_array($first_login_password_flag, array('1', 'true', 'yes', 'on'), TRUE)
	&& in_array($first_login_password_environment, array('staging', 'uat'), TRUE);

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$composer_autoload = FCPATH . 'vendor/autoload.php';
$config['composer_autoload'] = is_file($composer_autoload) ? $composer_autoload : FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$log_path = getenv('DOCLINC_LOG_PATH') ?: getenv('CI_LOG_PATH');
$config['log_path'] = $log_path ? rtrim($log_path, "/\\") . DIRECTORY_SEPARATOR : APPPATH . 'logs/';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$cache_path = getenv('DOCLINC_CACHE_PATH') ?: getenv('CI_CACHE_PATH');
$config['cache_path'] = $cache_path ? rtrim($cache_path, "/\\") . DIRECTORY_SEPARATOR : APPPATH . 'cache/';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$encryption_key_env = getenv('DOCLINC_ENCRYPTION_KEY');
if ($encryption_key_env === false || $encryption_key_env === '') {
	$encryption_key_env = isset($_SERVER['DOCLINC_ENCRYPTION_KEY'])
		? $_SERVER['DOCLINC_ENCRYPTION_KEY']
		: '';
}
$config['encryption_key'] = is_string($encryption_key_env) ? $encryption_key_env : '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/


// Guys yang ini nanti tinggal di komentar aja kalo mau jalanin du local
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'cilegon_bersatu_session';
// $config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$sess_save_path = getenv('DOCLINC_SESSION_PATH') ?: getenv('CI_SESSION_PATH');
$config['sess_save_path'] = $sess_save_path ? rtrim($sess_save_path, "/\\") . DIRECTORY_SEPARATOR : APPPATH . 'cache/sessions/';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;


// Terus hapus komentar yang ini ya
// $config['sess_driver'] = 'files';
// $config['sess_cookie_name'] = 'wms_session';
// $config['sess_expiration'] = 7200;
// $config['sess_save_path'] = NULL;
// $config['sess_match_ip'] = FALSE;
// $config['sess_time_to_update'] = 300;
// $config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$doclinc_cookie_secure_default = strtolower((string) parse_url((string) $config['base_url'], PHP_URL_SCHEME)) === 'https';
$doclinc_cookie_secure_env = strtolower(trim((string) (getenv('DOCLINC_COOKIE_SECURE') ?: '')));
if ($doclinc_cookie_secure_env === '') {
	$config['cookie_secure'] = $doclinc_cookie_secure_default;
} elseif (in_array($doclinc_cookie_secure_env, array('1', 'true', 'yes', 'on'), TRUE)) {
	$config['cookie_secure'] = TRUE;
} elseif (in_array($doclinc_cookie_secure_env, array('0', 'false', 'no', 'off'), TRUE)) {
	$config['cookie_secure'] = FALSE;
} else {
	$config['cookie_secure'] = $doclinc_cookie_secure_default;
}
$config['cookie_httponly'] = TRUE;
$config['cookie_samesite'] = 'Lax';

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'doclinc_csrf_token';
$config['csrf_cookie_name'] = 'doclinc_csrf_cookie';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = FALSE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

$config['google_maps_api_key'] = getenv('GOOGLE_MAPS_API_KEY') ?: '';
$config['firebase_enabled'] = filter_var(getenv('FIREBASE_ENABLED') ?: false, FILTER_VALIDATE_BOOLEAN);
$config['legacy_superapp_url'] = getenv('LEGACY_SUPERAPP_URL') ?: '';
$config['map_provider'] = getenv('MAP_PROVIDER') ?: 'none';
$config['mapbox_public_token'] = getenv('MAPBOX_PUBLIC_TOKEN') ?: '';
$reverse_geocoding_enabled_env = getenv('DOCLINC_REVERSE_GEOCODING_ENABLED');
$config['reverse_geocoding_enabled'] = $reverse_geocoding_enabled_env === false || $reverse_geocoding_enabled_env === ''
	? true
	: filter_var($reverse_geocoding_enabled_env, FILTER_VALIDATE_BOOLEAN);
$config['reverse_geocoding_endpoint'] = getenv('DOCLINC_REVERSE_GEOCODING_ENDPOINT') ?: 'https://nominatim.openstreetmap.org/reverse';
$config['reverse_geocoding_user_agent'] = getenv('DOCLINC_REVERSE_GEOCODING_USER_AGENT') ?: 'Doclinc/1.0 (+https://doclinc.sectunnel.online)';
$reverse_geocoding_allowed_hosts = getenv('DOCLINC_REVERSE_GEOCODING_ALLOWED_HOSTS') ?: 'nominatim.openstreetmap.org';
$config['reverse_geocoding_allowed_hosts'] = array_values(array_filter(array_map('trim', explode(',', strtolower($reverse_geocoding_allowed_hosts)))));
$reverse_geocoding_cache_path = getenv('DOCLINC_REVERSE_GEOCODING_CACHE_PATH');
if ($reverse_geocoding_cache_path === false || $reverse_geocoding_cache_path === '') {
	$reverse_geocoding_cache_path = rtrim(sys_get_temp_dir(), "/\\") . DIRECTORY_SEPARATOR
		. 'doclinc-reverse-geocoding-' . substr(hash('sha256', FCPATH), 0, 12);
}
$config['reverse_geocoding_cache_path'] = rtrim($reverse_geocoding_cache_path, "/\\") . DIRECTORY_SEPARATOR;
$routing_provider_env = getenv('ROUTING_PROVIDER');
if ($routing_provider_env === false || $routing_provider_env === '') {
	$routing_provider_env = isset($_SERVER['ROUTING_PROVIDER']) ? $_SERVER['ROUTING_PROVIDER'] : '';
}
$config['routing_provider'] = $routing_provider_env !== '' ? $routing_provider_env : 'none';

$valhalla_base_url_env = getenv('VALHALLA_BASE_URL');
if ($valhalla_base_url_env === false || $valhalla_base_url_env === '') {
	$valhalla_base_url_env = isset($_SERVER['VALHALLA_BASE_URL']) ? $_SERVER['VALHALLA_BASE_URL'] : '';
}
$config['valhalla_base_url'] = $valhalla_base_url_env !== '' ? $valhalla_base_url_env : '';

$routing_timeout_env = getenv('ROUTING_TIMEOUT_SECONDS');
if ($routing_timeout_env === false || $routing_timeout_env === '') {
	$routing_timeout_env = isset($_SERVER['ROUTING_TIMEOUT_SECONDS']) ? $_SERVER['ROUTING_TIMEOUT_SECONDS'] : '';
}
$config['routing_timeout_seconds'] = $routing_timeout_env !== '' ? $routing_timeout_env : 3;

$livekit_enabled_env = getenv('LIVEKIT_ENABLED');
if ($livekit_enabled_env === false || $livekit_enabled_env === '') {
	$livekit_enabled_env = isset($_SERVER['LIVEKIT_ENABLED']) ? $_SERVER['LIVEKIT_ENABLED'] : false;
}
$config['livekit_enabled'] = filter_var($livekit_enabled_env, FILTER_VALIDATE_BOOLEAN);

$livekit_ws_url_env = getenv('LIVEKIT_WS_URL');
if ($livekit_ws_url_env === false || $livekit_ws_url_env === '') {
	$livekit_ws_url_env = isset($_SERVER['LIVEKIT_WS_URL']) ? $_SERVER['LIVEKIT_WS_URL'] : '';
}
$config['livekit_ws_url'] = $livekit_ws_url_env !== '' ? $livekit_ws_url_env : '';

$livekit_api_key_env = getenv('LIVEKIT_API_KEY');
if ($livekit_api_key_env === false || $livekit_api_key_env === '') {
	$livekit_api_key_env = isset($_SERVER['LIVEKIT_API_KEY']) ? $_SERVER['LIVEKIT_API_KEY'] : '';
}
$config['livekit_api_key'] = $livekit_api_key_env !== '' ? $livekit_api_key_env : '';

$livekit_api_secret_env = getenv('LIVEKIT_API_SECRET');
if ($livekit_api_secret_env === false || $livekit_api_secret_env === '') {
	$livekit_api_secret_env = isset($_SERVER['LIVEKIT_API_SECRET']) ? $_SERVER['LIVEKIT_API_SECRET'] : '';
}
$config['livekit_api_secret'] = $livekit_api_secret_env !== '' ? $livekit_api_secret_env : '';

$livekit_token_ttl_env = getenv('LIVEKIT_TOKEN_TTL_SECONDS');
if ($livekit_token_ttl_env === false || $livekit_token_ttl_env === '') {
	$livekit_token_ttl_env = isset($_SERVER['LIVEKIT_TOKEN_TTL_SECONDS']) ? $_SERVER['LIVEKIT_TOKEN_TTL_SECONDS'] : '';
}
$config['livekit_token_ttl_seconds'] = is_numeric($livekit_token_ttl_env) ? (int) $livekit_token_ttl_env : 3600;

$config['api_access_token'] = getenv('API_ACCESS_TOKEN') ?: '';

$clinical_suggestions_enabled_env = getenv('DOCLINC_CLINICAL_SUGGESTIONS_ENABLED');
if ($clinical_suggestions_enabled_env === false || $clinical_suggestions_enabled_env === '') {
	$clinical_suggestions_enabled_env = isset($_SERVER['DOCLINC_CLINICAL_SUGGESTIONS_ENABLED'])
		? $_SERVER['DOCLINC_CLINICAL_SUGGESTIONS_ENABLED']
		: false;
}
$clinical_suggestions_environment_env = getenv('DOCLINC_CLINICAL_SUGGESTIONS_ENVIRONMENT');
if ($clinical_suggestions_environment_env === false || $clinical_suggestions_environment_env === '') {
	$clinical_suggestions_environment_env = isset($_SERVER['DOCLINC_CLINICAL_SUGGESTIONS_ENVIRONMENT'])
		? $_SERVER['DOCLINC_CLINICAL_SUGGESTIONS_ENVIRONMENT']
		: '';
}
require_once APPPATH . 'libraries/Clinical_suggestion_feature.php';
$clinical_suggestions_feature = Clinical_suggestion_feature::resolve(
	$clinical_suggestions_enabled_env,
	$clinical_suggestions_environment_env
);
$config['clinical_suggestions_environment'] = $clinical_suggestions_feature['environment'];
$config['clinical_suggestions_enabled'] = $clinical_suggestions_feature['enabled'];

$realtime_client_enabled_env = getenv('DOCLINC_REALTIME_CLIENT_ENABLED');
if ($realtime_client_enabled_env === false || $realtime_client_enabled_env === '') {
	$realtime_client_enabled_env = isset($_SERVER['DOCLINC_REALTIME_CLIENT_ENABLED'])
		? $_SERVER['DOCLINC_REALTIME_CLIENT_ENABLED']
		: null;
}
$realtime_client_environment_env = getenv('DOCLINC_REALTIME_CLIENT_ENVIRONMENT');
if ($realtime_client_environment_env === false || $realtime_client_environment_env === '') {
	$realtime_client_environment_env = isset($_SERVER['DOCLINC_REALTIME_CLIENT_ENVIRONMENT'])
		? $_SERVER['DOCLINC_REALTIME_CLIENT_ENVIRONMENT']
		: '';
}
$realtime_client_runtime_environment_env = getenv('DOCLINC_REALTIME_CLIENT_RUNTIME_ENVIRONMENT');
if ($realtime_client_runtime_environment_env === false || $realtime_client_runtime_environment_env === '') {
	$realtime_client_runtime_environment_env = isset($_SERVER['DOCLINC_REALTIME_CLIENT_RUNTIME_ENVIRONMENT'])
		? $_SERVER['DOCLINC_REALTIME_CLIENT_RUNTIME_ENVIRONMENT']
		: '';
}
$nakes_credential_enforcement_enabled_env = getenv('DOCLINC_NAKES_CREDENTIAL_ENFORCEMENT_ENABLED');
if ($nakes_credential_enforcement_enabled_env === false || $nakes_credential_enforcement_enabled_env === '') {
	$nakes_credential_enforcement_enabled_env = $_SERVER['DOCLINC_NAKES_CREDENTIAL_ENFORCEMENT_ENABLED'] ?? null;
}
$nakes_credential_enforcement_environment_env = getenv('DOCLINC_NAKES_CREDENTIAL_ENFORCEMENT_ENVIRONMENT');
if ($nakes_credential_enforcement_environment_env === false || $nakes_credential_enforcement_environment_env === '') {
	$nakes_credential_enforcement_environment_env = $_SERVER['DOCLINC_NAKES_CREDENTIAL_ENFORCEMENT_ENVIRONMENT'] ?? '';
}
require_once APPPATH . 'libraries/Doclinc_feature_flags.php';
$nakes_credential_enforcement_feature = Doclinc_feature_flags::resolve(
	$nakes_credential_enforcement_enabled_env,
	$nakes_credential_enforcement_environment_env,
	$realtime_client_runtime_environment_env
);
$config['nakes_credential_enforcement_enabled'] = $nakes_credential_enforcement_feature['enabled'];
$config['nakes_credential_enforcement_environment'] = $nakes_credential_enforcement_feature['environment'];
$config['nakes_credential_enforcement_feature_reason'] = $nakes_credential_enforcement_feature['reason'];
$single_active_session_enabled_env = getenv('DOCLINC_SINGLE_ACTIVE_SESSION_ENABLED');
if ($single_active_session_enabled_env === false || $single_active_session_enabled_env === '') {
	$single_active_session_enabled_env = $_SERVER['DOCLINC_SINGLE_ACTIVE_SESSION_ENABLED'] ?? null;
}
$single_active_session_environment_env = getenv('DOCLINC_SINGLE_ACTIVE_SESSION_ENVIRONMENT');
if ($single_active_session_environment_env === false || $single_active_session_environment_env === '') {
	$single_active_session_environment_env = $_SERVER['DOCLINC_SINGLE_ACTIVE_SESSION_ENVIRONMENT'] ?? '';
}
$single_active_session_feature = Doclinc_feature_flags::resolve(
	$single_active_session_enabled_env,
	$single_active_session_environment_env,
	$realtime_client_runtime_environment_env
);
$config['single_active_session_enabled'] = $single_active_session_feature['enabled'];
$config['single_active_session_environment'] = $single_active_session_feature['environment'];
$config['single_active_session_feature_reason'] = $single_active_session_feature['reason'];

$care_team_workflow_enabled_env = getenv('DOCLINC_CARE_TEAM_WORKFLOW_ENABLED');
if ($care_team_workflow_enabled_env === false || $care_team_workflow_enabled_env === '') {
	$care_team_workflow_enabled_env = $_SERVER['DOCLINC_CARE_TEAM_WORKFLOW_ENABLED'] ?? null;
}
$care_team_workflow_environment_env = getenv('DOCLINC_CARE_TEAM_WORKFLOW_ENVIRONMENT');
if ($care_team_workflow_environment_env === false || $care_team_workflow_environment_env === '') {
	$care_team_workflow_environment_env = $_SERVER['DOCLINC_CARE_TEAM_WORKFLOW_ENVIRONMENT'] ?? '';
}
$care_team_workflow_feature = Doclinc_feature_flags::resolve(
	$care_team_workflow_enabled_env,
	$care_team_workflow_environment_env,
	$realtime_client_runtime_environment_env
);
$config['care_team_workflow_enabled'] = $care_team_workflow_feature['enabled'];
$config['care_team_workflow_environment'] = $care_team_workflow_feature['environment'];
$config['care_team_workflow_feature_reason'] = $care_team_workflow_feature['reason'];
$realtime_public_websocket_url_env = getenv('DOCLINC_REALTIME_PUBLIC_WEBSOCKET_URL');
if ($realtime_public_websocket_url_env === false || $realtime_public_websocket_url_env === '') {
	$realtime_public_websocket_url_env = isset($_SERVER['DOCLINC_REALTIME_PUBLIC_WEBSOCKET_URL'])
		? $_SERVER['DOCLINC_REALTIME_PUBLIC_WEBSOCKET_URL']
		: '';
}
$realtime_token_secret_env = getenv('DOCLINC_REALTIME_CLIENT_TOKEN_HMAC_SECRET');
if ($realtime_token_secret_env === false || $realtime_token_secret_env === '') {
	$realtime_token_secret_env = isset($_SERVER['DOCLINC_REALTIME_CLIENT_TOKEN_HMAC_SECRET'])
		? $_SERVER['DOCLINC_REALTIME_CLIENT_TOKEN_HMAC_SECRET']
		: '';
}
$realtime_token_ttl_env = getenv('DOCLINC_REALTIME_CLIENT_TOKEN_TTL_SECONDS');
if ($realtime_token_ttl_env === false || $realtime_token_ttl_env === '') {
	$realtime_token_ttl_env = isset($_SERVER['DOCLINC_REALTIME_CLIENT_TOKEN_TTL_SECONDS'])
		? $_SERVER['DOCLINC_REALTIME_CLIENT_TOKEN_TTL_SECONDS']
		: '';
}

require_once APPPATH . 'libraries/Realtime_access_feature.php';
$realtime_client_feature = Realtime_access_feature::resolve(
	$realtime_client_enabled_env,
	$realtime_client_environment_env,
	$realtime_client_runtime_environment_env,
	$realtime_public_websocket_url_env
);
$config['realtime_client_enabled'] = $realtime_client_feature['enabled'];
$config['realtime_client_environment'] = $realtime_client_feature['environment'];
$config['realtime_client_websocket_url'] = $realtime_client_feature['websocket_url'];
$config['realtime_client_feature_reason'] = $realtime_client_feature['reason'];
$config['realtime_client_token_hmac_secret'] = is_string($realtime_token_secret_env) ? $realtime_token_secret_env : '';
$config['realtime_client_token_ttl_seconds'] = ctype_digit((string) $realtime_token_ttl_env)
	? (int) $realtime_token_ttl_env
	: 120;

$realtime_notifications_enabled_env = getenv('DOCLINC_REALTIME_NOTIFICATIONS_ENABLED');
if ($realtime_notifications_enabled_env === false || $realtime_notifications_enabled_env === '') {
	$realtime_notifications_enabled_env = isset($_SERVER['DOCLINC_REALTIME_NOTIFICATIONS_ENABLED'])
		? $_SERVER['DOCLINC_REALTIME_NOTIFICATIONS_ENABLED']
		: null;
}
$realtime_notifications_environment_env = getenv('DOCLINC_REALTIME_NOTIFICATIONS_ENVIRONMENT');
if ($realtime_notifications_environment_env === false || $realtime_notifications_environment_env === '') {
	$realtime_notifications_environment_env = isset($_SERVER['DOCLINC_REALTIME_NOTIFICATIONS_ENVIRONMENT'])
		? $_SERVER['DOCLINC_REALTIME_NOTIFICATIONS_ENVIRONMENT']
		: '';
}
require_once APPPATH . 'libraries/Realtime_notification_feature.php';
$realtime_notifications_feature = Realtime_notification_feature::resolve(
	$realtime_notifications_enabled_env,
	$realtime_notifications_environment_env,
	$realtime_client_runtime_environment_env,
	$config['realtime_client_enabled']
);
$config['realtime_notifications_enabled'] = $realtime_notifications_feature['enabled'];
$config['realtime_notifications_environment'] = $realtime_notifications_feature['environment'];
$config['realtime_notifications_feature_reason'] = $realtime_notifications_feature['reason'];

$realtime_requests_enabled_env = getenv('DOCLINC_REALTIME_REQUESTS_ENABLED');
if ($realtime_requests_enabled_env === false || $realtime_requests_enabled_env === '') {
	$realtime_requests_enabled_env = $_SERVER['DOCLINC_REALTIME_REQUESTS_ENABLED'] ?? null;
}
$realtime_requests_environment_env = getenv('DOCLINC_REALTIME_REQUESTS_ENVIRONMENT');
if ($realtime_requests_environment_env === false || $realtime_requests_environment_env === '') {
	$realtime_requests_environment_env = $_SERVER['DOCLINC_REALTIME_REQUESTS_ENVIRONMENT'] ?? '';
}
require_once APPPATH . 'libraries/Realtime_request_feature.php';
$realtime_requests_feature = Realtime_request_feature::resolve(
	$realtime_requests_enabled_env,
	$realtime_requests_environment_env,
	$realtime_client_runtime_environment_env,
	$config['realtime_client_enabled']
);
$config['realtime_requests_enabled'] = $realtime_requests_feature['enabled'];
$config['realtime_requests_environment'] = $realtime_requests_feature['environment'];
$config['realtime_requests_feature_reason'] = $realtime_requests_feature['reason'];

$visit_proof_required_env = getenv('DOCLINC_VISIT_PROOF_REQUIRED');
if ($visit_proof_required_env === false || $visit_proof_required_env === '') {
	$visit_proof_required_env = $_SERVER['DOCLINC_VISIT_PROOF_REQUIRED'] ?? null;
}
$visit_proof_environment_env = getenv('DOCLINC_VISIT_PROOF_ENVIRONMENT');
if ($visit_proof_environment_env === false || $visit_proof_environment_env === '') {
	$visit_proof_environment_env = $_SERVER['DOCLINC_VISIT_PROOF_ENVIRONMENT'] ?? '';
}
require_once APPPATH . 'libraries/Doclinc_feature_flags.php';
$visit_proof_feature = Doclinc_feature_flags::resolve(
	$visit_proof_required_env,
	$visit_proof_environment_env,
	$realtime_client_runtime_environment_env
);
$config['visit_proof_required'] = $visit_proof_feature['enabled'];
$config['visit_proof_environment'] = $visit_proof_feature['environment'];
$config['visit_proof_feature_reason'] = $visit_proof_feature['reason'];
$config['visit_proof_max_size_kb'] = 5120;
$config['visit_proof_location_max_age_seconds'] = 120;
$visit_proof_storage_path_env = getenv('DOCLINC_VISIT_PROOF_STORAGE_PATH');
if ($visit_proof_storage_path_env === false || $visit_proof_storage_path_env === '') {
	$visit_proof_storage_path_env = $_SERVER['DOCLINC_VISIT_PROOF_STORAGE_PATH'] ?? '';
}
$config['visit_proof_storage_path'] = is_string($visit_proof_storage_path_env)
	? trim($visit_proof_storage_path_env)
	: '';

$chat_attachment_storage_path_env = getenv('DOCLINC_CHAT_ATTACHMENT_STORAGE_PATH');
if ($chat_attachment_storage_path_env === false || $chat_attachment_storage_path_env === '') {
	$chat_attachment_storage_path_env = $_SERVER['DOCLINC_CHAT_ATTACHMENT_STORAGE_PATH'] ?? '';
}
if (!is_string($chat_attachment_storage_path_env) || trim($chat_attachment_storage_path_env) === '') {
	$chat_attachment_storage_path_env = dirname(dirname(rtrim(FCPATH, '/\\')))
		. DIRECTORY_SEPARATOR . 'private' . DIRECTORY_SEPARATOR . 'chat-attachments';
}
$config['chat_attachment_storage_path'] = trim($chat_attachment_storage_path_env);
$config['chat_attachment_max_size_kb'] = 4096;

$profile_image_storage_path_env = getenv('DOCLINC_PROFILE_IMAGE_STORAGE_PATH');
if ($profile_image_storage_path_env === false || $profile_image_storage_path_env === '') {
	$profile_image_storage_path_env = $_SERVER['DOCLINC_PROFILE_IMAGE_STORAGE_PATH'] ?? '';
}
if (!is_string($profile_image_storage_path_env) || trim($profile_image_storage_path_env) === '') {
	$profile_image_storage_path_env = dirname(dirname(rtrim(FCPATH, '/\\')))
		. DIRECTORY_SEPARATOR . 'private' . DIRECTORY_SEPARATOR . 'profile-images';
}
$config['profile_image_storage_path'] = trim($profile_image_storage_path_env);
$config['profile_image_max_size_kb'] = 5120;

$role_prerequisites_enabled_env = getenv('DOCLINC_ROLE_PREREQUISITES_ENABLED');
if ($role_prerequisites_enabled_env === false || $role_prerequisites_enabled_env === '') {
	$role_prerequisites_enabled_env = $_SERVER['DOCLINC_ROLE_PREREQUISITES_ENABLED'] ?? null;
}
$role_prerequisites_environment_env = getenv('DOCLINC_ROLE_PREREQUISITES_ENVIRONMENT');
if ($role_prerequisites_environment_env === false || $role_prerequisites_environment_env === '') {
	$role_prerequisites_environment_env = $_SERVER['DOCLINC_ROLE_PREREQUISITES_ENVIRONMENT'] ?? '';
}
$role_prerequisites_feature = Doclinc_feature_flags::resolve(
	$role_prerequisites_enabled_env,
	$role_prerequisites_environment_env,
	$realtime_client_runtime_environment_env
);
$config['role_prerequisites_enabled'] = $role_prerequisites_feature['enabled'];
$config['role_prerequisites_environment'] = $role_prerequisites_feature['environment'];
$config['role_prerequisites_feature_reason'] = $role_prerequisites_feature['reason'];

$additional_diagnoses_enabled_env = getenv('DOCLINC_ADDITIONAL_DIAGNOSES_ENABLED');
if ($additional_diagnoses_enabled_env === false || $additional_diagnoses_enabled_env === '') {
	$additional_diagnoses_enabled_env = $_SERVER['DOCLINC_ADDITIONAL_DIAGNOSES_ENABLED'] ?? null;
}
$additional_diagnoses_environment_env = getenv('DOCLINC_ADDITIONAL_DIAGNOSES_ENVIRONMENT');
if ($additional_diagnoses_environment_env === false || $additional_diagnoses_environment_env === '') {
	$additional_diagnoses_environment_env = $_SERVER['DOCLINC_ADDITIONAL_DIAGNOSES_ENVIRONMENT'] ?? '';
}
$additional_diagnoses_feature = Doclinc_feature_flags::resolve(
	$additional_diagnoses_enabled_env,
	$additional_diagnoses_environment_env,
	$realtime_client_runtime_environment_env
);
$config['additional_diagnoses_enabled'] = $additional_diagnoses_feature['enabled'];
$config['additional_diagnoses_environment'] = $additional_diagnoses_feature['environment'];
$config['additional_diagnoses_feature_reason'] = $additional_diagnoses_feature['reason'];

$nakes_presence_enabled_env = getenv('DOCLINC_NAKES_PRESENCE_ENABLED');
if ($nakes_presence_enabled_env === false || $nakes_presence_enabled_env === '') {
	$nakes_presence_enabled_env = $_SERVER['DOCLINC_NAKES_PRESENCE_ENABLED'] ?? null;
}
$nakes_presence_environment_env = getenv('DOCLINC_NAKES_PRESENCE_ENVIRONMENT');
if ($nakes_presence_environment_env === false || $nakes_presence_environment_env === '') {
	$nakes_presence_environment_env = $_SERVER['DOCLINC_NAKES_PRESENCE_ENVIRONMENT'] ?? '';
}
$nakes_presence_feature = Doclinc_feature_flags::resolve(
	$nakes_presence_enabled_env,
	$nakes_presence_environment_env,
	$realtime_client_runtime_environment_env
);
$config['nakes_presence_enabled'] = $nakes_presence_feature['enabled'];
$config['nakes_presence_environment'] = $nakes_presence_feature['environment'];
$config['nakes_presence_feature_reason'] = $nakes_presence_feature['reason'];
$config['nakes_presence_heartbeat_seconds'] = 30;
$config['nakes_presence_write_throttle_seconds'] = 45;
$config['nakes_presence_online_timeout_seconds'] = 90;

$puskesmas_operations_enabled_env = getenv('DOCLINC_PUSKESMAS_OPERATIONS_ENABLED');
if ($puskesmas_operations_enabled_env === false || $puskesmas_operations_enabled_env === '') {
	$puskesmas_operations_enabled_env = $_SERVER['DOCLINC_PUSKESMAS_OPERATIONS_ENABLED'] ?? null;
}
$puskesmas_operations_environment_env = getenv('DOCLINC_PUSKESMAS_OPERATIONS_ENVIRONMENT');
if ($puskesmas_operations_environment_env === false || $puskesmas_operations_environment_env === '') {
	$puskesmas_operations_environment_env = $_SERVER['DOCLINC_PUSKESMAS_OPERATIONS_ENVIRONMENT'] ?? '';
}
$puskesmas_operations_feature = Doclinc_feature_flags::resolve(
	$puskesmas_operations_enabled_env,
	$puskesmas_operations_environment_env,
	$realtime_client_runtime_environment_env
);
$config['puskesmas_operations_enabled'] = $puskesmas_operations_feature['enabled']
	&& $config['nakes_presence_enabled'] === true;
$config['puskesmas_operations_environment'] = $puskesmas_operations_feature['environment'];
$config['puskesmas_operations_feature_reason'] = !$puskesmas_operations_feature['enabled']
	? $puskesmas_operations_feature['reason']
	: ($config['nakes_presence_enabled'] !== true ? 'nakes_presence_required' : 'enabled');
$config['puskesmas_operations_poll_seconds'] = 30;
$config['puskesmas_operations_staff_limit'] = 200;
$config['puskesmas_operations_request_limit'] = 200;
