<?php

$database = getenv('DOCLINC_NAKES_RESET_DB_NAME') ?: '';
$resetUser = getenv('DOCLINC_NAKES_RESET_DB_USER') ?: '';
$resetPassword = getenv('DOCLINC_NAKES_RESET_DB_PASSWORD');
$sourcePath = getenv('DOCLINC_NAKES_TEST_XLSX') ?: '';
if (preg_match('/(?:^|[_-])test(?:$|[_-])/', strtolower($database)) !== 1 || $sourcePath === '' || !is_string($resetPassword) || $resetPassword === '') {
	fwrite(STDERR,"NAKES_RESET_INTEGRATION=FAIL\nSAFE_ERROR_CODE=disposable_test_required\n");exit(2);
}
require_once dirname(__DIR__) . '/lib/NakesSource.php';
function integration_expect($condition,$code){if(!$condition)throw new RuntimeException($code);}
function integration_cli(array $args){$root=dirname(__DIR__,3);$p=proc_open(array_merge(array(PHP_BINARY,$root.'/tools/nakes_import/nakes_import.php'),$args),array(1=>array('pipe','w'),2=>array('pipe','w')),$pipes,null,null,array('bypass_shell'=>true));if(!is_resource($p))return array(255,'','');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return array(proc_close($p),$out,$err);}
function insert_many(mysqli $db,$sql,$count,callable $binder){$stmt=$db->prepare($sql);for($i=1;$i<=$count;$i++)$binder($stmt,$i);$stmt->close();}

$stage='connection';
try{
	mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);
	$host=getenv('DOCLINC_NAKES_RESET_DB_HOST')?:'localhost';$port=(int)(getenv('DOCLINC_NAKES_RESET_DB_PORT')?:3306);
	$admin=new mysqli($host,getenv('DOCLINC_NAKES_TEST_ADMIN_DB_USER')?:'root',getenv('DOCLINC_NAKES_TEST_ADMIN_DB_PASSWORD'),$database,$port);$admin->set_charset('utf8mb4');
	$stage='fixture';
	$tables=array('rating','puskesmas','locations','admin_notification_reads','call_sessions','consultation_messages','notifications','request_events','request_staff_assignments','terapi','konsultasi','medicalrecords','requests','puskesmas_staff','m_dokter','audit_logs','clinical_suggestion_aliases','clinical_suggestion_terms','clinical_suggestion_import_batches','clinical_schema_migrations','feeds','m_puskesmas','users');
	foreach($tables as $table)$admin->query("DROP TABLE IF EXISTS `$table`");
	$admin->query("CREATE TABLE users(userId int(11) NOT NULL AUTO_INCREMENT,nama varchar(100) NOT NULL,email varchar(100) NOT NULL,username varchar(100) NULL,password varchar(100) NOT NULL,role enum('admin','dokter','warga','') NOT NULL,status enum('aktif','nonaktif') NULL DEFAULT 'aktif',must_change_password tinyint(1) NOT NULL DEFAULT 0,password_changed_at datetime NULL,remark varchar(100) NULL,no_hp varchar(50) NULL,foto varchar(255) NULL,created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(userId),UNIQUE KEY(email),UNIQUE KEY(username)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE m_puskesmas(kode_pkm varchar(100) NOT NULL,nama_puskesmas varchar(150) NOT NULL,status enum('aktif','nonaktif') NOT NULL DEFAULT 'aktif',created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(kode_pkm)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE puskesmas_staff(staff_id int(11) NOT NULL AUTO_INCREMENT,kode_pkm varchar(100) NOT NULL,nama varchar(150) NOT NULL,no_hp varchar(50) NULL,profesi varchar(100) NULL,penugasan varchar(150) NULL,nomor_sip varchar(100) NULL,user_id int(11) NULL,status enum('aktif','nonaktif') NOT NULL DEFAULT 'aktif',created_at datetime NOT NULL,updated_at datetime NULL,created_by_user_id int(11) NULL,updated_by_user_id int(11) NULL,PRIMARY KEY(staff_id),KEY(user_id),KEY(kode_pkm)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE requests(request_id int(11) NOT NULL AUTO_INCREMENT,user_id int(11) NOT NULL,dokter_id int(11) NULL,request_status enum('Pending','Accepted','Completed','Cancelled') DEFAULT 'Pending',assigned_puskesmas_code varchar(100) NULL,file varchar(255) NULL,PRIMARY KEY(request_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE medicalrecords(record_id int(11) NOT NULL AUTO_INCREMENT,request_id int(11) NOT NULL,diagnosis text NULL,treatment text NULL,recommendations text NULL,created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(record_id),KEY(request_id),CONSTRAINT medicalrecords_ibfk_1 FOREIGN KEY(request_id) REFERENCES requests(request_id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB");
	$admin->query("CREATE TABLE konsultasi(konsul_id int(11) NOT NULL AUTO_INCREMENT,request_id int(11) NOT NULL,diagnosa text NULL,saran text NULL,foto varchar(255) NULL,PRIMARY KEY(konsul_id),UNIQUE KEY(request_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE terapi(terapi_id int(11) NOT NULL AUTO_INCREMENT,konsul_id int(11) NOT NULL,terapi varchar(255) NULL,PRIMARY KEY(terapi_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE request_staff_assignments(assignment_id int(11) NOT NULL AUTO_INCREMENT,request_id int(11) NOT NULL,staff_id int(11) NOT NULL,kode_pkm varchar(100) NOT NULL,assigned_by_user_id int(11) NOT NULL,status varchar(20) NOT NULL,assigned_at datetime NOT NULL,PRIMARY KEY(assignment_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE request_events(event_id int(11) NOT NULL AUTO_INCREMENT,request_id int(11) NOT NULL,event_type varchar(64) NOT NULL,actor_user_id int(11) NULL,actor_staff_id int(11) NULL,created_at datetime NOT NULL,PRIMARY KEY(event_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE consultation_messages(message_id int(11) NOT NULL AUTO_INCREMENT,request_id int(11) NOT NULL,sender_user_id int(11) NOT NULL,attachment_path varchar(255) NULL,PRIMARY KEY(message_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE call_sessions(call_id bigint unsigned NOT NULL AUTO_INCREMENT,request_id int(11) NOT NULL,caller_user_id int(11) NOT NULL,callee_user_id int(11) NOT NULL,PRIMARY KEY(call_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE notifications(notification_id int(11) NOT NULL AUTO_INCREMENT,recipient_user_id int(11) NULL,recipient_puskesmas_code varchar(100) NULL,actor_user_id int(11) NULL,entity_type varchar(64) NOT NULL,entity_id varchar(64) NOT NULL,PRIMARY KEY(notification_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE admin_notification_reads(user_id int(11) NOT NULL,last_seen_event_id int(11) NULL,PRIMARY KEY(user_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE locations(location_id int(11) NOT NULL AUTO_INCREMENT,id_user int(11) NOT NULL,location text NULL,PRIMARY KEY(location_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE m_dokter(professional_id int(11) NOT NULL AUTO_INCREMENT,name varchar(50) NOT NULL,phone varchar(20) NOT NULL,email varchar(100) NOT NULL,password varchar(255) NOT NULL,PRIMARY KEY(professional_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE audit_logs(id bigint unsigned NOT NULL AUTO_INCREMENT,actor_user_id int(11) NULL,action varchar(100) NOT NULL,entity_type varchar(100) NULL,entity_id varchar(100) NULL,ip_address varchar(45) NULL,user_agent varchar(255) NULL,metadata_json text NULL,created_at datetime NOT NULL,PRIMARY KEY(id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE feeds(feedId int(11) NOT NULL AUTO_INCREMENT,subject varchar(255) NOT NULL,PRIMARY KEY(feedId)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE clinical_suggestion_import_batches(batch_id bigint unsigned NOT NULL AUTO_INCREMENT,batch_reference varchar(100),PRIMARY KEY(batch_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE clinical_suggestion_terms(term_id bigint unsigned NOT NULL AUTO_INCREMENT,batch_id bigint unsigned,label varchar(100),PRIMARY KEY(term_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE clinical_suggestion_aliases(alias_id bigint unsigned NOT NULL AUTO_INCREMENT,term_id bigint unsigned,label varchar(100),PRIMARY KEY(alias_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE clinical_schema_migrations(migration_id varchar(100) NOT NULL,state varchar(20) NOT NULL,PRIMARY KEY(migration_id)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE puskesmas(id_puskesmas int(11) NOT NULL AUTO_INCREMENT,kode_pkm varchar(100),PRIMARY KEY(id_puskesmas)) ENGINE=InnoDB");
	$admin->query("CREATE TABLE rating(rating_id int(11) NOT NULL AUTO_INCREMENT,id_user int(11),id_dokter int(11),rating int(11),PRIMARY KEY(rating_id)) ENGINE=InnoDB");

	$codes=DoclincNakesSource::CODES;$uniqueCodes=array_values(array_unique($codes));sort($uniqueCodes);$stmt=$admin->prepare("INSERT INTO m_puskesmas(kode_pkm,nama_puskesmas,status) VALUES (?,?,'aktif')");foreach($uniqueCodes as $index=>$code){$name='PKM-TEST-'.($index+1);$stmt->bind_param('ss',$code,$name);$stmt->execute();}$stmt->close();$admin->query("INSERT INTO m_puskesmas VALUES('DEFAULT','PKM-DEFAULT-TEST','nonaktif',NOW())");$admin->query("INSERT INTO puskesmas(kode_pkm) VALUES('DEFAULT')");
	$existingPassword=implode('',array('Existing','-','Account','!','42'));$existingHash=password_hash($existingPassword,PASSWORD_DEFAULT);$existingPassword=null;$userStmt=$admin->prepare('INSERT INTO users(userId,nama,email,username,password,role,status,remark,no_hp) VALUES(?,?,?,?,?,?,?,?,?)');
	for($id=1;$id<=27;$id++){if($id===1){$role='admin';$status='aktif';$remark=null;}elseif($id<=10){$role='dokter';$status='aktif';$remark=$uniqueCodes[$id-2];}elseif($id===11){$role='dokter';$status='aktif';$remark=$uniqueCodes[0];}elseif($id===12){$role='dokter';$status='aktif';$remark=$uniqueCodes[1];}elseif($id<=16){$role='dokter';$status='nonaktif';$remark=$uniqueCodes[($id-13)%9];}else{$role='warga';$status='aktif';$remark=null;}$name='TEST-ACCOUNT-'.$id;$email='test-account-'.$id.'@example.invalid';$username='test-account-'.$id;$phone=null;$userStmt->bind_param('issssssss',$id,$name,$email,$username,$existingHash,$role,$status,$remark,$phone);$userStmt->execute();}$userStmt->close();
	$staffStmt=$admin->prepare("INSERT INTO puskesmas_staff(kode_pkm,nama,no_hp,profesi,penugasan,nomor_sip,user_id,status,created_at,updated_at,created_by_user_id) VALUES (? ,?,NULL,'Dokter',NULL,NULL,?,'aktif',NOW(),NOW(),1)");for($i=1;$i<=8;$i++){$code=$uniqueCodes[($i-1)%9];$name='TEST-STAFF-'.$i;$linked=$i===1?11:null;$staffStmt->bind_param('ssi',$code,$name,$linked);$staffStmt->execute();}$staffStmt->close();
	$legacyStmt=$admin->prepare('INSERT INTO m_dokter(professional_id,name,phone,email,password) VALUES (?,?,?,?,?)');for($i=1;$i<=8;$i++){$legacyName='LEGACY-'.$i;$legacyPhone='legacy-'.$i;$legacyEmail='legacy-'.$i.'@example.invalid';$legacyStmt->bind_param('issss',$i,$legacyName,$legacyPhone,$legacyEmail,$existingHash);$legacyStmt->execute();}$legacyStmt->close();
	for($i=1;$i<=37;$i++){$uid=17+(($i-1)%11);$admin->query("INSERT INTO requests(request_id,user_id,dokter_id,request_status,assigned_puskesmas_code,file) VALUES($i,$uid,11,'Completed','{$uniqueCodes[0]}',NULL)");}
	for($i=1;$i<=19;$i++)$admin->query("INSERT INTO medicalrecords(request_id,diagnosis) VALUES($i,'TEST')");for($i=1;$i<=18;$i++)$admin->query("INSERT INTO konsultasi(request_id,diagnosa,saran) VALUES($i,'TEST','TEST')");for($i=1;$i<=11;$i++)$admin->query("INSERT INTO terapi(konsul_id,terapi) VALUES($i,'TEST')");
	for($i=1;$i<=14;$i++)$admin->query("INSERT INTO request_staff_assignments(request_id,staff_id,kode_pkm,assigned_by_user_id,status,assigned_at) VALUES($i,1,'{$uniqueCodes[0]}',2,'aktif',NOW())");for($i=1;$i<=49;$i++)$admin->query("INSERT INTO request_events(request_id,event_type,actor_user_id,actor_staff_id,created_at) VALUES(".(1+(($i-1)%37)).",'test_event',2,1,NOW())");for($i=1;$i<=39;$i++)$admin->query("INSERT INTO consultation_messages(request_id,sender_user_id) VALUES(".(1+(($i-1)%37)).",17)");for($i=1;$i<=12;$i++)$admin->query("INSERT INTO call_sessions(request_id,caller_user_id,callee_user_id) VALUES($i,17,11)");for($i=1;$i<=104;$i++)$admin->query("INSERT INTO notifications(recipient_user_id,recipient_puskesmas_code,actor_user_id,entity_type,entity_id) VALUES(17,'{$uniqueCodes[0]}',2,'request','".(1+(($i-1)%37))."')");
	for($i=1;$i<=5;$i++)$admin->query("INSERT INTO locations(id_user,location) VALUES(".(16+$i).",'TEST')");for($i=1;$i<=3;$i++)$admin->query("INSERT INTO feeds(subject) VALUES('TEST-FEED-$i')");for($i=1;$i<=3;$i++)$admin->query("INSERT INTO rating(id_user,id_dokter,rating) VALUES(17,11,5)");
	$audit=$admin->prepare('INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata_json,created_at) VALUES(?,?,?,?,?,NOW())');for($i=1;$i<=353;$i++){if($i===1){$actor=1;$action='login_success';$type='auth';$entity='1';$meta='{"role":"admin"}';}elseif($i<=300){$actor=null;$action='login_failed';$type='auth';$entity=null;$meta='{"area":"public"}';}elseif($i<=320){$actor=1;$action='request_event';$type='request';$entity=(string)(1+(($i-301)%37));$meta='{"target":"accept"}';}else{$actor=17;$action='login_success';$type='auth';$entity='17';$meta='{"role":"warga"}';}$audit->bind_param('issss',$actor,$action,$type,$entity,$meta);$audit->execute();}$audit->close();
	$admin->query("INSERT INTO clinical_suggestion_import_batches(batch_reference) VALUES('test-preserved')");$term=$admin->prepare("INSERT INTO clinical_suggestion_terms(batch_id,label) VALUES(1,?)");for($i=1;$i<=11450;$i++){$label='TERM-'.$i;$term->bind_param('s',$label);$term->execute();}$term->close();$alias=$admin->prepare("INSERT INTO clinical_suggestion_aliases(term_id,label) VALUES(?,?)");for($i=1;$i<=701;$i++){$termId=$i;$label='ALIAS-'.$i;$alias->bind_param('is',$termId,$label);$alias->execute();}$alias->close();for($i=1;$i<=6;$i++)$admin->query("INSERT INTO clinical_schema_migrations VALUES('TEST-MIGRATION-$i','applied')");

	$stage='grants';$safeUser=preg_replace('/[^a-zA-Z0-9_]/','',$resetUser);integration_expect($safeUser===$resetUser&&$safeUser!=='','reset_user');$escapedPass=$admin->real_escape_string($resetPassword);$admin->query("DROP USER IF EXISTS `$safeUser`@'%'");$admin->query("CREATE USER `$safeUser`@'%' IDENTIFIED BY '$escapedPass'");
	$selectTables=array('admin_notification_reads','audit_logs','call_sessions','consultation_messages','feeds','konsultasi','medicalrecords','m_dokter','m_puskesmas','notifications','puskesmas_staff','requests','request_events','request_staff_assignments','terapi','users','locations','clinical_suggestion_import_batches','clinical_suggestion_terms','clinical_suggestion_aliases','clinical_schema_migrations','rating','puskesmas');
	$deleteTables=array('audit_logs','admin_notification_reads','call_sessions','consultation_messages','notifications','request_events','request_staff_assignments','medicalrecords','terapi','konsultasi','requests','locations','puskesmas_staff','m_dokter','users','m_puskesmas','rating','puskesmas');
	foreach($selectTables as $table)$admin->query("GRANT SELECT ON `$database`.`$table` TO `$safeUser`@'%'");foreach($deleteTables as $table)$admin->query("GRANT DELETE ON `$database`.`$table` TO `$safeUser`@'%'");foreach(array('users','puskesmas_staff')as $table)$admin->query("GRANT INSERT ON `$database`.`$table` TO `$safeUser`@'%'");
	$source=(new DoclincNakesSource())->inspect($sourcePath,false);$pii=array();foreach($source['records']as $record){$pii[]=$record['nama'];$pii[]=$record['no_hp'];$pii[]='0'.substr($record['no_hp'],3);}
	$baseArgs=array('--source-xlsx='.$sourcePath,'--format=json');
	$stage='plan';list($code,$out,$err)=integration_cli(array_merge(array('plan-reset-import'),$baseArgs));if($code!==0)fwrite(STDERR,$err);integration_expect($code===0,'plan');$plan=json_decode($out,true);integration_expect(is_array($plan)&&$plan['write_executed']===false&&$plan['source_record_count']===26,'plan_contract');integration_expect((int)$admin->query('SELECT COUNT(*) total FROM requests')->fetch_assoc()['total']===37,'plan_write');
	foreach($pii as $secret)integration_expect(strpos($out.$err,$secret)===false,'pii_output');
	$applyArgs=array_merge(array('apply-reset-import','--apply'),$baseArgs,array('--confirm-database='.$database,'--confirm-source-sha256='.DoclincNakesSource::SHA256,'--confirm-source-record-count=26','--confirm-preserved-puskesmas-count=9','--confirm-preserved-command-center-count=9','--confirm-backup-sha256=test-only','--reset-reference=uat-nakes-reset-20260727T010203Z-integration','--actor-admin-user-id=1'));
	$stage='rollback';$admin->query("CREATE TRIGGER reject_test_import BEFORE INSERT ON users FOR EACH ROW BEGIN IF NEW.username LIKE 'nakes.%' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='test rejection'; END IF; END");list($code,$out,$err)=integration_cli($applyArgs);integration_expect($code!==0&&(int)$admin->query('SELECT COUNT(*) total FROM users')->fetch_assoc()['total']===27&&(int)$admin->query('SELECT COUNT(*) total FROM requests')->fetch_assoc()['total']===37&&(int)$admin->query('SELECT COUNT(*) total FROM audit_logs')->fetch_assoc()['total']===353&&(int)$admin->query("SELECT COUNT(*) total FROM m_puskesmas WHERE kode_pkm='DEFAULT'")->fetch_assoc()['total']===1,'rollback');$admin->query('DROP TRIGGER reject_test_import');
	$adminHash=$admin->query("SELECT password FROM users WHERE userId=1")->fetch_assoc()['password'];$ccRows=$admin->query("SELECT userId,password,email,username,status,remark FROM users WHERE userId BETWEEN 2 AND 10 ORDER BY userId")->fetch_all(MYSQLI_ASSOC);
	$stage='apply';list($code,$out,$err)=integration_cli($applyArgs);if($code!==0)fwrite(STDERR,$err);integration_expect($code===0,'apply');$result=json_decode($out,true);integration_expect(is_array($result)&&$result['transaction_committed']===true&&$result['imported_nakes']===26,'apply_contract');
	$stage='pii_output';foreach($pii as $secret)integration_expect(strpos($out.$err,$secret)===false,'pii_output');
	$stage='preservation';integration_expect($admin->query("SELECT password FROM users WHERE userId=1")->fetch_assoc()['password']===$adminHash,'admin_password');integration_expect($admin->query("SELECT userId,password,email,username,status,remark FROM users WHERE userId BETWEEN 2 AND 10 ORDER BY userId")->fetch_all(MYSQLI_ASSOC)===$ccRows,'cc_preserved');integration_expect((int)$admin->query('SELECT COUNT(*) total FROM audit_logs')->fetch_assoc()['total']===0,'audit_zero');
	$stage='notifications';integration_expect($result['transaction_notifications']===0&&(int)$admin->query('SELECT COUNT(*) total FROM notifications')->fetch_assoc()['total']===0,'transaction_notifications');
	$stage='dummy_dependencies';integration_expect($result['legacy_default_dependencies']===0&&$result['dummy_ratings']===0&&$result['deleted_user_locations']===0&&(int)$admin->query("SELECT COUNT(*) total FROM puskesmas WHERE kode_pkm='DEFAULT'")->fetch_assoc()['total']===0&&(int)$admin->query('SELECT COUNT(*) total FROM rating')->fetch_assoc()['total']===0&&(int)$admin->query('SELECT COUNT(*) total FROM locations')->fetch_assoc()['total']===0,'dummy_dependencies');
	$stage='distribution';$actualDistribution=$result['staff_distribution'];$expectedDistribution=array('10280101'=>3,'10280201'=>4,'10280301'=>3,'10280401'=>2,'10280402'=>3,'10280501'=>3,'10280601'=>2,'10280701'=>3,'2241001'=>3);ksort($actualDistribution);ksort($expectedDistribution);integration_expect($actualDistribution===$expectedDistribution,'staff_distribution');
	$stage='idempotency';list($code,$out,$err)=integration_cli($applyArgs);integration_expect($code!==0&&strpos($err,'pre_reset_count_mismatch')!==false,'already_applied');
	$stage='excessive_grant';$admin->query("GRANT UPDATE ON `$database`.`users` TO `$safeUser`@'%'");list($code,$out,$err)=integration_cli(array_merge(array('plan-reset-import'),$baseArgs));integration_expect($code!==0&&strpos($err,'writer_grants_excessive')!==false,'excessive_grant');$admin->query("REVOKE UPDATE ON `$database`.`users` FROM `$safeUser`@'%'");
	$stage='excessive_object_grant';$admin->query("GRANT INSERT ON `$database`.`audit_logs` TO `$safeUser`@'%'");list($code,$out,$err)=integration_cli(array_merge(array('plan-reset-import'),$baseArgs));integration_expect($code!==0&&strpos($err,'writer_grants_excessive')!==false,'excessive_object_grant');$admin->query("REVOKE INSERT ON `$database`.`audit_logs` FROM `$safeUser`@'%'");
	echo "NAKES_RESET_INTEGRATION=PASS\nPLAN_ZERO_WRITE=PASS\nAUDIT_LOGS_FULL_DELETE=PASS\nCOMMAND_CENTER_PRESERVATION=PASS\nADMIN_PRESERVATION=PASS\nEXISTING_PASSWORD_UNCHANGED=PASS\nDEFAULT_PUSKESMAS_DELETE=PASS\nDUMMY_DEPENDENCIES_ZERO=PASS\nCLINICAL_SUGGESTION_PRESERVATION=PASS\nTRANSACTION_ROLLBACK=PASS\nAUDIT_AND_DEFAULT_ROLLBACK=PASS\nFAILED_ROW_ZERO_PARTIAL=PASS\nALREADY_APPLIED_REFUSAL=PASS\nPHONE_PASSWORD_HASH_CONTRACT=PASS\nPII_OUTPUT_ABSENT=PASS\nM_DOKTER_POST_ZERO=PASS\nCROSS_PUSKESMAS_IDENTITY=PASS\nTRANSACTION_NOTIFICATIONS_ZERO=PASS\nSTAFF_DISTRIBUTION=PASS\nEXCESSIVE_GRANT_REJECTED=PASS\nEXCESSIVE_OBJECT_GRANT_REJECTED=PASS\n";
}catch(Throwable $e){fwrite(STDERR,"NAKES_RESET_INTEGRATION=FAIL\nSAFE_ERROR_CODE=reset_{$stage}_failed\n");exit(1);}finally{if(isset($admin)&&$admin instanceof mysqli)$admin->close();}
