CREATE TABLE `clinical_master_import_batches` (
  `import_batch_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `schema_migration_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `package_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `root_manifest_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `structural_validation_result` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'not_run',
  `package_governance_status` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `production_ready` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `package_runtime_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `source_location_identifier` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
  `import_mode` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `initiated_by_user_id` INT NULL,
  `initiator_identity` VARCHAR(128) NOT NULL,
  `importer_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'planned',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `declared_dataset_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `processed_dataset_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `declared_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `processed_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `inserted_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `skipped_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `failed_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `error_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `warning_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `metadata_json` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `started_at` DATETIME(6) NULL,
  `completed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`import_batch_id`),
  UNIQUE KEY `uq_clinical_import_batch_package` (`package_id`, `package_version`, `root_manifest_sha256`),
  KEY `idx_clinical_import_batch_package_version` (`package_id`, `package_version`),
  KEY `idx_clinical_import_batch_status_created` (`status`, `created_at`),
  KEY `idx_clinical_import_batch_initiator_created` (`initiated_by_user_id`, `created_at`),
  KEY `idx_clinical_import_batch_schema_migration` (`schema_migration_id`),
  CONSTRAINT `fk_clinical_import_batch_schema_migration` FOREIGN KEY (`schema_migration_id`) REFERENCES `clinical_schema_migrations` (`migration_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_clinical_import_batch_sha256` CHECK (`root_manifest_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_import_batch_validation` CHECK (`structural_validation_result` IN ('not_run','pass','fail','error')),
  CONSTRAINT `chk_clinical_import_batch_governance` CHECK (`package_governance_status` IN ('draft','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_import_batch_mode` CHECK (`import_mode` IN ('validate_only','insert_only','reconcile')),
  CONSTRAINT `chk_clinical_import_batch_booleans` CHECK (`production_ready` IN (0,1) AND `package_runtime_enabled` IN (0,1)),
  CONSTRAINT `chk_clinical_import_batch_status` CHECK (`status` IN ('planned','validating','running','completed','failed','cancelled')),
  CONSTRAINT `chk_clinical_import_batch_metadata_json` CHECK (`metadata_json` IS NULL OR JSON_VALID(`metadata_json`) = 1),
  CONSTRAINT `chk_clinical_import_batch_terminal_at` CHECK (`status` NOT IN ('completed','failed','cancelled') OR `completed_at` IS NOT NULL),
  CONSTRAINT `chk_clinical_import_batch_dataset_counts` CHECK (`processed_dataset_count` <= `declared_dataset_count`),
  CONSTRAINT `chk_clinical_import_batch_record_counts` CHECK (`processed_record_count` <= `declared_record_count` AND `processed_record_count` = `inserted_record_count` + `updated_record_count` + `skipped_record_count` + `failed_record_count`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
