CREATE TABLE `clinical_master_import_items` (
  `import_item_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `import_batch_id` BIGINT UNSIGNED NOT NULL,
  `dataset_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `dataset_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `dataset_sha256` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `declared_record_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `processed_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `inserted_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `skipped_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `failed_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `canonical_governance_status` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_runtime_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `status` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'pending',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `error_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `error_summary` VARCHAR(1000) NULL,
  `started_at` DATETIME(6) NULL,
  `completed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`import_item_id`),
  UNIQUE KEY `uq_clinical_import_item_batch_dataset` (`import_batch_id`, `dataset_id`),
  KEY `idx_clinical_import_item_dataset_checksum` (`dataset_id`, `dataset_sha256`),
  KEY `idx_clinical_import_item_batch_status` (`import_batch_id`, `status`),
  CONSTRAINT `fk_clinical_import_item_batch` FOREIGN KEY (`import_batch_id`) REFERENCES `clinical_master_import_batches` (`import_batch_id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_clinical_import_item_sha256` CHECK (`dataset_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_import_item_governance` CHECK (`canonical_governance_status` IN ('draft','in_review','approved','rejected','retired')),
  CONSTRAINT `chk_clinical_import_item_runtime_boolean` CHECK (`source_runtime_enabled` IN (0,1)),
  CONSTRAINT `chk_clinical_import_item_status` CHECK (`status` IN ('pending','running','completed','failed','skipped')),
  CONSTRAINT `chk_clinical_import_item_terminal_at` CHECK (`status` NOT IN ('completed','failed','skipped') OR `completed_at` IS NOT NULL),
  CONSTRAINT `chk_clinical_import_item_counts` CHECK (`processed_count` <= `declared_record_count` AND `processed_count` = `inserted_count` + `updated_count` + `skipped_count` + `failed_count`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
