CREATE TABLE `clinical_schema_migrations` (
  `migration_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `migration_name` VARCHAR(191) NOT NULL,
  `migration_checksum` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `state` VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'applying',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `statement_count` SMALLINT UNSIGNED NOT NULL,
  `last_completed_step` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `execution_environment` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `target_database` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `server_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tool_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `executor_identity` VARCHAR(128) NOT NULL,
  `backup_reference` VARCHAR(191) COLLATE utf8mb4_bin NOT NULL,
  `started_at` DATETIME(6) NOT NULL,
  `applied_at` DATETIME(6) NULL,
  `failed_at` DATETIME(6) NULL,
  `error_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `error_summary` VARCHAR(1000) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`migration_id`),
  UNIQUE KEY `uq_clinical_schema_migration_checksum` (`migration_checksum`),
  KEY `idx_clinical_schema_state_updated` (`state`, `updated_at`),
  CONSTRAINT `chk_clinical_schema_checksum` CHECK (`migration_checksum` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_clinical_schema_state` CHECK (`state` IN ('applying','applied','failed','rolling_back','rolled_back')),
  CONSTRAINT `chk_clinical_schema_step` CHECK (`last_completed_step` <= `statement_count`),
  CONSTRAINT `chk_clinical_schema_applied_at` CHECK (`state` <> 'applied' OR `applied_at` IS NOT NULL),
  CONSTRAINT `chk_clinical_schema_failed_at` CHECK (`state` <> 'failed' OR `failed_at` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci;
